-- Generated by tools/generate_arcs.py; regenerate after geometry edits.
OneCrosshair.ArcAssets = {
    radius = 45.25, thickness = 5.0, length = 90.0,
    extent = 58.75, steps = 64, columns = 8, rows = 16,
}
