-- Targeted Arabic store strings; no font or layout mutation.
if GetCVar("language.2") == "ar" then
    if SI_ACHIEVEMENT_SEARCH_EDIT_DEFAULT then SafeAddString(SI_ACHIEVEMENT_SEARCH_EDIT_DEFAULT, "ﺚﺤﺑ", 1) end
    if SI_ACTIVE_PREVIEW_END_PREVIEW_ACTION then SafeAddString(SI_ACTIVE_PREVIEW_END_PREVIEW_ACTION, "ﺔﻨﻳﺎﻌﻤﻟﺍ ﺀﺎﻬﻧﺇ", 1) end
    if SI_ANTIQUITY_BACK_TO_JOURNAL then SafeAddString(SI_ANTIQUITY_BACK_TO_JOURNAL, "ﻉﻮﺟﺭ", 1) end
    if SI_ANTIQUITY_DIGGING_FANFARE_NEXT then SafeAddString(SI_ANTIQUITY_DIGGING_FANFARE_NEXT, "ﻲﻟﺎﺘﻟﺍ", 1) end
    if SI_ANTIQUITY_SEARCH_EDIT_DEFAULT then SafeAddString(SI_ANTIQUITY_SEARCH_EDIT_DEFAULT, "ﺚﺤﺑ", 1) end
    if SI_BATTLEGROUND_SCOREBOARD_NEXT_PLAYER_KEYBIND then SafeAddString(SI_BATTLEGROUND_SCOREBOARD_NEXT_PLAYER_KEYBIND, "ﻲﻟﺎﺘﻟﺍ", 1) end
    if SI_BATTLEGROUND_SCOREBOARD_PREVIOUS_PLAYER_KEYBIND then SafeAddString(SI_BATTLEGROUND_SCOREBOARD_PREVIOUS_PLAYER_KEYBIND, "ﻖﺑﺎﺴﻟﺍ", 1) end
    if SI_BINDING_NAME_TOGGLE_MARKET then SafeAddString(SI_BINDING_NAME_TOGGLE_MARKET, "ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ", 1) end
    if SI_BUFFS_OPTIONS_ALL_ENABLED then SafeAddString(SI_BUFFS_OPTIONS_ALL_ENABLED, "ﻞﻜﻟﺍ", 1) end
    if SI_BUGCATEGORY4 then SafeAddString(SI_BUGCATEGORY4, "ﺮﺻﺎﻨﻋ", 1) end
    if SI_CAMPAIGN_BONUSES_HOME_KEEP_ALL then SafeAddString(SI_CAMPAIGN_BONUSES_HOME_KEEP_ALL, "ﻞﻜﻟﺍ", 1) end
    if SI_CANCEL then SafeAddString(SI_CANCEL, "ﺀﺎﻐﻟﺇ", 1) end
    if SI_CHAMPION_CONFIRM_SPEND_POINTS_ACTION then SafeAddString(SI_CHAMPION_CONFIRM_SPEND_POINTS_ACTION, "ﺪﻴﻛﺄﺗ", 2) end
    if SI_COLLECTIBLECATEGORYTYPE0 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE0, "ﺢﻟﺎﺻ ﺮﻴﻏ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE1 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE1, "ﻞﻳﺰﻨﺘﻠﻟ ﻞﺑﺎﻗ ﻯﻮﺘﺤﻣ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE10 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE10, "ﺔﻌﺒﻗ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE11 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE11, "ﺓﺮﺸﺒﻟﺍ ﺮﻬﻈﻣ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE12 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE12, "ﻲﻠﻜﺷ ﻝﻮّﺤﺗ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE13 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE13, "ﺮﻌﺸﻟﺍ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE14 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE14, "ﻥﻭﺮﻘﻟﺍ / ﺔﻴﺤﻠﻟﺍ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE15 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE15, "ﺓﺮﻴﺒﻛ ﺔﻨﻳﺯ", 2) end
    if SI_COLLECTIBLECATEGORYTYPE16 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE16, "ﺓﺮﻴﻐﺻ ﺔﻨﻳﺯ", 2) end
    if SI_COLLECTIBLECATEGORYTYPE17 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE17, "ﻪﺟﻮﻟﺍ ﺕﺎﻣﻋ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE18 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE18, "ﻢﺴﺠﻟﺍ ﺕﺎﻣﻋ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE19 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE19, "ﻝﺰﻨﻣ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE2 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE2, "ﺔﻴﻄﻣ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE20 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE20, "ﺙﺎﺛﺃ", 2) end
    if SI_COLLECTIBLECATEGORYTYPE21 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE21, "ﺮﻴﺒﻌﺗ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE22 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE22, "ﻞﺼﻓ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE24 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE24, "ﻱﺰﻟﺍ ﻂﻤﻧ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE25 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE25, "ﻝﺰﻨﻤﻟﺍ ﻥﺰﺨﻣ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE26 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE26, "ﺎﻳﺎﻈﺷ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE27 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE27, "ﻖﻴﻓﺭ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE28 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE28, "ﺓﺩﺎﺷﺍ ﺕﺎﻳﺎﻜﺣ ﻲﻋﺍﺭ", 2) end
    if SI_COLLECTIBLECATEGORYTYPE29 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE29, "ﺔﺼﺼﺨﻣ ﺔﻛﺮﺣ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE3 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE3, "ﻲﻟﺎﺘﻗ ﺮﻴﻏ ﻒﻴﻟﺃ ﻥﺍﻮﻴﺣ", 2) end
    if SI_COLLECTIBLECATEGORYTYPE30 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE30, "ﺓﺭﺎﻬﻤﻟﺍ ﻂﻤﻧ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE4 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE4, "ﻱﺯ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE5 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE5, "ﺭﺎﻛﺬﺗ", 2) end
    if SI_COLLECTIBLECATEGORYTYPE6 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE6, "ﺔﻴﻗﺮﺗ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE7 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE7, "ﺔﻣﺪﺧ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE8 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE8, "ﺪﻋﺎﺴﻣ", 1) end
    if SI_COLLECTIBLECATEGORYTYPE9 then SafeAddString(SI_COLLECTIBLECATEGORYTYPE9, "ﺔﻳﺮﻴﺒﻌﺗ ﺔﻴﺼﺨﺷ", 1) end
    if SI_COLLECTIBLEUNLOCKSTATE0 then SafeAddString(SI_COLLECTIBLEUNLOCKSTATE0, "ﻰﻨﺘﻘﻣ ﺮﻴﻏ", 2) end
    if SI_COLLECTIBLE_ACTION_END_PREVIEW then SafeAddString(SI_COLLECTIBLE_ACTION_END_PREVIEW, "ﺔﻨﻳﺎﻌﻤﻟﺍ ﺀﺎﻬﻧﺇ", 1) end
    if SI_COLLECTIBLE_ACTION_PREVIEW then SafeAddString(SI_COLLECTIBLE_ACTION_PREVIEW, "ﺔﻨﻳﺎﻌﻣ", 1) end
    if SI_COLLECTIBLE_REQUIRED_TO_USE_ITEM_CROWN_STORE then SafeAddString(SI_COLLECTIBLE_REQUIRED_TO_USE_ITEM_CROWN_STORE, ".ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ ﻦﻣ (<<2>>) <<1>> ﻰﻟﺇ ﺝﺎﺘﺤﺗ ،ﻪﻣﺍﺪﺨﺘﺳ", 2) end
    if SI_COLLECTIBLE_REQUIRED_TO_USE_SCRIBING_CROWN_STORE then SafeAddString(SI_COLLECTIBLE_REQUIRED_TO_USE_SCRIBING_CROWN_STORE, "!ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ ﻦﻣ |cffffff(<<2>>) <<1>>|r ﺀﺍﺮﺸﺑ ﻯﻮﺘﺤﻤﻟﺍ ﺍﺬﻫ ﺢﺘﻓ ﻚﻨﻜﻤﻳ", 1) end
    if SI_COLLECTIONS_BOOK_SEARCH_EDIT_DEFAULT then SafeAddString(SI_COLLECTIONS_BOOK_SEARCH_EDIT_DEFAULT, "ﺚﺤﺑ", 2) end
    if SI_COLLECTIONS_CANNOT_PREVIEW_HOUSE_FROM_LOCATION then SafeAddString(SI_COLLECTIONS_CANNOT_PREVIEW_HOUSE_FROM_LOCATION, ".ﺎﻨﻫ ﻝﺰﻨﻤﻟﺍ ﺔﻨﻳﺎﻌﻣ ﻦﻜﻤﻳ ", 1) end
    if SI_COLOR_PICKER_NEW then SafeAddString(SI_COLOR_PICKER_NEW, "ﺪﻳﺪﺟ", 1) end
    if SI_CONFIRM_CLEAR_UNUSED_KEYBINDS_TITLE then SafeAddString(SI_CONFIRM_CLEAR_UNUSED_KEYBINDS_TITLE, "ﺪﻴﻛﺄﺗ", 1) end
    if SI_CONFIRM_MUNDUS_STONE_DECLINE then SafeAddString(SI_CONFIRM_MUNDUS_STONE_DECLINE, "ﺀﺎﻐﻟﺇ", 1) end
    if SI_CONTENT_REQUIRES_COLLECTIBLE_OPEN_CROWN_STORE then SafeAddString(SI_CONTENT_REQUIRES_COLLECTIBLE_OPEN_CROWN_STORE, "ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ ﺢﺘﻓ", 1) end
    if SI_CRAFTING_ENTER_PREVIEW_MODE then SafeAddString(SI_CRAFTING_ENTER_PREVIEW_MODE, "ﺔﻨﻳﺎﻌﻣ", 1) end
    if SI_CRAFTING_EXIT_PREVIEW_MODE then SafeAddString(SI_CRAFTING_EXIT_PREVIEW_MODE, "ﺔﻨﻳﺎﻌﻤﻟﺍ ﺀﺎﻬﻧﺇ", 1) end
    if SI_CRAFTING_QUANTITY_ALL then SafeAddString(SI_CRAFTING_QUANTITY_ALL, "ﻞﻜﻟﺍ", 1) end
    if SI_CROWN_CRATE_CHANGE_CRATE_KEYBIND then SafeAddString(SI_CROWN_CRATE_CHANGE_CRATE_KEYBIND, "ﻉﻮﺟﺭ", 2) end
    if SI_CROWN_CRATE_LEAVE_GEM_EXTRACTION_KEYBIND then SafeAddString(SI_CROWN_CRATE_LEAVE_GEM_EXTRACTION_KEYBIND, "ﻉﻮﺟﺭ", 1) end
    if SI_CROWN_STORE_MENU_CROWN_STORE_LABEL then SafeAddString(SI_CROWN_STORE_MENU_CROWN_STORE_LABEL, "ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ", 1) end
    if SI_CROWN_STORE_MENU_DAILY_LOGIN_LABEL then SafeAddString(SI_CROWN_STORE_MENU_DAILY_LOGIN_LABEL, "ﺔﻴﻣﻮﻴﻟﺍ ﺕﺂﻓﺎﻜﻤﻟﺍ", 1) end
    if SI_CROWN_STORE_MENU_GIFT_INVENTORY_LABEL then SafeAddString(SI_CROWN_STORE_MENU_GIFT_INVENTORY_LABEL, "ﺎﻳﺍﺪﻬﻟﺍ ﻥﻭﺰﺨﻣ", 1) end
    if SI_CROWN_STORE_MENU_SEALS_STORE_LABEL then SafeAddString(SI_CROWN_STORE_MENU_SEALS_STORE_LABEL, "ﻡﺎﺘﺧﺍ", 4) end
    if SI_CROWN_STORE_MENU_TRADE_BAR_STORE_LABEL then SafeAddString(SI_CROWN_STORE_MENU_TRADE_BAR_STORE_LABEL, "ﻲﺒﻫﺬﻟﺍ ﻞﺣﺎﺴﻟﺍ ﻕﻮﺳ", 1) end
    if SI_CROWN_STORE_SEARCH_ADDITIONAL_ARMORY_SLOTS then SafeAddString(SI_CROWN_STORE_SEARCH_ADDITIONAL_ARMORY_SLOTS, "ﺔﻧﺎﺳﺮﺘﻟﺍ ﺕﺎﻧﺎﺧ", 1) end
    if SI_CROWN_STORE_SEARCH_ADDITIONAL_OUTFITS then SafeAddString(SI_CROWN_STORE_SEARCH_ADDITIONAL_OUTFITS, "ﻱﺰﻟﺍ ﺔﻧﺎﺧ", 1) end
    if SI_CROWN_STORE_SEARCH_CRAFT_ITEMS then SafeAddString(SI_CROWN_STORE_SEARCH_CRAFT_ITEMS, "ﻊﻨﺼﻟﺍ ﺮﺻﺎﻨﻋ", 1) end
    if SI_CROWN_STORE_SEARCH_CROWN_CRATES then SafeAddString(SI_CROWN_STORE_SEARCH_CROWN_CRATES, "ﻥﺎﺠﻴﺘﻟﺍ ﻕﻭﺪﻨﺻ", 1) end
    if SI_CROWN_STORE_SEARCH_OUTFIT_CURRENCY then SafeAddString(SI_CROWN_STORE_SEARCH_OUTFIT_CURRENCY, "ﻱﺰﻟﺍ ﺔﻠﻤﻋ", 1) end
    if SI_CROWN_STORE_TITLE then SafeAddString(SI_CROWN_STORE_TITLE, "ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ", 1) end
    if SI_DAILY_LOGIN_REWARDS_END_PREVIEW_KEYBIND then SafeAddString(SI_DAILY_LOGIN_REWARDS_END_PREVIEW_KEYBIND, "ﺔﻨﻳﺎﻌﻤﻟﺍ ﺀﺎﻬﻧﺇ", 1) end
    if SI_DAILY_LOGIN_REWARDS_PREVIEW_KEYBIND then SafeAddString(SI_DAILY_LOGIN_REWARDS_PREVIEW_KEYBIND, "ﺔﻨﻳﺎﻌﻣ", 1) end
    if SI_DIALOG_BACK then SafeAddString(SI_DIALOG_BACK, "ﻉﻮﺟﺭ", 1) end
    if SI_DIALOG_BUTTON_REMOVE_VISITOR_PERMISSION then SafeAddString(SI_DIALOG_BUTTON_REMOVE_VISITOR_PERMISSION, "ﺪﻴﻛﺄﺗ", 1) end
    if SI_DIALOG_BUTTON_TEXT_LOGOUT_CANCEL then SafeAddString(SI_DIALOG_BUTTON_TEXT_LOGOUT_CANCEL, "ﺀﺎﻐﻟﺇ", 1) end
    if SI_DIALOG_BUTTON_TEXT_QUIT_CANCEL then SafeAddString(SI_DIALOG_BUTTON_TEXT_QUIT_CANCEL, "ﺀﺎﻐﻟﺇ", 1) end
    if SI_DIALOG_CANCEL then SafeAddString(SI_DIALOG_CANCEL, "ﺀﺎﻐﻟﺇ", 3) end
    if SI_DIALOG_CONFIRM then SafeAddString(SI_DIALOG_CONFIRM, "ﺪﻴﻛﺄﺗ", 3) end
    if SI_DIALOG_EXIT then SafeAddString(SI_DIALOG_EXIT, "ﺝﻭﺮﺧ", 1) end
    if SI_DIALOG_PURCHASE then SafeAddString(SI_DIALOG_PURCHASE, "ﺀﺍﺮﺷ", 3) end
    if SI_DLC_BOOK_ACTION_OPEN_CROWN_STORE then SafeAddString(SI_DLC_BOOK_ACTION_OPEN_CROWN_STORE, "ﻢﺋﺍﺩ ﻞﻜﺸﺑ ﺢﺘﻓ", 1) end
    if SI_ERROR_PREVIEW_MOUNT_PASSENGER then SafeAddString(SI_ERROR_PREVIEW_MOUNT_PASSENGER, ".ﺪﻋﺎﻘﻤﻟﺍ ﺓﺩﺪﻌﺘﻣ ﺔﻴﻄﻣ ﻰﻠﻋ ﺐﻛﺍﺭ ﺖﻧﺃﻭ ﺔﻨﻳﺎﻌﻤﻟﺍ ﻚﻨﻜﻤﻳ ", 1) end
    if SI_EULATYPE_NEGATIVEBUTTONTEXT3 then SafeAddString(SI_EULATYPE_NEGATIVEBUTTONTEXT3, "ﺀﺎﻐﻟﺇ", 1) end
    if SI_EXIT_BUTTON then SafeAddString(SI_EXIT_BUTTON, "ﺝﻭﺮﺧ", 1) end
    if SI_EXIT_HIDEYHOLE then SafeAddString(SI_EXIT_HIDEYHOLE, "ﺝﻭﺮﺧ", 1) end
    if SI_FRIENDS_LIST_PANEL_SEARCH then SafeAddString(SI_FRIENDS_LIST_PANEL_SEARCH, ":ﺐﺴﺣ ﺔﻴﻔﺼﺗ", 1) end
    if SI_GAMECAMERAACTIONTYPE1 then SafeAddString(SI_GAMECAMERAACTIONTYPE1, "ﺚﺤﺑ", 2) end
    if SI_GAMECAMERAACTIONTYPE25 then SafeAddString(SI_GAMECAMERAACTIONTYPE25, "ﺔﻨﻳﺎﻌﻣ", 1) end
    if SI_GAMECAMERAACTIONTYPE26 then SafeAddString(SI_GAMECAMERAACTIONTYPE26, "ﺝﻭﺮﺧ", 1) end
    if SI_GAMEPADITEMCATEGORY9 then SafeAddString(SI_GAMEPADITEMCATEGORY9, "ﻱﺯ", 1) end
    if SI_GAMEPAD_BACK_OPTION then SafeAddString(SI_GAMEPAD_BACK_OPTION, "ﻉﻮﺟﺭ", 1) end
    if SI_GAMEPAD_BANK_SEARCH_DEFAULT_TEXT then SafeAddString(SI_GAMEPAD_BANK_SEARCH_DEFAULT_TEXT, "ﺚﺤﺑ", 1) end
    if SI_GAMEPAD_CAMPAIGN_BROWSER_CONFIRM_HOME_CAMPAIGN_DIALOG_TITLE then SafeAddString(SI_GAMEPAD_CAMPAIGN_BROWSER_CONFIRM_HOME_CAMPAIGN_DIALOG_TITLE, "ﺪﻴﻛﺄﺗ", 1) end
    if SI_GAMEPAD_DLC_BOOK_ACTION_OPEN_CROWN_STORE then SafeAddString(SI_GAMEPAD_DLC_BOOK_ACTION_OPEN_CROWN_STORE, "ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ ﺢﺘﻓ", 1) end
    if SI_GAMEPAD_FURNITURE_TEXT_FILTER_KEYBIND_TEXT then SafeAddString(SI_GAMEPAD_FURNITURE_TEXT_FILTER_KEYBIND_TEXT, "ﺚﺤﺑ", 1) end
    if SI_GAMEPAD_GUILD_HISTORY_PAGE_NEXT then SafeAddString(SI_GAMEPAD_GUILD_HISTORY_PAGE_NEXT, "ﻲﻟﺎﺘﻟﺍ", 1) end
    if SI_GAMEPAD_GUILD_HISTORY_PAGE_PREVIOUS then SafeAddString(SI_GAMEPAD_GUILD_HISTORY_PAGE_PREVIOUS, "ﻖﺑﺎﺴﻟﺍ", 1) end
    if SI_GAMEPAD_GUILD_LIST_NEW_HEADER then SafeAddString(SI_GAMEPAD_GUILD_LIST_NEW_HEADER, "ﺪﻳﺪﺟ", 1) end
    if SI_GAMEPAD_HELP_SEARCH then SafeAddString(SI_GAMEPAD_HELP_SEARCH, "ﺚﺤﺑ", 1) end
    if SI_GAMEPAD_INVENTORY_DESTROY_CONFIRM_HEADER then SafeAddString(SI_GAMEPAD_INVENTORY_DESTROY_CONFIRM_HEADER, "ﺪﻴﻛﺄﺗ", 1) end
    if SI_GAMEPAD_MAIL_SEND_ITEMS_HEADER then SafeAddString(SI_GAMEPAD_MAIL_SEND_ITEMS_HEADER, "ﺮﺻﺎﻨﻋ", 1) end
    if SI_GAMEPAD_MAIN_MENU_CROWN_STORE_CATEGORY then SafeAddString(SI_GAMEPAD_MAIN_MENU_CROWN_STORE_CATEGORY, "ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ", 1) end
    if SI_GAMEPAD_MAIN_MENU_CROWN_STORE_ENTRY then SafeAddString(SI_GAMEPAD_MAIN_MENU_CROWN_STORE_ENTRY, "ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ", 1) end
    if SI_GAMEPAD_MAIN_MENU_MARKET_BALANCE_TITLE then SafeAddString(SI_GAMEPAD_MAIN_MENU_MARKET_BALANCE_TITLE, "ﺪﻴﺻﺮﻟﺍ", 1) end
    if SI_GAMEPAD_MAIN_MENU_SEAL_MARKET_ENTRY then SafeAddString(SI_GAMEPAD_MAIN_MENU_SEAL_MARKET_ENTRY, "ﻡﺎﺘﺧﺍ", 1) end
    if SI_GAMEPAD_MAIN_MENU_TRADE_BAR_MARKET_ENTRY then SafeAddString(SI_GAMEPAD_MAIN_MENU_TRADE_BAR_MARKET_ENTRY, "ﻲﺒﻫﺬﻟﺍ ﻞﺣﺎﺴﻟﺍ ﻕﻮﺳ", 1) end
    if SI_GAMEPAD_MARKET_BUNDLES then SafeAddString(SI_GAMEPAD_MARKET_BUNDLES, "ﻡﺰﺤﻟﺍ", 1) end
    if SI_GAMEPAD_MARKET_BUNDLES_TOOLTIP_INCLUDE_MESSAGE then SafeAddString(SI_GAMEPAD_MARKET_BUNDLES_TOOLTIP_INCLUDE_MESSAGE, ":ﻰﻠﻋ ﺔﻣﺰﺤﻟﺍ ﻩﺬﻫ ﻱﻮﺘﺤﺗ", 1) end
    if SI_GAMEPAD_MARKET_BUNDLES_TOOLTIP_PRICE then SafeAddString(SI_GAMEPAD_MARKET_BUNDLES_TOOLTIP_PRICE, "ﺔﻔﻠﻜﺘﻟﺍ", 1) end
    if SI_GAMEPAD_MARKET_BUY_PLUS_KEYBIND_LABEL then SafeAddString(SI_GAMEPAD_MARKET_BUY_PLUS_KEYBIND_LABEL, "ESO Plus ﻙﺍﺮﺘﺷﺍ ﺀﺍﺮﺷ", 1) end
    if SI_GAMEPAD_MARKET_CONFIRM_PURCHASE_BUY_NOW_LABEL then SafeAddString(SI_GAMEPAD_MARKET_CONFIRM_PURCHASE_BUY_NOW_LABEL, "ﻥﺍ ﺀﺍﺮﺸﻟﺍ", 1) end
    if SI_GAMEPAD_MARKET_CONFIRM_PURCHASE_COST_LABEL then SafeAddString(SI_GAMEPAD_MARKET_CONFIRM_PURCHASE_COST_LABEL, "ﺔﻔﻠﻜﺘﻟﺍ", 1) end
    if SI_GAMEPAD_MARKET_CONFIRM_PURCHASE_ESO_PLUS_COST_LABEL then SafeAddString(SI_GAMEPAD_MARKET_CONFIRM_PURCHASE_ESO_PLUS_COST_LABEL, "ESO Plus ﺮﻌﺳ", 1) end
    if SI_GAMEPAD_MARKET_CONFIRM_PURCHASE_LABEL then SafeAddString(SI_GAMEPAD_MARKET_CONFIRM_PURCHASE_LABEL, ".ﺀﺍﺮﺸﻟﺍ ﺔﻴﻠﻤﻋ ﺪﻛّﺃ", 1) end
    if SI_GAMEPAD_MARKET_CONFIRM_PURCHASE_NORMAL_COST_LABEL then SafeAddString(SI_GAMEPAD_MARKET_CONFIRM_PURCHASE_NORMAL_COST_LABEL, "ﻱﺩﺎﻌﻟﺍ ﺮﻌﺴﻟﺍ", 1) end
    if SI_GAMEPAD_MARKET_FILTER_SET_FILTER then SafeAddString(SI_GAMEPAD_MARKET_FILTER_SET_FILTER, "ﺔﻴﻔﺼﺗ", 1) end
    if SI_GAMEPAD_MARKET_FREE_TRIAL_TILE_ACTIVE_TEXT then SafeAddString(SI_GAMEPAD_MARKET_FREE_TRIAL_TILE_ACTIVE_TEXT, "ﻂﺸﻧ", 1) end
    if SI_GAMEPAD_MARKET_FREE_TRIAL_TILE_TEXT then SafeAddString(SI_GAMEPAD_MARKET_FREE_TRIAL_TILE_TEXT, "!ﻥﺍ ﺃﺪﺒﺗ", 1) end
    if SI_GAMEPAD_MARKET_FREE_TRIAL_TILE_TITLE then SafeAddString(SI_GAMEPAD_MARKET_FREE_TRIAL_TILE_TITLE, "!ESO Plus ﻙﺍﺮﺘﺷ ﺔﻴﻧﺎﺠﻣ ﺔﺑﺮﺠﺗ", 1) end
    if SI_GAMEPAD_MARKET_FUNDS_LABEL then SafeAddString(SI_GAMEPAD_MARKET_FUNDS_LABEL, "ﻲﻘﺒﺘﻤﻟﺍ ﺪﻴﺻﺮﻟﺍ", 2) end
    if SI_GAMEPAD_MARKET_LOCKED_TITLE then SafeAddString(SI_GAMEPAD_MARKET_LOCKED_TITLE, "ﺡﺎﺘﻣ", 1) end
    if SI_GAMEPAD_MARKET_MEMBERSHIP_INFO_TILE_ACTIVE_TEXT then SafeAddString(SI_GAMEPAD_MARKET_MEMBERSHIP_INFO_TILE_ACTIVE_TEXT, "ﻂﺸﻧ ﻙﺍﺮﺘﺷﺍ", 1) end
    if SI_GAMEPAD_MARKET_MEMBERSHIP_INFO_TILE_TEXT then SafeAddString(SI_GAMEPAD_MARKET_MEMBERSHIP_INFO_TILE_TEXT, "!ﻡﻮﻴﻟﺍ ﻙﺮﺘﺷﺍ", 1) end
    if SI_GAMEPAD_MARKET_MEMBERSHIP_INFO_TILE_TITLE then SafeAddString(SI_GAMEPAD_MARKET_MEMBERSHIP_INFO_TILE_TITLE, "ESO Plus ﺔﻳﻮﻀﻋ", 1) end
    if SI_GAMEPAD_MARKET_PRESCENE_LOADING then SafeAddString(SI_GAMEPAD_MARKET_PRESCENE_LOADING, "ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ ﺢﺘﻓ ﺭٍﺎﺟ", 1) end
    if SI_GAMEPAD_MARKET_PURCHASE_BUNDLE_KEYBIND then SafeAddString(SI_GAMEPAD_MARKET_PURCHASE_BUNDLE_KEYBIND, "ﺔﻣﺰﺤﻟﺍ ﺀﺍﺮﺷ", 1) end
    if SI_GAMEPAD_MARKET_SEARCH_PROMPT then SafeAddString(SI_GAMEPAD_MARKET_SEARCH_PROMPT, "ﺚﺤﺒﻟﺍ ﺺﻧ ﻞﺧﺩﺃ", 1) end
    if SI_GAMEPAD_MARKET_TITLE then SafeAddString(SI_GAMEPAD_MARKET_TITLE, "ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ", 1) end
    if SI_GAMEPAD_MARKET_VIEW_BENEFITS_KEYBIND then SafeAddString(SI_GAMEPAD_MARKET_VIEW_BENEFITS_KEYBIND, "ﺎﻳﺍﺰﻤﻟﺍ ﺽﺮﻋ", 1) end
    if SI_GAMEPAD_MOD_BROWSER_DEFAULT_SEARCH_TEXT then SafeAddString(SI_GAMEPAD_MOD_BROWSER_DEFAULT_SEARCH_TEXT, "ﺚﺤﺑ", 1) end
    if SI_GAMEPAD_OUTFITS_DEFAULT_SEARCH_TEXT then SafeAddString(SI_GAMEPAD_OUTFITS_DEFAULT_SEARCH_TEXT, "ﺚﺤﺑ", 1) end
    if SI_GAMEPAD_PREVIEW_NEXT then SafeAddString(SI_GAMEPAD_PREVIEW_NEXT, "ﻲﻟﺎﺘﻟﺍ", 1) end
    if SI_GAMEPAD_PREVIEW_PREVIOUS then SafeAddString(SI_GAMEPAD_PREVIEW_PREVIOUS, "ﻖﺑﺎﺴﻟﺍ", 1) end
    if SI_GAMEPAD_SKILLS_PURCHASE then SafeAddString(SI_GAMEPAD_SKILLS_PURCHASE, "ﺀﺍﺮﺷ", 1) end
    if SI_GAMEPAD_TOOLTIP_WAYSHRINE_PREVIEW_HOUSE_INTERACT then SafeAddString(SI_GAMEPAD_TOOLTIP_WAYSHRINE_PREVIEW_HOUSE_INTERACT, ".ﺎﻨﻫ ﻰﻟﺇ ﻲﻧﺍ ﻝﺎﻘﺘﻧﻟ <<1>> ﻂﻐﺿﺍ", 1) end
    if SI_GAMEPAD_TRADING_HOUSE_CONFIRM_BUY_DIALOG_TITLE then SafeAddString(SI_GAMEPAD_TRADING_HOUSE_CONFIRM_BUY_DIALOG_TITLE, "ﺀﺍﺮﺷ", 1) end
    if SI_GAMEPAD_TRADING_HOUSE_CREATE_LISTING_CONFIRM then SafeAddString(SI_GAMEPAD_TRADING_HOUSE_CREATE_LISTING_CONFIRM, "ﺪﻴﻛﺄﺗ", 1) end
    if SI_GAMEPLAY_OPTIONS_ITEMS then SafeAddString(SI_GAMEPLAY_OPTIONS_ITEMS, "ﺮﺻﺎﻨﻋ", 1) end
    if SI_GAMMA_DECLINE then SafeAddString(SI_GAMMA_DECLINE, "ﻉﻮﺟﺭ", 1) end
    if SI_GEMIFIABLEFILTERTYPE0 then SafeAddString(SI_GEMIFIABLEFILTERTYPE0, "ﻞﻜﻟﺍ", 1) end
    if SI_GIFT_INVENTORY_VIEW_WINDOW_END_PREVIEW_KEYBIND then SafeAddString(SI_GIFT_INVENTORY_VIEW_WINDOW_END_PREVIEW_KEYBIND, "ﺔﻨﻳﺎﻌﻤﻟﺍ ﺀﺎﻬﻧﺇ", 1) end
    if SI_GIFT_INVENTORY_VIEW_WINDOW_PREVIEW_KEYBIND then SafeAddString(SI_GIFT_INVENTORY_VIEW_WINDOW_PREVIEW_KEYBIND, "ﺔﻳﺪﻬﻟﺍ ﺽﺮﻋ", 1) end
    if SI_GIFT_SENDING_BACK_KEYBIND_LABEL then SafeAddString(SI_GIFT_SENDING_BACK_KEYBIND_LABEL, "ﻉﻮﺟﺭ", 1) end
    if SI_GROUP_FINDER_CONFIRM_EDIT_GROUP then SafeAddString(SI_GROUP_FINDER_CONFIRM_EDIT_GROUP, "ﺪﻴﻛﺄﺗ", 2) end
    if SI_GROUP_FINDER_CREATE_EDIT_BACK then SafeAddString(SI_GROUP_FINDER_CREATE_EDIT_BACK, "ﻉﻮﺟﺭ", 1) end
    if SI_GUILDHISTORYEVENTSUBCATEGORY0 then SafeAddString(SI_GUILDHISTORYEVENTSUBCATEGORY0, "ﻞﻜﻟﺍ", 1) end
    if SI_GUILD_BROWSER_APPLICATIONS_RESCIND_DIALOG_CANCEL_BUTTON then SafeAddString(SI_GUILD_BROWSER_APPLICATIONS_RESCIND_DIALOG_CANCEL_BUTTON, "ﺪﻴﻛﺄﺗ", 1) end
    if SI_GUILD_BROWSER_GUILD_INFO_BACK_BUTTON then SafeAddString(SI_GUILD_BROWSER_GUILD_INFO_BACK_BUTTON, "ﻉﻮﺟﺭ", 1) end
    if SI_GUILD_BROWSER_GUILD_INFO_EXIT then SafeAddString(SI_GUILD_BROWSER_GUILD_INFO_EXIT, "ﺝﻭﺮﺧ", 1) end
    if SI_GUILD_BROWSER_GUILD_INFO_EXIT_BUTTON then SafeAddString(SI_GUILD_BROWSER_GUILD_INFO_EXIT_BUTTON, "ﺝﻭﺮﺧ", 1) end
    if SI_GUILD_HERALDRY_DIALOG_CANCEL then SafeAddString(SI_GUILD_HERALDRY_DIALOG_CANCEL, "ﺀﺎﻐﻟﺇ", 1) end
    if SI_GUILD_HISTORY_SUBCATEGORY_ALL then SafeAddString(SI_GUILD_HISTORY_SUBCATEGORY_ALL, "ﻞﻜﻟﺍ", 1) end
    if SI_GUILD_RANKS_CANCEL then SafeAddString(SI_GUILD_RANKS_CANCEL, "ﺀﺎﻐﻟﺇ", 1) end
    if SI_HOOK_POINT_STORE_PURCHASE then SafeAddString(SI_HOOK_POINT_STORE_PURCHASE, "ﺀﺍﺮﺷ", 1) end
    if SI_HOUSE_TEMPLATE_PREVIEW_BUTTON_TEXT then SafeAddString(SI_HOUSE_TEMPLATE_PREVIEW_BUTTON_TEXT, "ﺔﻨﻳﺎﻌﻣ", 1) end
    if SI_HOUSINGFURNITUREBOUNDFILTER0 then SafeAddString(SI_HOUSINGFURNITUREBOUNDFILTER0, "ﻞﻜﻟﺍ", 1) end
    if SI_HOUSINGFURNITURELOCATIONFILTER1 then SafeAddString(SI_HOUSINGFURNITURELOCATIONFILTER1, "ﻞﻜﻟﺍ", 1) end
    if SI_HOUSING_BOOK_ACTION_PREVIEW_HOUSE then SafeAddString(SI_HOUSING_BOOK_ACTION_PREVIEW_HOUSE, "ﻝﺰﻨﻤﻟﺍ ﺔﻨﻳﺎﻌﻣ", 1) end
    if SI_HOUSING_EDITOR_CANCEL then SafeAddString(SI_HOUSING_EDITOR_CANCEL, "ﺀﺎﻐﻟﺇ", 1) end
    if SI_HOUSING_EDITOR_END_PREVIEW_PLACEMENT then SafeAddString(SI_HOUSING_EDITOR_END_PREVIEW_PLACEMENT, "ﻉﻮﺟﺭ", 1) end
    if SI_HOUSING_EDITOR_EXIT_LINK then SafeAddString(SI_HOUSING_EDITOR_EXIT_LINK, "ﺪﻴﻛﺄﺗ", 2) end
    if SI_HOUSING_EDITOR_EXIT_PATH then SafeAddString(SI_HOUSING_EDITOR_EXIT_PATH, "ﺪﻴﻛﺄﺗ", 1) end
    if SI_HOUSING_EDITOR_PREVIEW_PLACEMENT then SafeAddString(SI_HOUSING_EDITOR_PREVIEW_PLACEMENT, "ﻊﺿﻮﻟﺍ ﺔﻨﻳﺎﻌﻣ", 1) end
    if SI_HOUSING_ENABLE_PREVIEW_INSPECTION_MODE_CHECKBOX then SafeAddString(SI_HOUSING_ENABLE_PREVIEW_INSPECTION_MODE_CHECKBOX, "ﺺﺤﻔﻟﺍ ﻊﺿﻭ", 1) end
    if SI_HOUSING_ENABLE_PREVIEW_INSPECTION_MODE_TOOLTIP then SafeAddString(SI_HOUSING_ENABLE_PREVIEW_INSPECTION_MODE_TOOLTIP, ".ﺎﻬﻓﺪﻬﺘﺴﺗ ﻲﺘﻟﺍ ﺙﺎﺛﺍ ﺔﻌﻄﻗ ﻰﻠﻋ ﻑﺮّﻌﺘﻟﺍ ﺺﺤﻔﻟﺍ ﻊﺿﻭ ﺢﻴﺘﻳ", 1) end
    if SI_HOUSING_FURNITURE_BROWSER_PURCHASE_KEYBIND then SafeAddString(SI_HOUSING_FURNITURE_BROWSER_PURCHASE_KEYBIND, "ﺀﺍﺮﺷ", 1) end
    if SI_HOUSING_FURNITURE_NO_MARKET_PRODUCTS then SafeAddString(SI_HOUSING_FURNITURE_NO_MARKET_PRODUCTS, ".ﺀﺍﺮﺸﻠﻟ ﺡﺎﺘﻣ ﺙﺎﺛﺃ ﺪﺟﻮﻳ ", 1) end
    if SI_HOUSING_FURNITURE_TAB_PURCHASE then SafeAddString(SI_HOUSING_FURNITURE_TAB_PURCHASE, "ﺀﺍﺮﺷ", 1) end
    if SI_HOUSING_FURNITURE_TEXT_FILTER_DEFAULT_TEXT then SafeAddString(SI_HOUSING_FURNITURE_TEXT_FILTER_DEFAULT_TEXT, "ﺚﺤﺑ", 1) end
    if SI_HOUSING_PREVIEW_INSPECTION_MODE_DISABLED then SafeAddString(SI_HOUSING_PREVIEW_INSPECTION_MODE_DISABLED, ".ﺺﺤﻔﻟﺍ ﻊﺿﻭ ﻞﻴﻄﻌﺗ ﻢﺗ", 1) end
    if SI_HOUSING_PREVIEW_INSPECTION_MODE_ENABLED then SafeAddString(SI_HOUSING_PREVIEW_INSPECTION_MODE_ENABLED, ".ﺺﺤﻔﻟﺍ ﻊﺿﻭ ﻞﻴﻌﻔﺗ ﻢﺗ", 1) end
    if SI_HOUSING_PREVIEW_NOT_AVAILABLE_FOR_PURCHASE then SafeAddString(SI_HOUSING_PREVIEW_NOT_AVAILABLE_FOR_PURCHASE, ".ﺎﻴًﻟﺎﺣ ﻊﻴﺒﻠﻟ ﺽﻭﺮﻌﻣ ﺮﻴﻏ ﻝﺰﻨﻤﻟﺍ ﺍﺬﻫ", 1) end
    if SI_HOUSING_PREVIEW_PURCHASE_FOR_GOLD_BODY then SafeAddString(SI_HOUSING_PREVIEW_PURCHASE_FOR_GOLD_BODY, "؟|cffffff<<3>>|r ﻞﺑﺎﻘﻣ |cffffff(<<2>>) <<1>>|r ﺀﺍﺮﺷ ﺪﻳﺮﺗ ﻞﻫ", 1) end
    if SI_HOUSING_PREVIEW_PURCHASE_FOR_GOLD_TITLE then SafeAddString(SI_HOUSING_PREVIEW_PURCHASE_FOR_GOLD_TITLE, "ﺀﺍﺮﺸﻟﺍ ﺪﻴﻛﺄﺗ", 1) end
    if SI_HOUSING_PREVIEW_TEMPLATE_FURNISHINGS then SafeAddString(SI_HOUSING_PREVIEW_TEMPLATE_FURNISHINGS, "ﺙﺎﺛﺍ", 1) end
    if SI_HOUSING_TOGGLE_PREVIEW_INSPECTION_MODE_ACTION then SafeAddString(SI_HOUSING_TOGGLE_PREVIEW_INSPECTION_MODE_ACTION, "ﺺﺤﻔﻟﺍ ﻊﺿﻭ ﻞﻴﻄﻌﺗ/ﻞﻴﻌﻔﺗ", 1) end
    if SI_INTERFACE_OPTIONS_ACCOUNT_MARKETING_HEADER then SafeAddString(SI_INTERFACE_OPTIONS_ACCOUNT_MARKETING_HEADER, "ﺕﺎﻧﻋﺍ ﺕﻴﻀﻔﺗ", 1) end
    if SI_INTERFACE_OPTIONS_COMBAT_SCT_ENABLED then SafeAddString(SI_INTERFACE_OPTIONS_COMBAT_SCT_ENABLED, "ﻞﻜﻟﺍ", 2) end
    if SI_INVENTORY_MODE_ITEMS then SafeAddString(SI_INVENTORY_MODE_ITEMS, "ﺮﺻﺎﻨﻋ", 1) end
    if SI_INVENTORY_WALLET_ALL_FILTER then SafeAddString(SI_INVENTORY_WALLET_ALL_FILTER, "ﻞﻜﻟﺍ", 1) end
    if SI_ITEMFILTERTYPE0 then SafeAddString(SI_ITEMFILTERTYPE0, "ﻞﻜﻟﺍ", 1) end
    if SI_ITEMTYPE13 then SafeAddString(SI_ITEMTYPE13, "ﻱﺯ", 1) end
    if SI_ITEMTYPEDISPLAYCATEGORY0 then SafeAddString(SI_ITEMTYPEDISPLAYCATEGORY0, "ﻞﻜﻟﺍ", 1) end
    if SI_ITEM_ACTION_PREVIEW then SafeAddString(SI_ITEM_ACTION_PREVIEW, "ﺔﻨﻳﺎﻌﻣ", 1) end
    if SI_ITEM_ACTION_PREVIEW_DYE_STAMP then SafeAddString(SI_ITEM_ACTION_PREVIEW_DYE_STAMP, "ﻎﺒﺼﻟﺍ ﺔﻨﻳﺎﻌﻣ", 1) end
    if SI_ITEM_FILTER_BY_TEXT then SafeAddString(SI_ITEM_FILTER_BY_TEXT, "ﺚﺤﺑ", 2) end
    if SI_ITEM_FORMAT_STR_SET_COLLECTION_PIECE_LOCKED then SafeAddString(SI_ITEM_FORMAT_STR_SET_COLLECTION_PIECE_LOCKED, "ﻰﻨﺘﻘﻣ ﺮﻴﻏ", 1) end
    if SI_ITEM_RECONSTRUCTION_BACK then SafeAddString(SI_ITEM_RECONSTRUCTION_BACK, "ﻉﻮﺟﺭ", 1) end
    if SI_ITEM_RECONSTRUCTION_EXIT then SafeAddString(SI_ITEM_RECONSTRUCTION_EXIT, "ﺝﻭﺮﺧ", 1) end
    if SI_KEYCODE128 then SafeAddString(SI_KEYCODE128, "ﻉﻮﺟﺭ", 1) end
    if SI_KEYCODE_NARRATIONTEXT128 then SafeAddString(SI_KEYCODE_NARRATIONTEXT128, "ﻉﻮﺟﺭ", 1) end
    if SI_LFG_LOCK_REASON_COLLECTIBLE_NOT_UNLOCKED_CROWN_STORE then SafeAddString(SI_LFG_LOCK_REASON_COLLECTIBLE_NOT_UNLOCKED_CROWN_STORE, ".ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ ﻦﻣ |cffffff(<<2>>) <<1>>|r ﻁﺎﺸﻨﻟﺍ ﺍﺬﻫ ﺐﻠﻄﺘﻳ", 1) end
    if SI_MAIL_INBOX_NEXT then SafeAddString(SI_MAIL_INBOX_NEXT, "ﻲﻟﺎﺘﻟﺍ", 1) end
    if SI_MAIL_INBOX_PREVIOUS then SafeAddString(SI_MAIL_INBOX_PREVIOUS, "ﻖﺑﺎﺴﻟﺍ", 1) end
    if SI_MAIN_MENU_MARKET then SafeAddString(SI_MAIN_MENU_MARKET, "ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ", 1) end
    if SI_MARKETFILTERVIEW1 then SafeAddString(SI_MARKETFILTERVIEW1, "ﻞﻜﻟﺍ ﺭﺎﻬﻇﺇ", 1) end
    if SI_MARKETFILTERVIEW2 then SafeAddString(SI_MARKETFILTERVIEW2, "ﺕﺎﻳﺮﺘﺸﻤﻟﺍ ﺭﺎﻬﻇﺇ", 1) end
    if SI_MARKETFILTERVIEW3 then SafeAddString(SI_MARKETFILTERVIEW3, "ﻯﺮﺘﺸﻤﻟﺍ ﺮﻴﻏ ﺭﺎﻬﻇﺇ", 1) end
    if SI_MARKETINGPREFERENCESREQUESTRESULT1 then SafeAddString(SI_MARKETINGPREFERENCESREQUESTRESULT1, ".ﻥﺍ ﺐﻠﻄﻟﺍ ﺬﻴﻔﻨﺗ ﻦﻜﻤﻳ ", 1) end
    if SI_MARKETINGPREFERENCESREQUESTRESULT2 then SafeAddString(SI_MARKETINGPREFERENCESREQUESTRESULT2, ".ﺀﻤﻌﻟﺍ ﺔﻣﺪﺧ ﻊﻣ ﻞﺻﺍﻮﺘﻟﺍ ﻭﺃ ﺎﻘًﺣ ﺔﻟﻭﺎﺤﻤﻟﺍ ﻰﺟﺮﻳُ .ﻚﺑﺎﺴﺣ ﻰﻟﺇ ﻝﻮﺻﻮﻟﺍ ﺀﺎﻨﺛﺃ ﺄﻄﺧ ﺙﺪﺣ", 1) end
    if SI_MARKETINGPREFERENCESREQUESTRESULT3 then SafeAddString(SI_MARKETINGPREFERENCESREQUESTRESULT3, ".ﺎﻘًﺣ ﺔﻟﻭﺎﺤﻤﻟﺍ ﻰﺟﺮﻳُ .ﺎﻴًﻟﺎﺣ ﺔﺣﺎﺘﻣ ﺮﻴﻏ ﺀﺍﺮﺸﻟﺍ ﺕﺍﺭﺎﻴﺧ", 1) end
    if SI_MARKETPURCHASABLERESULT0 then SafeAddString(SI_MARKETPURCHASABLERESULT0, "ﺡﺎﺠﻨﺑ ﺀﺍﺮﺸﻟﺍ ﻢﺗ", 1) end
    if SI_MARKETPURCHASABLERESULT1 then SafeAddString(SI_MARKETPURCHASABLERESULT1, ".ﺀﺍﺮﺸﻟﺍ ﻡﺎﻤﺗ ﺔﻴﻓﺎﻛ ﺎﻧًﺎﺠﻴﺗ ﻚﻠﻤﺗ ", 1) end
    if SI_MARKETPURCHASABLERESULT10 then SafeAddString(SI_MARKETPURCHASABLERESULT10, ".ﻥﺍ ﺮﺼﻨﻌﻟﺍ ﺍﺬﻫ ﺀﺍﺮﺷ ﻚﻨﻜﻤﻳ  ،ﺍﺭًﺬﻋ", 1) end
    if SI_MARKETPURCHASABLERESULT11 then SafeAddString(SI_MARKETPURCHASABLERESULT11, ".ﻞﻌﻔﻟﺎﺑ ﻞﻣﺎﻜﻟﺎﺑ ﺮﺼﻨﻌﻟﺍ ﺍﺬﻫ ﺖﺤﺘﻓ ﺪﻘﻟ", 2) end
    if SI_MARKETPURCHASABLERESULT12 then SafeAddString(SI_MARKETPURCHASABLERESULT12, ".ﺎﺒًﻳﺮﻗ ﺞﺘﻨﻤﻟﺍ ﺍﺬﻫ ﺮﻓﻮﺘﻴﺳ", 1) end
    if SI_MARKETPURCHASABLERESULT13 then SafeAddString(SI_MARKETPURCHASABLERESULT13, ".ﺀﺍﺮﺸﻟﺍ ﻡﺎﻤﺗ ﺔﻴﻓﺎﻛ ﻥﺎﺠﻴﺗ ﺮﻫﺍﻮﺟ ﻚﻠﻤﺗ ", 1) end
    if SI_MARKETPURCHASABLERESULT14 then SafeAddString(SI_MARKETPURCHASABLERESULT14, ".ﺩﻮﺟﻮﻣ ﺮﻴﻏ ﺞﺘﻨﻤﻟﺍ ﺍﺬﻫ ﻥﺃ ﻭﺪﺒﻳ ،ﺍﺭًﺬﻋ", 1) end
    if SI_MARKETPURCHASABLERESULT15 then SafeAddString(SI_MARKETPURCHASABLERESULT15, "!ﻞﻌﻔﻟﺎﺑ ﺮﺼﻨﻌﻟﺍ ﺍﺬﻫ ﻚﻠﻤﺗ ﺖﻧﺃ", 1) end
    if SI_MARKETPURCHASABLERESULT16 then SafeAddString(SI_MARKETPURCHASABLERESULT16, ".ﺡﺎﺘﻣ ﺮﻴﻏ ﺞﺘﻨﻤﻟﺍ ﺍﺬﻫ", 1) end
    if SI_MARKETPURCHASABLERESULT17 then SafeAddString(SI_MARKETPURCHASABLERESULT17, ".ﺎﻳﺍﺪﻬﻟﺍ ﻝﺎﺳﺭﺇ ﻚﻨﻜﻤﻳ ", 1) end
    if SI_MARKETPURCHASABLERESULT18 then SafeAddString(SI_MARKETPURCHASABLERESULT18, ".ﺞﺘﻨﻤﻟﺍ ﺍﺬﻫ ﺀﺍﺪﻫﺇ ﻚﻨﻜﻤﻳ ", 1) end
    if SI_MARKETPURCHASABLERESULT19 then SafeAddString(SI_MARKETPURCHASABLERESULT19, ".ﺔﻳﺪﻬﻟﺍ ﻩﺬﻫ ﻝﻮﺒﻗ ﺐﻋﻟﺍ ﺍﺬﻬﻟ ﻦﻜﻤﻳ ", 2) end
    if SI_MARKETPURCHASABLERESULT2 then SafeAddString(SI_MARKETPURCHASABLERESULT2, ".ﻚﺴﻔﻨﻟ ﺍﺬﻫ ﺀﺍﺮﺸﻟ ﻚﺘﺒﻴﻘﺣ ﻲﻓ ﺔﻴﻓﺎﻛ ﺔﺣﺎﺴﻣ ﺪﺟﻮﺗ ", 2) end
    if SI_MARKETPURCHASABLERESULT20 then SafeAddString(SI_MARKETPURCHASABLERESULT20, ".ﺎﻨﻫ ﻦﻣ ﺞﺘﻨﻤﻟﺍ ﺍﺬﻫ ﺀﺍﺮﺷ ﻦﻜﻤﻳ ", 1) end
    if SI_MARKETPURCHASABLERESULT21 then SafeAddString(SI_MARKETPURCHASABLERESULT21, ".ﻥﺎﺠﻴﺘﻟﺍ ﺮﻫﺍﻮﺠﺑ ﻯﺮﺘﺸﺗُ ﻲﺘﻟﺍ ﺕﺎﺠﺘﻨﻤﻟﺍ ﺀﺍﺪﻫﺇ ﻚﻨﻜﻤﻳ ", 1) end
    if SI_MARKETPURCHASABLERESULT22 then SafeAddString(SI_MARKETPURCHASABLERESULT22, ".ﻚﻳﺪﻟ ﺎﻳﺍﺪﻬﻟﺍ ﺔﺒﻴﻘﺣ ﻲﻓ ﻞﻌﻔﻟﺎﺑ ﺩﻮﺟﻮﻣ ﺞﺘﻨﻤﻟﺍ ﺍﺬﻫ", 1) end
    if SI_MARKETPURCHASABLERESULT23 then SafeAddString(SI_MARKETPURCHASABLERESULT23, ".ﺪﻌﺑ ﺎﻳﺍﺪﻬﻟﺍ ﻝﺎﺳﺭﺇ ﻚﻨﻜﻤﻳ ", 1) end
    if SI_MARKETPURCHASABLERESULT24 then SafeAddString(SI_MARKETPURCHASABLERESULT24, ".ﺐﻋﻟﺍ ﻰﻠﻋ ﺮﺜﻌﻳُ ﻢﻟ", 1) end
    if SI_MARKETPURCHASABLERESULT25 then SafeAddString(SI_MARKETPURCHASABLERESULT25, ".ﺎﻘًﺣ ﺔﻟﻭﺎﺤﻤﻟﺍ ﻰﺟﺮﻳُ .ﺎﻴًﻟﺎﺣ ﻞﻔﻘﻣ ﺎﻳﺍﺪﻬﻟﺍ ﻝﺎﺳﺭﺇ", 1) end
    if SI_MARKETPURCHASABLERESULT26 then SafeAddString(SI_MARKETPURCHASABLERESULT26, ".ﻞﻌﻔﻟﺎﺑ ﻰﻨﺘﻘﻤﻟﺍ ﺍﺬﻫ ﻚﻠﻤﻳ ﺐﻋﻟﺍ ﺍﺬﻫ", 1) end
    if SI_MARKETPURCHASABLERESULT27 then SafeAddString(SI_MARKETPURCHASABLERESULT27, ".ﺞﺘﻨﻤﻟﺍ ﺍﺬﻫ ﺀﺍﺮﺸﻟ |ceeca2aESO Plus|r ﻙﺍﺮﺘﺷﺍ ﻡﺰﻠﻳ", 2) end
    if SI_MARKETPURCHASABLERESULT28 then SafeAddString(SI_MARKETPURCHASABLERESULT28, ".ﺪﻴﺻﺮﻠﻟ ﻰﺼﻗﺍ ﺪﺤﻟﺍ ﺯﻭﺎﺠﺘﻴﺳ ﻪﻧ ﺍﺬﻫ ﺀﺍﺮﺷ ﻚﻨﻜﻤﻳ ", 2) end
    if SI_MARKETPURCHASABLERESULT29 then SafeAddString(SI_MARKETPURCHASABLERESULT29, ".ﻥﺍ ﺮﺼﻨﻌﻟﺍ ﺍﺬﻫ ﺀﺍﺮﺷ ﻚﻨﻜﻤﻳ  ،ﺍﺭًﺬﻋ", 1) end
    if SI_MARKETPURCHASABLERESULT3 then SafeAddString(SI_MARKETPURCHASABLERESULT3, ".ﺩﻮﺟﻮﻣ ﺮﻴﻏ ﺞﺘﻨﻤﻟﺍ ﺍﺬﻫ ﻥﺃ ﻭﺪﺒﻳ ،ﺍﺭًﺬﻋ", 1) end
    if SI_MARKETPURCHASABLERESULT30 then SafeAddString(SI_MARKETPURCHASABLERESULT30, ".ﺔﺻﺎﺧ ﺕﺍﺭﺪﻗ ﻚﻠﻤﺗ ﻚﺘﻴﺼﺨﺷ ﺖﻣﺍﺩ ﺎﻣ ﺍﺬﻫ ﺀﺍﺮﺷ ﻚﻨﻜﻤﻳ ", 1) end
    if SI_MARKETPURCHASABLERESULT31 then SafeAddString(SI_MARKETPURCHASABLERESULT31, ".ﺊﻠﺘﻤﻣ ﻡﺎﻬﻤﻟﺍ ﻞﺠﺳ", 3) end
    if SI_MARKETPURCHASABLERESULT32 then SafeAddString(SI_MARKETPURCHASABLERESULT32, ".ﻞﻌﻔﻟﺎﺑ ﺔﻤﻬﻤﻟﺍ ﻩﺬﻫ ﺬﻔّﻨﺗ ﺖﻧﺃ", 1) end
    if SI_MARKETPURCHASABLERESULT33 then SafeAddString(SI_MARKETPURCHASABLERESULT33, ".ﻞﻌﻔﻟﺎﺑ ﺔﻤﻬﻤﻟﺍ ﻩﺬﻫ ﺖﻠﻤﻛﺃ ﺪﻘﻟ", 1) end
    if SI_MARKETPURCHASABLERESULT34 then SafeAddString(SI_MARKETPURCHASABLERESULT34, ".ﺔﻤﻬﻤﻟﺍ ﻩﺬﻫ ﻝﻮﺒﻗ ﻚﻨﻜﻤﻳ ", 1) end
    if SI_MARKETPURCHASABLERESULT36 then SafeAddString(SI_MARKETPURCHASABLERESULT36, ".ﺔﻳﺪﻬﻟﺍ ﻝﺎﺳﺭﺇ ﻲﻓ ﻚﺘﺒﻏﺭ ﺪﻴﻛﺄﺗ ًﻭﺃ ﺐﺠﻳ", 1) end
    if SI_MARKETPURCHASABLERESULT37 then SafeAddString(SI_MARKETPURCHASABLERESULT37, ".ﺀﺍﺮﺸﻟﺍ ﻡﺎﻤﺗ ﺔﻴﻓﺎﻛ ﺎﻣًﺎﺘﺧﺃ ﻚﻠﻤﺗ ", 4) end
    if SI_MARKETPURCHASABLERESULT38 then SafeAddString(SI_MARKETPURCHASABLERESULT38, ".ﻡﺎﺘﺧﺍ ﻡﺍﺪﺨﺘﺳﺎﺑ ﺎﻳﺍﺪﻬﻟﺍ ﻝﺎﺳﺭﺇ ﻚﻨﻜﻤﻳ ", 3) end
    if SI_MARKETPURCHASABLERESULT39 then SafeAddString(SI_MARKETPURCHASABLERESULT39, ".ﺔﺤﻟﺎﺻ ﺮﻴﻏ ﺔﻴﻤﻛ", 1) end
    if SI_MARKETPURCHASABLERESULT4 then SafeAddString(SI_MARKETPURCHASABLERESULT4, ".ﻪﺴﻔﻧ ﺪﻳﺮﻔﻟﺍ ﺮﺼﻨﻌﻟﺍ ﻦﻣ ﺔﺨﺴﻧ ﻦﻣ ﺮﺜﻛﺃ ﻞﻤﺣ ﻚﻨﻜﻤﻳ ", 2) end
    if SI_MARKETPURCHASABLERESULT40 then SafeAddString(SI_MARKETPURCHASABLERESULT40, ".ﺔﻴﻤﻜﻠﻟ ﻰﺼﻗﺍ ﺪﺤﻟﺍ ﺯﻭﺎﺠﺘﻳ <<1>>", 1) end
    if SI_MARKETPURCHASABLERESULT41 then SafeAddString(SI_MARKETPURCHASABLERESULT41, ".ﻥﺍ ﺮﺼﻨﻌﻟﺍ ﺍﺬﻫ ﺀﺍﺮﺷ ﻚﻨﻜﻤﻳ  ،ﺍﺭًﺬﻋ", 1) end
    if SI_MARKETPURCHASABLERESULT42 then SafeAddString(SI_MARKETPURCHASABLERESULT42, ".ﺔﻘﻠّﻌﻤﻟﺍ ﺀﺍﺪﻫﺍ ﺕﺎﺒﻠﻃ ﻞﺒﻘﺗُ ﻰﺘﺣ ﺎﻳﺍﺪﻬﻟﺍ ﻦﻣ ﺪﻳﺰﻣ ﻝﺎﺳﺭﺇ ﻚﻨﻜﻤﻳ ", 1) end
    if SI_MARKETPURCHASABLERESULT43 then SafeAddString(SI_MARKETPURCHASABLERESULT43, ".ﺀﺍﺮﺸﻟﺍ ﻡﺎﻤﺗ ﺔﻴﻓﺎﻛ ﺔﻳﺭﺎﺠﺗ ﻚﺋﺎﺒﺳ ﻚﻠﻤﺗ ", 2) end
    if SI_MARKETPURCHASABLERESULT44 then SafeAddString(SI_MARKETPURCHASABLERESULT44, ".ﺔﻳﺭﺎﺠﺘﻟﺍ ﻚﺋﺎﺒﺴﻟﺍ ﻡﺍﺪﺨﺘﺳﺎﺑ ﺎﻳﺍﺪﻬﻟﺍ ﻝﺎﺳﺭﺇ ﻚﻨﻜﻤﻳ ", 2) end
    if SI_MARKETPURCHASABLERESULT45 then SafeAddString(SI_MARKETPURCHASABLERESULT45, ".ﺔﻠﻤﺤﻟﺍ ﻩﺬﻫ ﻲﻓ ﺞﺘﻨﻤﻟﺍ ﺍﺬﻫ ﺀﺍﺮﺷ ﻚﻨﻜﻤﻳ  ،ﺍﺭًﺬﻋ", 1) end
    if SI_MARKETPURCHASABLERESULT5 then SafeAddString(SI_MARKETPURCHASABLERESULT5, ".ﺮﺼﻨﻌﻟﺍ ﺍﺬﻫ ﺀﺍﺮﺷ ﻚﻨﻜﻤﻳ  ،ﺍﺭًﺬﻋ", 1) end
    if SI_MARKETPURCHASABLERESULT6 then SafeAddString(SI_MARKETPURCHASABLERESULT6, ".ﺎﻘًﺣ ﺔﻟﻭﺎﺤﻤﻟﺍ ﻰﺟﺮﻳُ .ﻥﺍ ﺀﺍﺮﺸﻟﺍ ﻡﺎﻤﺗﺇ ﻦﻜﻤﻳ ", 1) end
    if SI_MARKETPURCHASABLERESULT7 then SafeAddString(SI_MARKETPURCHASABLERESULT7, ".ﺩﻮﺟﻮﻣ ﺮﻴﻏ ﺞﺘﻨﻤﻟﺍ ﺍﺬﻫ ﻥﺃ ﻭﺪﺒﻳ ،ﺍﺭًﺬﻋ", 1) end
    if SI_MARKETPURCHASABLERESULT8 then SafeAddString(SI_MARKETPURCHASABLERESULT8, ".ﻞﻌﻔﻟﺎﺑ ﻰﻨﺘﻘﻤﻟﺍ ﺍﺬﻫ ﻚﻠﻤﺗ ﺖﻧﺃ", 2) end
    if SI_MARKETPURCHASABLERESULT9 then SafeAddString(SI_MARKETPURCHASABLERESULT9, ".ﻥﺍ ﺮﺼﻨﻌﻟﺍ ﺍﺬﻫ ﺀﺍﺮﺷ ﻚﻨﻜﻤﻳ  ،ﺍﺭًﺬﻋ", 1) end
    if SI_MARKET_ACTION_END_PREVIEW then SafeAddString(SI_MARKET_ACTION_END_PREVIEW, "ﺔﻨﻳﺎﻌﻤﻟﺍ ﺀﺎﻬﻧﺇ", 1) end
    if SI_MARKET_ACTION_PREVIEW then SafeAddString(SI_MARKET_ACTION_PREVIEW, "ﺔﻨﻳﺎﻌﻣ", 1) end
    if SI_MARKET_ACTION_PURCHASE then SafeAddString(SI_MARKET_ACTION_PURCHASE, "ﺀﺍﺮﺷ", 1) end
    if SI_MARKET_ACTION_PURCHASE_BUNDLE then SafeAddString(SI_MARKET_ACTION_PURCHASE_BUNDLE, "ﺔﻣﺰﺤﻟﺍ ﺀﺍﺮﺷ", 1) end
    if SI_MARKET_ALL_LABEL then SafeAddString(SI_MARKET_ALL_LABEL, "ﻞﻜﻟﺍ", 1) end
    if SI_MARKET_ANNOUNCEMENT_ACTIVITY_FINDER_ACTION then SafeAddString(SI_MARKET_ANNOUNCEMENT_ACTIVITY_FINDER_ACTION, "ﺔﻘﻄﻨﻤﻟﺍ ﻞﻴﻟﺩ ﺢﺘﻓ", 2) end
    if SI_MARKET_ANNOUNCEMENT_HELP_BUTTON then SafeAddString(SI_MARKET_ANNOUNCEMENT_HELP_BUTTON, "ﺕﺎﻣﻮﻠﻌﻤﻟﺍ ﻦﻣ ﺪﻳﺰﻣ", 1) end
    if SI_MARKET_ANNOUNCEMENT_LOCKED_CROWN_STORE_DESCRIPTION then SafeAddString(SI_MARKET_ANNOUNCEMENT_LOCKED_CROWN_STORE_DESCRIPTION, ".ﻡﺩﺎﺨﻟﺍ ﺔﻧﺎﻴﺻ ﺐﺒﺴﺑ ﺡﺎﺘﻣ ﺮﻴﻏ", 1) end
    if SI_MARKET_ANNOUNCEMENT_LOCKED_CROWN_STORE_TITLE then SafeAddString(SI_MARKET_ANNOUNCEMENT_LOCKED_CROWN_STORE_TITLE, "ﺎﺒًﻳﺮﻗ ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ ﺩﻮﻌﻴﺳ", 1) end
    if SI_MARKET_ANNOUNCEMENT_NO_FEATURED_PRODUCTS_TITLE then SafeAddString(SI_MARKET_ANNOUNCEMENT_NO_FEATURED_PRODUCTS_TITLE, "ﺎﻴًﻟﺎﺣ ﺓﺰﻴﻤﻣ ﺕﺎﺠﺘﻨﻣ ﺪﺟﻮﺗ ", 1) end
    if SI_MARKET_ANNOUNCEMENT_PROMOTIONAL_EVENT_ACTION then SafeAddString(SI_MARKET_ANNOUNCEMENT_PROMOTIONAL_EVENT_ACTION, "ﺔﻴﺒﻫﺬﻟﺍ ﻲﻋﺎﺴﻤﻟﺍ", 3) end
    if SI_MARKET_ANNOUNCEMENT_PROMOTIONAL_EVENT_COMPLETE then SafeAddString(SI_MARKET_ANNOUNCEMENT_PROMOTIONAL_EVENT_COMPLETE, "ﻝﺎﻤﻛﺇ", 1) end
    if SI_MARKET_ANNOUNCEMENT_SCROLL_KEYBIND then SafeAddString(SI_MARKET_ANNOUNCEMENT_SCROLL_KEYBIND, "ﻞﻔﺳ ﺮﻳﺮﻤﺘﻟﺍ", 1) end
    if SI_MARKET_ANNOUNCEMENT_TITLE then SafeAddString(SI_MARKET_ANNOUNCEMENT_TITLE, "ﺰﻴﻤﻣ", 2) end
    if SI_MARKET_ANNOUNCEMENT_VIEW_CHAPTER_UPGRADE then SafeAddString(SI_MARKET_ANNOUNCEMENT_VIEW_CHAPTER_UPGRADE, "ﻞﺼﻔﻟﺍ ﺔﻴﻗﺮﺗ", 1) end
    if SI_MARKET_ANNOUNCEMENT_VIEW_CROWN_STORE then SafeAddString(SI_MARKET_ANNOUNCEMENT_VIEW_CROWN_STORE, "ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ ﺢﺘﻓ", 2) end
    if SI_MARKET_ANNOUNCEMENT_WELCOME then SafeAddString(SI_MARKET_ANNOUNCEMENT_WELCOME, "The Elder Scrolls Online ﻲﻓ ﻚﺑ ﺎﺒًﺣﺮﻣ", 1) end
    if SI_MARKET_BACK_TO_STORE_KEYBIND_LABEL then SafeAddString(SI_MARKET_BACK_TO_STORE_KEYBIND_LABEL, "ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ ﻰﻟﺇ ﺓﺩﻮﻌﻟﺍ", 1) end
    if SI_MARKET_BUNDLE_DETAILS_KEYBIND_TEXT then SafeAddString(SI_MARKET_BUNDLE_DETAILS_KEYBIND_TEXT, "ﺔﻣﺰﺤﻟﺍ ﻞﻴﺻﺎﻔﺗ", 1) end
    if SI_MARKET_BUNDLE_PARTS_OWNED_TEXT then SafeAddString(SI_MARKET_BUNDLE_PARTS_OWNED_TEXT, ".ﺎﻬﺋﺍﺮﺷ ﺪﻨﻋ ًﻣﺎﻛ ﺔﻣﺰﺤﻟﺍ ﺮﻌﺳ ﻊﻓﺪﺘﺳ ،ﻚﻟﺫ ﻊﻣﻭ .ﻞﻌﻔﻟﺎﺑ ﺔﻣﺰﺤﻟﺍ ﻩﺬﻫ ﻦﻣ ﺍﺀًﺰﺟ ﻚﻠﻤﺗ ﺖﻧﺃ", 2) end
    if SI_MARKET_BUNDLE_PARTS_UNLOCKED_TEXT then SafeAddString(SI_MARKET_BUNDLE_PARTS_UNLOCKED_TEXT, ".ESO Plus ﻲﻓ ﻚﻛﺍﺮﺘﺷﺍ ﺀﺎﻬﺘﻧﺍ ﺪﻌﺑ ﻰﺘﺣ ﻩﺍﻮﺘﺤﻣ ﻰﻟﺇ ﻝﻮﺻﻮﻟﺍ ﻚﻟ ﺢﻴﺘﻳ ﺎﻤﻣ ،ﺎﻴًﺋﺎﻬﻧ ﻲﻓﺎﺿﺍ ﻯﻮﺘﺤﻤﻟﺍ ﻰﻨﺘﻘﻣ ﺢﺘﻔﺘﺳ ،ﺞﺘﻨﻤﻟﺍ ﺍﺬﻫ ﺀﺍﺮﺸﺑ", 3) end
    if SI_MARKET_BUY_CROWNS then SafeAddString(SI_MARKET_BUY_CROWNS, "ﻥﺎﺠﻴﺘﻟﺍ ﺀﺍﺮﺷ", 1) end
    if SI_MARKET_CONFIRM_PURCHASE_AS_GIFT_LABEL then SafeAddString(SI_MARKET_CONFIRM_PURCHASE_AS_GIFT_LABEL, "ﺔﻳﺪﻬﻛ", 1) end
    if SI_MARKET_CONFIRM_PURCHASE_BACK_KEYBIND_LABEL then SafeAddString(SI_MARKET_CONFIRM_PURCHASE_BACK_KEYBIND_LABEL, "ﻉﻮﺟﺭ", 1) end
    if SI_MARKET_CONFIRM_PURCHASE_COST_LABEL then SafeAddString(SI_MARKET_CONFIRM_PURCHASE_COST_LABEL, ":ﺮﻌﺴﻟﺍ", 1) end
    if SI_MARKET_CONFIRM_PURCHASE_CURRENT_BALANCE_LABEL then SafeAddString(SI_MARKET_CONFIRM_PURCHASE_CURRENT_BALANCE_LABEL, ":ﻲﻟﺎﺤﻟﺍ ﺪﻴﺻﺮﻟﺍ", 1) end
    if SI_MARKET_CONFIRM_PURCHASE_ESO_PLUS_COST_LABEL then SafeAddString(SI_MARKET_CONFIRM_PURCHASE_ESO_PLUS_COST_LABEL, ":ESO Plus ﺮﻌﺳ", 1) end
    if SI_MARKET_CONFIRM_PURCHASE_FOR_ME_LABEL then SafeAddString(SI_MARKET_CONFIRM_PURCHASE_FOR_ME_LABEL, "ﻲﺴﻔﻨﻟ", 1) end
    if SI_MARKET_CONFIRM_PURCHASE_GIFT_RECIPIENT_LABEL then SafeAddString(SI_MARKET_CONFIRM_PURCHASE_GIFT_RECIPIENT_LABEL, "ﻡﺪﺨﺘﺴﻣ ﻢﺳﺍ ﻞﺧﺩﺃ", 1) end
    if SI_MARKET_CONFIRM_PURCHASE_KEYBIND_TEXT then SafeAddString(SI_MARKET_CONFIRM_PURCHASE_KEYBIND_TEXT, "ﺪﻴﻛﺄﺗ", 1) end
    if SI_MARKET_CONFIRM_PURCHASE_MAXIMUM_LABEL then SafeAddString(SI_MARKET_CONFIRM_PURCHASE_MAXIMUM_LABEL, "<<1>> :ﻰﺼﻗﺍ ﺪﺤﻟﺍ", 1) end
    if SI_MARKET_CONFIRM_PURCHASE_NORMAL_COST_LABEL then SafeAddString(SI_MARKET_CONFIRM_PURCHASE_NORMAL_COST_LABEL, ":ﻱﺩﺎﻌﻟﺍ ﺮﻌﺴﻟﺍ", 1) end
    if SI_MARKET_CONFIRM_PURCHASE_QUANTITY_LABEL then SafeAddString(SI_MARKET_CONFIRM_PURCHASE_QUANTITY_LABEL, "ﺔﻴﻤﻜﻟﺍ", 1) end
    if SI_MARKET_CONFIRM_PURCHASE_RECIPIENT_SELECTOR_HEADER then SafeAddString(SI_MARKET_CONFIRM_PURCHASE_RECIPIENT_SELECTOR_HEADER, "ﺀﺍﺮﺷ", 1) end
    if SI_MARKET_CONFIRM_PURCHASE_RESTART_KEYBIND_LABEL then SafeAddString(SI_MARKET_CONFIRM_PURCHASE_RESTART_KEYBIND_LABEL, "ﺔﻳﺪﻬﻟﺍ ﻞﻳﺪﻌﺗ", 1) end
    if SI_MARKET_CONFIRM_PURCHASE_TITLE then SafeAddString(SI_MARKET_CONFIRM_PURCHASE_TITLE, "ﺀﺍﺮﺸﻟﺍ ﺪﻴﻛﺄﺗ", 1) end
    if SI_MARKET_CRATE_LIST_HEADER then SafeAddString(SI_MARKET_CRATE_LIST_HEADER, "ﺔﻠﻤﺘﺤﻤﻟﺍ ﺕﺎﻳﻮﺘﺤﻤﻟﺍ", 1) end
    if SI_MARKET_CURRENCY_LABEL then SafeAddString(SI_MARKET_CURRENCY_LABEL, "|cffffff<<X:1>>|r :ﻥﺎﺠﻴﺘﻟﺍ ﺪﻴﺻﺭ", 3) end
    if SI_MARKET_CURRENCY_TOOLTIP then SafeAddString(SI_MARKET_CURRENCY_TOOLTIP, "<<1>> :ﻲﻟﺎﻤﺟﺍ", 1) end
    if SI_MARKET_CURRENT_PRICE_NARRATION then SafeAddString(SI_MARKET_CURRENT_PRICE_NARRATION, "ﻲﻟﺎﺤﻟﺍ", 1) end
    if SI_MARKET_DISCOUNT_LABEL then SafeAddString(SI_MARKET_DISCOUNT_LABEL, "ﻢﺼﺧ", 1) end
    if SI_MARKET_DISCOUNT_PRICE_RANGE_PERCENT_FORMAT then SafeAddString(SI_MARKET_DISCOUNT_PRICE_RANGE_PERCENT_FORMAT, "<<X:1>>–<<X:2>>% ﺔﺒﺴﻨﺑ ﻢﺼﺧ", 1) end
    if SI_MARKET_DLC_CATEGORY then SafeAddString(SI_MARKET_DLC_CATEGORY, "ﻲﻓﺎﺿﺇ ﻯﻮﺘﺤﻣ", 1) end
    if SI_MARKET_END_ALL_PREVIEWS_KEYBIND_TEXT then SafeAddString(SI_MARKET_END_ALL_PREVIEWS_KEYBIND_TEXT, "ﺕﺎﻨﻳﺎﻌﻤﻟﺍ ﻊﻴﻤﺟ ﺀﺎﻬﻧﺇ", 1) end
    if SI_MARKET_END_PREVIEW_KEYBIND_TEXT then SafeAddString(SI_MARKET_END_PREVIEW_KEYBIND_TEXT, "ﺔﻨﻳﺎﻌﻤﻟﺍ ﺀﺎﻬﻧﺇ", 1) end
    if SI_MARKET_ESO_PLUS_DEAL_LABEL then SafeAddString(SI_MARKET_ESO_PLUS_DEAL_LABEL, "ﺽﺮﻋ", 1) end
    if SI_MARKET_ESO_PLUS_DEAL_NARRATION then SafeAddString(SI_MARKET_ESO_PLUS_DEAL_NARRATION, "ESO Plus ﺽﺮﻋ", 1) end
    if SI_MARKET_ESO_PLUS_EXCLUSIVE_LABEL then SafeAddString(SI_MARKET_ESO_PLUS_EXCLUSIVE_LABEL, "ﻱﺮﺼﺣ", 1) end
    if SI_MARKET_ESO_PLUS_EXCLUSIVE_NARRATION then SafeAddString(SI_MARKET_ESO_PLUS_EXCLUSIVE_NARRATION, "ESO Plus ﻲﻛﺮﺘﺸﻤﻟ ﻱﺮﺼﺣ", 1) end
    if SI_MARKET_ESO_PLUS_MEMBERSHIP_CATEGORY then SafeAddString(SI_MARKET_ESO_PLUS_MEMBERSHIP_CATEGORY, "ﺀﺎﻀﻋﺍ", 1) end
    if SI_MARKET_ESO_PLUS_OFFERS_ALL_SUBCATEGORY then SafeAddString(SI_MARKET_ESO_PLUS_OFFERS_ALL_SUBCATEGORY, "ﺽﻭﺮﻌﻟﺍ ﻊﻴﻤﺟ", 1) end
    if SI_MARKET_ESO_PLUS_OFFERS_CATEGORY then SafeAddString(SI_MARKET_ESO_PLUS_OFFERS_CATEGORY, "ESO Plus ﺽﺮﻋ", 1) end
    if SI_MARKET_FEATURED_CATEGORY then SafeAddString(SI_MARKET_FEATURED_CATEGORY, "ﺰﻴﻤﻣ", 1) end
    if SI_MARKET_FEATURED_SUBCATEGORY then SafeAddString(SI_MARKET_FEATURED_SUBCATEGORY, "ﺔﻴﺠﻳﻭﺮﺘﻟﺍ ﺕﺎﺠﺘﻨﻤﻟﺍ", 1) end
    if SI_MARKET_FILTER_LABEL then SafeAddString(SI_MARKET_FILTER_LABEL, ":ﺔﻴﻔﺼﺗ", 1) end
    if SI_MARKET_FILTER_SHOW_ALL then SafeAddString(SI_MARKET_FILTER_SHOW_ALL, "ﻞﻜﻟﺍ", 1) end
    if SI_MARKET_FILTER_SHOW_NOT_PURCHASED then SafeAddString(SI_MARKET_FILTER_SHOW_NOT_PURCHASED, "ﺮَﺘﺸﻳُ ﻢﻟ", 1) end
    if SI_MARKET_FILTER_SHOW_PURCHASED then SafeAddString(SI_MARKET_FILTER_SHOW_PURCHASED, "ﻩﺅﺍﺮﺷ ﻢﺗ", 1) end
    if SI_MARKET_FREE_LABEL then SafeAddString(SI_MARKET_FREE_LABEL, "!ﺎﻧًﺎﺠﻣ", 1) end
    if SI_MARKET_FREE_TRIAL_TOOLTIP_DESCRIPTION then SafeAddString(SI_MARKET_FREE_TRIAL_TOOLTIP_DESCRIPTION, ".(ﺔﻳﺮﻬﺸﻟﺍ ﻥﺎﺠﻴﺘﻟﺍ ﻞﻤﺸﻳ ) |cffffff<<1>>|r ﺓﺪﻤﻟ ﺎﻧًﺎﺠﻣ ESO Plus ﺎﻳﺍﺰﻤﺑ ﻊﺘﻤﺘﺳﺍ", 2) end
    if SI_MARKET_FREE_TRIAL_TOOLTIP_HEADER then SafeAddString(SI_MARKET_FREE_TRIAL_TOOLTIP_HEADER, "ﺔﺣﺎﺘﻣ ﺔﻴﻧﺎﺠﻤﻟﺍ ESO Plus ﺔﺑﺮﺠﺗ", 1) end
    if SI_MARKET_FREE_TRIAL_TOOLTIP_START_INSTRUCTIONS then SafeAddString(SI_MARKET_FREE_TRIAL_TOOLTIP_START_INSTRUCTIONS, ".ﺔﻴﻧﺎﺠﻤﻟﺍ ﻚﺘﺑﺮﺠﺗ ﺀﺪﺒﻟ <<X:1>> ﻰﻠﻋ ﻂﻐﺿﺍ", 1) end
    if SI_MARKET_GENERAL_SUBCATEGORY then SafeAddString(SI_MARKET_GENERAL_SUBCATEGORY, "ﻡﺎﻋ", 1) end
    if SI_MARKET_GIFTING_ACCOUNT_LOCKED_TEXT then SafeAddString(SI_MARKET_GIFTING_ACCOUNT_LOCKED_TEXT, ".ﻚﺑﺎﺴﺤﻟ ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ ﻦﻣ ﺎﻳﺍﺪﻬﻟﺍ ﻝﺎﺳﺭﺇ ﺓﺰﻴﻣ ﺢﺘﻔﺗُ ﻢﻟ", 1) end
    if SI_MARKET_GIFTING_ALREADY_HAVE_GIFT_TEXT then SafeAddString(SI_MARKET_GIFTING_ALREADY_HAVE_GIFT_TEXT, ".ﺍﺩًﺪﺠﻣ ﻪﺋﺍﺮﺷ ﻞﺒﻗ ﺔﻳﺪﻬﻛ ﻪﻟﺎﺳﺭﺇ ﺐﺠﻳ .ﺎﻳﺍﺪﻬﻟﺍ ﺔﺒﻴﻘﺣ ﻲﻓ <<1>> ﻚﻳﺪﻟ", 1) end
    if SI_MARKET_GIFTING_BUNDLE_PARTS_OWNED_TEXT then SafeAddString(SI_MARKET_GIFTING_BUNDLE_PARTS_OWNED_TEXT, ".ًﻣﺎﻛ ﺎﻫﺮﻌﺳ ﻊﻓﺩ ﻊﻣ ﺔﻣﺰﺤﻟﺍ ﻩﺅﺍﺪﻫﺇ ﻚﻨﻜﻤﻳ .ﻞﻌﻔﻟﺎﺑ ﺔﻣﺰﺤﻟﺍ ﻩﺬﻫ ﻦﻣ ﺍﺀًﺰﺟ ﻚﻠﻤﻳ ﻢﻠﺘﺴﻤﻟﺍ", 1) end
    if SI_MARKET_GIFTING_GRACE_PERIOD_TEXT then SafeAddString(SI_MARKET_GIFTING_GRACE_PERIOD_TEXT, ".ﺪﻌﺑ ﻚﺑﺎﺴﺤﻟ ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ ﻦﻣ ﺎﻳﺍﺪﻬﻟﺍ ﻝﺎﺳﺭﺇ ﺓﺰﻴﻣ ﺢﺘﻔﺗُ ﻢﻟ\n\n.|cffffff<<X:1>>|r ﻝﺧ ﺓﺰﻴﻤﻟﺍ ﻞﻌَّﻔﺘُﺳ", 1) end
    if SI_MARKET_GIFTING_GRACE_PERIOD_TOOLTIP then SafeAddString(SI_MARKET_GIFTING_GRACE_PERIOD_TOOLTIP, ".|cffffffﺓﺪﻋﺎﺴﻤﻟﺍ ﺔﻤﺋﺎﻗ|r ﻲﻓ ﺔﻴﻓﺎﺿﺇ ﺕﺎﻣﻮﻠﻌﻣ ﺮﻓﻮﺘﺗ .|cffffff<<1>>|r ﻝﺧ |cffffffﺎﻳﺍﺪﻬﻟﺍ|r ﺢﺘﻔﺘُﺳ", 1) end
    if SI_MARKET_GIFTING_LOCKED_HELP_KEYBIND then SafeAddString(SI_MARKET_GIFTING_LOCKED_HELP_KEYBIND, "ﺕﺎﻣﻮﻠﻌﻤﻟﺍ ﻦﻣ ﺪﻳﺰﻣ", 1) end
    if SI_MARKET_GIFTING_LOCKED_TITLE then SafeAddString(SI_MARKET_GIFTING_LOCKED_TITLE, "ﻞﻔﻘﻣ ﺀﺍﺪﻫﺍ", 1) end
    if SI_MARKET_GIFTING_PURCHASE_REQUIREMENT_FAILED_TEXT then SafeAddString(SI_MARKET_GIFTING_PURCHASE_REQUIREMENT_FAILED_TEXT, ".ﺞﺘﻨﻤﻟﺍ ﺍﺬﻫ ﺀﺍﺪﻫ ﺔﺑﻮﻠﻄﻤﻟﺍ ﺀﺍﺮﺸﻟﺍ ﻁﻭﺮﺷ ﻲﻓﻮﺘﺴﺗ ", 1) end
    if SI_MARKET_GIFTING_RANDOM_NOTE_CONFIRMATION_LABEL then SafeAddString(SI_MARKET_GIFTING_RANDOM_NOTE_CONFIRMATION_LABEL, "؟ﺔﻴﺋﺍﻮﺸﻋ ﺔﻟﺎﺳﺭ ﻡﺍﺪﺨﺘﺳﺍ ﺪﻳﺮﺗ ﻞﻫ", 1) end
    if SI_MARKET_GIFTING_RANDOM_NOTE_LABEL then SafeAddString(SI_MARKET_GIFTING_RANDOM_NOTE_LABEL, "ﺔﻴﺋﺍﻮﺸﻋ ﺔﻟﺎﺳﺭ", 1) end
    if SI_MARKET_GIFTING_RESEND_BUNDLE_PARTS_OWNED_TEXT then SafeAddString(SI_MARKET_GIFTING_RESEND_BUNDLE_PARTS_OWNED_TEXT, ".ﺎﻬﻟﺎﺳﺭﺇ ﻚﻧﺎﻜﻣﺈﺑ ﻝﺍﺰﻳ  .ﻞﻌﻔﻟﺎﺑ ﺔﻣﺰﺤﻟﺍ ﻩﺬﻫ ﻦﻣ ﺍﺀًﺰﺟ ﻚﻠﻤﻳ ﻢﻠﺘﺴﻤﻟﺍ", 1) end
    if SI_MARKET_GIFTING_SERVER_LOCKED_TEXT then SafeAddString(SI_MARKET_GIFTING_SERVER_LOCKED_TEXT, ".ﺎﻘًﺣ ﺔﻟﻭﺎﺤﻤﻟﺍ ﻰﺟﺮﻳُ .ﺎﻴًﻟﺎﺣ ﺔﻠﻔﻘﻣ ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ ﺎﻳﺍﺪﻫ", 1) end
    if SI_MARKET_GIFTING_SUCCESS_TEXT then SafeAddString(SI_MARKET_GIFTING_SUCCESS_TEXT, ".<<2>> ﻰﻟﺇ ﻪﺋﺍﺪﻫ ﺡﺎﺠﻨﺑ <<t:1>> ﺀﺍﺮﺷ ﻢﺗ", 1) end
    if SI_MARKET_GIFTING_SUCCESS_TEXT_WITH_QUANTITY then SafeAddString(SI_MARKET_GIFTING_SUCCESS_TEXT_WITH_QUANTITY, "<<3>> :ﻢﻠﺘﺴﻤﻠﻟ ﺡﺎﺠﻨﺑ <<t:1>><<2[// ($d)]>> ﺔﻳﺪﻬﻟﺍ ﺀﺍﺮﺷ ﻢﺗ", 1) end
    if SI_MARKET_GIFT_BUNDLE_KEYBIND_TEXT then SafeAddString(SI_MARKET_GIFT_BUNDLE_KEYBIND_TEXT, "ﺔﻣﺰﺤﻟﺍ ﺀﺍﺪﻫﺇ", 1) end
    if SI_MARKET_GIFT_KEYBIND_TEXT then SafeAddString(SI_MARKET_GIFT_KEYBIND_TEXT, "ﺔﻳﺪﻫ", 1) end
    if SI_MARKET_HOUSE_INFO_ESO_PLUS_TEXT then SafeAddString(SI_MARKET_HOUSE_INFO_ESO_PLUS_TEXT, "ESO Plus ﻞﻀﻔﺑ ﺪﺤﻟﺍ ﻒﻋﺎﻀﺗ*", 1) end
    if SI_MARKET_INSUFFICIENT_FUNDS_CONFIRM_BUTTON_TEXT then SafeAddString(SI_MARKET_INSUFFICIENT_FUNDS_CONFIRM_BUTTON_TEXT, "ﻥﺎﺠﻴﺘﻟﺍ ﺀﺍﺮﺷ", 1) end
    if SI_MARKET_INSUFFICIENT_FUNDS_TEXT then SafeAddString(SI_MARKET_INSUFFICIENT_FUNDS_TEXT, ".ﺀﺍﺮﺸﻟﺍ ﻡﺎﻤﺗ ﻥﺎﺠﻴﺘﻟﺍ<<1>> ﻦﻣ ﻲﻔﻜﻳ ﺎﻣ ﻚﻠﻤﺗ \n\n.<<2>> ﺮﺒﻋ ﻥﺎﺠﻴﺘﻟﺍ<<1>> ﻦﻣ ﺪﻳﺰﻣ ﺀﺍﺮﺷ ﻚﻨﻜﻤﻳ", 1) end
    if SI_MARKET_INSUFFICIENT_FUNDS_TEXT_EPIC then SafeAddString(SI_MARKET_INSUFFICIENT_FUNDS_TEXT_EPIC, ".Epic Games ﺔﻬﺟﺍﻭ ﻲﻓ ﺎﺤًﻔﺼﺘﻣ ﺭﺎﻴﺨﻟﺍ ﺍﺬﻫ ﺢﺘﻔﻴﺳ .Epic Games ﺮﺠﺘﻣ ﻦﻣ ﻥﺎﺠﻴﺘﻟﺍ<<X:1>> ﻦﻣ ﺪﻳﺰﻤﻟﺍ ﺀﺍﺮﺷ ﻚﻨﻜﻤﻳ .ﺀﺍﺮﺸﻟﺍ ﻡﺎﻤﺗ ﻥﺎﺠﻴﺘﻟﺍ<<X:1>> ﻦﻣ ﻲﻔﻜﻳ ﺎﻣ ﻚﻠﻤﺗ ", 2) end
    if SI_MARKET_INSUFFICIENT_FUNDS_TEXT_STEAM then SafeAddString(SI_MARKET_INSUFFICIENT_FUNDS_TEXT_STEAM, ".®Steam ﺔﻬﺟﺍﻭ ﻲﻓ ﺎﺤًﻔﺼﺘﻣ ﺭﺎﻴﺨﻟﺍ ﺍﺬﻫ ﺢﺘﻔﻴﺳ .®Steam ﺮﺠﺘﻣ ﻦﻣ ﻥﺎﺠﻴﺘﻟﺍ<<X:1>> ﻦﻣ ﺪﻳﺰﻤﻟﺍ ﺀﺍﺮﺷ ﻚﻨﻜﻤﻳ .ﺀﺍﺮﺸﻟﺍ ﻡﺎﻤﺗ ﻥﺎﺠﻴﺘﻟﺍ<<X:1>> ﻦﻣ ﻲﻔﻜﻳ ﺎﻣ ﻚﻠﻤﺗ ", 2) end
    if SI_MARKET_INSUFFICIENT_FUNDS_TEXT_WEB then SafeAddString(SI_MARKET_INSUFFICIENT_FUNDS_TEXT_WEB, ".ﺔﺒﻌﻠﻟﺍ ﺝﺭﺎﺧ ﺐﻳﻮﻟﺍ ﺢﻔﺼﺘﻣ ﺍﺬﻫ ﺢﺘﻔﻴﺳ .|c76BCC3<<X:2>>|r ﺮﺒﻋ ﻥﺎﺠﻴﺘﻟﺍ<<1>> ﻦﻣ ﺪﻳﺰﻤﻟﺍ ﺀﺍﺮﺷ ﻚﻨﻜﻤﻳ .ﺀﺍﺮﺸﻟﺍ ﻡﺎﻤﺗ ﻥﺎﺠﻴﺘﻟﺍ<<1>> ﻦﻣ ﻲﻔﻜﻳ ﺎﻣ ﻚﻠﻤﺗ ", 1) end
    if SI_MARKET_INVENTORY_FULL_TEXT then SafeAddString(SI_MARKET_INVENTORY_FULL_TEXT, ".ﺀﺍﺮﺸﻟﺍ ﺍﺬﻫ ﻡﺎﻤﺗ ﺔﺒﻴﻘﺤﻟﺍ ﻲﻓ <<1[/ﺔﻧﺎﺧ/ﺕﺎﻧﺎﺧ]>> <<1>> ﻰﻟﺇ ﺝﺎﺘﺤﺗ", 1) end
    if SI_MARKET_JOIN_ESO_PLUS_CONFIRM_BUTTON_TEXT then SafeAddString(SI_MARKET_JOIN_ESO_PLUS_CONFIRM_BUTTON_TEXT, "!ﻡﻮﻴﻟﺍ ﻙﺮﺘﺷﺍ", 1) end
    if SI_MARKET_LIMITED_TIME_OFFER_CATEGORY then SafeAddString(SI_MARKET_LIMITED_TIME_OFFER_CATEGORY, "ﺓﺩﻭﺪﺤﻣ ﺓﺮﺘﻔﻟ ﺽﻭﺮﻋ", 1) end
    if SI_MARKET_LOCKED_TEXT then SafeAddString(SI_MARKET_LOCKED_TEXT, "!ﺎﻘًﺣ ﺔﻟﻭﺎﺤﻤﻟﺍ ﻰﺟﺮﻳُ .ﺎﻴًﻟﺎﺣ ﺡﺎﺘﻣ ﺮﻴﻏ ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ", 1) end
    if SI_MARKET_LOG_OUT_TO_CHARACTER_SELECT_KEYBIND_LABEL then SafeAddString(SI_MARKET_LOG_OUT_TO_CHARACTER_SELECT_KEYBIND_LABEL, "ﺕﺎﻴﺼﺨﺸﻟﺍ ﺔﺷﺎﺷ ﻰﻟﺇ ﺓﺩﻮﻌﻟﺍ", 1) end
    if SI_MARKET_NEW_LABEL then SafeAddString(SI_MARKET_NEW_LABEL, "ﺪﻳﺪﺟ", 1) end
    if SI_MARKET_OPEN_CROWN_CRATES_KEYBIND_LABEL then SafeAddString(SI_MARKET_OPEN_CROWN_CRATES_KEYBIND_LABEL, "ﻥﺎﺠﻴﺘﻟﺍ ﻖﻳﺩﺎﻨﺻ ﺢﺘﻓ", 1) end
    if SI_MARKET_OPEN_GIFT_INVENTORY_KEYBIND_LABEL then SafeAddString(SI_MARKET_OPEN_GIFT_INVENTORY_KEYBIND_LABEL, "ﺎﻳﺍﺪﻬﻟﺍ ﺔﺒﻴﻘﺣ ﺢﺘﻓ", 1) end
    if SI_MARKET_ORIGINAL_PRICE_NARRATION then SafeAddString(SI_MARKET_ORIGINAL_PRICE_NARRATION, "ﻲﻠﺻﺍ", 1) end
    if SI_MARKET_PLACE_IN_HOUSE_KEYBIND_LABEL then SafeAddString(SI_MARKET_PLACE_IN_HOUSE_KEYBIND_LABEL, "ﻊﺿﻭ", 1) end
    if SI_MARKET_PREVIEW_ERROR_CANNOT_JUMP_FROM_LOCATION then SafeAddString(SI_MARKET_PREVIEW_ERROR_CANNOT_JUMP_FROM_LOCATION, ".ﻊﻗﻮﻤﻟﺍ ﺍﺬﻫ ﻦﻣ ﻝﺰﻨﻣ ﺔﻨﻳﺎﻌﻣ ﻚﻨﻜﻤﻳ ", 1) end
    if SI_MARKET_PREVIEW_HOUSE_TEMPLATE_KEYBIND_LABEL then SafeAddString(SI_MARKET_PREVIEW_HOUSE_TEMPLATE_KEYBIND_LABEL, "ﻝﺰﻨﻤﻟﺍ ﺔﻨﻳﺎﻌﻣ", 1) end
    if SI_MARKET_PREVIEW_HOUSE_TEXT then SafeAddString(SI_MARKET_PREVIEW_HOUSE_TEXT, ".ﺀﺍﺮﺸﻟﺍ ﺕﺍﺭﺎﻴﺧ ﺽﺮﻌﻟ <<2>> ﻰﻠﻋ ﻂﻐﺿﺍ ،ﻝﺰﻨﻤﻟﺍ ﻰﻟﺇ ﻚﻟﻮﺻﻭ ﺪﻨﻋ .<<1>> ﻰﻟﺇ ﻊﻳﺮﺴﻟﺍ ﺮﻔﺴﻟﺍ ﻚﺷﻭ ﻰﻠﻋ ﺖﻧﺃ", 2) end
    if SI_MARKET_PREVIEW_HOUSE_TITLE then SafeAddString(SI_MARKET_PREVIEW_HOUSE_TITLE, "ﻝﺰﻨﻤﻟﺍ ﺔﻨﻳﺎﻌﻣ", 1) end
    if SI_MARKET_PREVIEW_KEYBIND_TEXT then SafeAddString(SI_MARKET_PREVIEW_KEYBIND_TEXT, "ﺔﻨﻳﺎﻌﻣ", 1) end
    if SI_MARKET_PRODUCT_HOUSING_HOUSE_SUPPORTS_WEATHER_CONTROL_LABEL then SafeAddString(SI_MARKET_PRODUCT_HOUSING_HOUSE_SUPPORTS_WEATHER_CONTROL_LABEL, "ﺲﻘﻄﻟﺎﺑ ﻢﻜﺤﺘﻟﺍ ﻢﻋﺪﻳ", 1) end
    if SI_MARKET_PRODUCT_HOUSING_HOUSE_TYPE_LABEL then SafeAddString(SI_MARKET_PRODUCT_HOUSING_HOUSE_TYPE_LABEL, "ﻝﺰﻨﻤﻟﺍ ﻉﻮﻧ", 1) end
    if SI_MARKET_PRODUCT_HOUSING_LOCATION_LABEL then SafeAddString(SI_MARKET_PRODUCT_HOUSING_LOCATION_LABEL, "ﻊﻗﻮﻤﻟﺍ", 1) end
    if SI_MARKET_PRODUCT_TOOLTIP_BUNDLE then SafeAddString(SI_MARKET_PRODUCT_TOOLTIP_BUNDLE, "ﺔﻣﺰﺣ", 1) end
    if SI_MARKET_PRODUCT_TOOLTIP_DLC then SafeAddString(SI_MARKET_PRODUCT_TOOLTIP_DLC, "ﻲﻓﺎﺿﺇ ﻯﻮﺘﺤﻣ", 1) end
    if SI_MARKET_PRODUCT_TOOLTIP_ESO_PLUS_DEAL_DESCRIPTION then SafeAddString(SI_MARKET_PRODUCT_TOOLTIP_ESO_PLUS_DEAL_DESCRIPTION, "ESO Plus ﻲﻛﺮﺘﺸﻤﻟ ﺽﺮﻋ", 1) end
    if SI_MARKET_PRODUCT_TOOLTIP_ESO_PLUS_EXCLUSIVE_DESCRIPTION then SafeAddString(SI_MARKET_PRODUCT_TOOLTIP_ESO_PLUS_EXCLUSIVE_DESCRIPTION, "ESO Plus ﻲﻛﺮﺘﺸﻤﻟ ﻱﺮﺼﺣ ﺽﺮﻋ", 1) end
    if SI_MARKET_PRODUCT_TOOLTIP_PURCHASABLE_ON_ALT_CHARACTER_DESCRIPTION then SafeAddString(SI_MARKET_PRODUCT_TOOLTIP_PURCHASABLE_ON_ALT_CHARACTER_DESCRIPTION, ".ﺪﻌﺑ ﻲﻨﻌﻤﻟﺍ ﺯﺎﺠﻧﺍ ﻰﻠﻋ ﻞﺼﺤﺗ ﻢﻟ ﺔﻴﺼﺨﺸﺑ ﻝﻮﺧﺪﻟﺍ ﻞﺠّﺳ ،ﺀﺍﺮﺸﻠﻟ", 2) end
    if SI_MARKET_PRODUCT_TOOLTIP_REQUIRED_ACHIEVEMENT_HEADER then SafeAddString(SI_MARKET_PRODUCT_TOOLTIP_REQUIRED_ACHIEVEMENT_HEADER, ":ﺀﺍﺮﺸﻠﻟ ﺏﻮﻠﻄﻤﻟﺍ ﺯﺎﺠﻧﺍ", 1) end
    if SI_MARKET_PRODUCT_TOOLTIP_REQUIRED_COLLECTIBLES_HEADER then SafeAddString(SI_MARKET_PRODUCT_TOOLTIP_REQUIRED_COLLECTIBLES_HEADER, ":ﺎﻫﺅﺍﺮﺷ ﺏﻮﻠﻄﻤﻟﺍ ﺕﺎﻴﻨﺘﻘﻤﻟﺍ", 1) end
    if SI_MARKET_PRODUCT_TOOLTIP_SKILL_LINE_PURCHASABLE_ON_ALT_CHARACTER_DESCRIPTION then SafeAddString(SI_MARKET_PRODUCT_TOOLTIP_SKILL_LINE_PURCHASABLE_ON_ALT_CHARACTER_DESCRIPTION, ".ﺪﻌﺑ ﻲﻨﻌﻤﻟﺍ ﺕﺍﺭﺎﻬﻤﻟﺍ ﻂﺧ ﺢﺘﻔﺗ ﻢﻟ ﺔﻴﺼﺨﺸﺑ ﻝﻮﺧﺪﻟﺍ ﻞﺠّﺳ ،ﺀﺍﺮﺸﻠﻟ", 1) end
    if SI_MARKET_PRODUCT_TOOLTIP_SKYSHARD_PURCHASABLE_ON_ALT_CHARACTER_DESCRIPTION then SafeAddString(SI_MARKET_PRODUCT_TOOLTIP_SKYSHARD_PURCHASABLE_ON_ALT_CHARACTER_DESCRIPTION, ".ﺪﻌﺑ ﺔﻴﻨﻌﻤﻟﺍ ﺔﻳﻭﺎﻤﺴﻟﺍ ﺎﻳﺎﻈﺸﻟﺍ ﻊﻤﺠﺗ ﻢﻟ ﺔﻴﺼﺨﺸﺑ ﻝﻮﺧﺪﻟﺍ ﻞﺠّﺳ ،ﺀﺍﺮﺸﻠﻟ", 2) end
    if SI_MARKET_PRODUCT_TOOLTIP_UNLOCK then SafeAddString(SI_MARKET_PRODUCT_TOOLTIP_UNLOCK, "ﺢﺘﻓُ", 1) end
    if SI_MARKET_PRODUCT_TOTAL_LABEL then SafeAddString(SI_MARKET_PRODUCT_TOTAL_LABEL, "ﺮﺻﺎﻨﻋ", 1) end
    if SI_MARKET_PURCHASED_LABEL then SafeAddString(SI_MARKET_PURCHASED_LABEL, "ﻩﺅﺍﺮﺷ ﻢﺗ", 1) end
    if SI_MARKET_PURCHASE_ALREADY_HAVE_GIFT_TEXT then SafeAddString(SI_MARKET_PURCHASE_ALREADY_HAVE_GIFT_TEXT, ".ﺍﺩًﺪﺠﻣ ﻪﺋﺍﺮﺷ ﻞﺒﻗ ﻪﻤﻠﺘﺳﺍ .ﺎﻳﺍﺪﻬﻟﺍ ﺔﺒﻴﻘﺣ ﻲﻓ <<1>> ﻚﻳﺪﻟ", 1) end
    if SI_MARKET_PURCHASE_BUNDLE_KEYBIND_TEXT then SafeAddString(SI_MARKET_PURCHASE_BUNDLE_KEYBIND_TEXT, "ﺔﻣﺰﺤﻟﺍ ﺀﺍﺮﺷ", 1) end
    if SI_MARKET_PURCHASE_ERROR_CONTINUE then SafeAddString(SI_MARKET_PURCHASE_ERROR_CONTINUE, "ﺔﻌﺑﺎﺘﻣ", 1) end
    if SI_MARKET_PURCHASE_ERROR_WITH_CONTINUE_TEXT_FORMATTER then SafeAddString(SI_MARKET_PURCHASE_ERROR_WITH_CONTINUE_TEXT_FORMATTER, "<<1>>\n\n؟ﺔﻌﺑﺎﺘﻤﻟﺍ ﺪﻳﺮﺗ ﻞﻫ", 1) end
    if SI_MARKET_PURCHASE_FREE_TRIAL_SUCCESS_TEXT then SafeAddString(SI_MARKET_PURCHASE_FREE_TRIAL_SUCCESS_TEXT, ".ﺡﺎﺠﻨﺑ |cffffffﺔﻴﻧﺎﺠﻤﻟﺍ ESO Plus ﺔﺑﺮﺠﺗ|r ﺕﺃﺪﺑ", 1) end
    if SI_MARKET_PURCHASE_FREE_TRIAL_SUCCESS_TITLE_TEXT then SafeAddString(SI_MARKET_PURCHASE_FREE_TRIAL_SUCCESS_TITLE_TEXT, "ﺔﻴﻧﺎﺠﻤﻟﺍ ESO Plus ﺔﺑﺮﺠﺗ", 1) end
    if SI_MARKET_PURCHASE_FREE_TRIAL_TEXT then SafeAddString(SI_MARKET_PURCHASE_FREE_TRIAL_TEXT, ".|cffffff<<1>>|r ﺓﺪﻤﻟ ﺔﺒﻌﻠﻟﺍ ﻞﺧﺍﺩ ESO Plus ﺎﻳﺍﺰﻣ ﻊﻴﻤﺠﺑ ﻊﺘﻤﺘﺘﺳ\n\n.ﺔﻳﺮﺼﺤﻟﺍ ﻪﺗﺎﺠﺘﻨﻣﻭ ESO Plus ﺽﻭﺮﻋ ﻭﺃ ﺔﻳﺮﻬﺸﻟﺍ |cffffffﻥﺎﺠﻴﺘﻟﺍ|r<<X:2>> ﺕﺎﺼﺼﺨﻣ |cffffffﺔﻴﻧﺎﺠﻤﻟﺍ ESO Plus ﺔﺑﺮﺠﺗ|r ﻞﻤﺸﺗ  :ﺮﻴﻛﺬﺗ", 4) end
    if SI_MARKET_PURCHASE_FREE_TRIAL_TITLE then SafeAddString(SI_MARKET_PURCHASE_FREE_TRIAL_TITLE, "ﺔﻴﻧﺎﺠﻤﻟﺍ ESO Plus ﺔﺑﺮﺠﺗ", 1) end
    if SI_MARKET_PURCHASE_KEYBIND_TEXT then SafeAddString(SI_MARKET_PURCHASE_KEYBIND_TEXT, "ﺀﺍﺮﺷ", 1) end
    if SI_MARKET_PURCHASE_REQUIREMENT_INELIGIBLE_LABEL then SafeAddString(SI_MARKET_PURCHASE_REQUIREMENT_INELIGIBLE_LABEL, "ﺓﺎﻓﻮﺘﺴﻣ ﺮﻴﻏ ﺕﺎﺒﻠﻄﺘﻤﻟﺍ", 3) end
    if SI_MARKET_PURCHASE_SUCCESS_ESO_PLUS_SAVINGS_TEXT then SafeAddString(SI_MARKET_PURCHASE_SUCCESS_ESO_PLUS_SAVINGS_TEXT, "<<1>> ﻩﺭﺪﻗ ﺎﻤًﺼﺧ ESO Plus ﻙﺍﺮﺘﺷﺍ ﻚﻟ ﺮﻓّﻭ", 1) end
    if SI_MARKET_PURCHASE_SUCCESS_TEXT then SafeAddString(SI_MARKET_PURCHASE_SUCCESS_TEXT, "ﺡﺎﺠﻨﺑ <<t:1>> ﺀﺍﺮﺷ ﻢﺗ", 3) end
    if SI_MARKET_PURCHASE_SUCCESS_TEXT_WITH_COLLECTIBLE then SafeAddString(SI_MARKET_PURCHASE_SUCCESS_TEXT_WITH_COLLECTIBLE, "ﺡﺎﺠﻨﺑ <<t:1>> ﺀﺍﺮﺷ ﻢﺗ\n\n.ﺕﺎﻴﻨﺘﻘﻤﻟﺍ ﺔﺷﺎﺷ ﻲﻓ ﻚﺗﺎﻳﺮﺘﺸﻣ ﺽﺮﻋ ﻚﻨﻜﻤﻳ", 3) end
    if SI_MARKET_PURCHASE_SUCCESS_TEXT_WITH_QUANTITY then SafeAddString(SI_MARKET_PURCHASE_SUCCESS_TEXT_WITH_QUANTITY, "ﺡﺎﺠﻨﺑ <<t:1>><<2[// ($d)]>> ﺀﺍﺮﺷ ﻢﺗ", 3) end
    if SI_MARKET_PURCHASE_SUCCESS_TEXT_WITH_TOKEN_USAGE then SafeAddString(SI_MARKET_PURCHASE_SUCCESS_TEXT_WITH_TOKEN_USAGE, "ﺡﺎﺠﻨﺑ <<t:1>> ﺀﺍﺮﺷ ﻢﺗ\n\n.ﺔﻴﺼﺨﺸﻟﺍ ﺭﺎﻴﺘﺧﺍ ﺔﺷﺎﺷ ﻲﻓ ﺇ ﺯﻮﻣﺮﻟﺍ ﻡﺍﺪﺨﺘﺳﺍ ﻦﻜﻤﻳ ", 2) end
    if SI_MARKET_PURCHASING_TEXT then SafeAddString(SI_MARKET_PURCHASING_TEXT, "<<t:1>> ﺀﺍﺮﺷ ﺭٍﺎﺟ", 4) end
    if SI_MARKET_PURCHASING_TEXT_WITH_QUANTITY then SafeAddString(SI_MARKET_PURCHASING_TEXT_WITH_QUANTITY, "<<t:1>><<2[// ($d)]>> ﺀﺍﺮﺷ ﺭٍﺎﺟ", 3) end
    if SI_MARKET_PURCHASING_TITLE then SafeAddString(SI_MARKET_PURCHASING_TITLE, "ﺀﺍﺮﺷ", 1) end
    if SI_MARKET_SEARCH_EDIT_DEFAULT then SafeAddString(SI_MARKET_SEARCH_EDIT_DEFAULT, "ﺚﺤﺑ", 1) end
    if SI_MARKET_SEARCH_FILTER_BY_LABEL then SafeAddString(SI_MARKET_SEARCH_FILTER_BY_LABEL, ":ﺐﺴﺣ ﺔﻴﻔﺼﺗ", 1) end
    if SI_MARKET_SEARCH_NO_MATCHES then SafeAddString(SI_MARKET_SEARCH_NO_MATCHES, "ﺔﻘﺑﺎﻄﻣ ﺞﺋﺎﺘﻧ ﺪﺟﻮﺗ ", 1) end
    if SI_MARKET_SELECT_HOUSE_TEMPLATE_LABEL then SafeAddString(SI_MARKET_SELECT_HOUSE_TEMPLATE_LABEL, "ﻝﺰﻨﻤﻟﺍ ﺝﺫﻮﻤﻧ ﺭﺎﻴﺘﺧﺍ", 1) end
    if SI_MARKET_SELECT_HOUSE_TEMPLATE_REVIEW_PURCHASE then SafeAddString(SI_MARKET_SELECT_HOUSE_TEMPLATE_REVIEW_PURCHASE, "ﺕﺎﻳﺮﺘﺸﻤﻟﺍ ﺽﺮﻋ", 1) end
    if SI_MARKET_SELECT_HOUSE_TEMPLATE_TITLE then SafeAddString(SI_MARKET_SELECT_HOUSE_TEMPLATE_TITLE, "ﻝﺰﻨﻤﻟﺍ ﺝﺫﻮﻤﻧ ﺭﺎﻴﺘﺧﺍ", 1) end
    if SI_MARKET_START_TRIAL_KEYBIND_TEXT then SafeAddString(SI_MARKET_START_TRIAL_KEYBIND_TEXT, "ﺔﻴﻧﺎﺠﻤﻟﺍ ﺔﺑﺮﺠﺘﻟﺍ ﺀﺪﺑ", 1) end
    if SI_MARKET_SUBSCRIPTION_PAGE_BENEFITS_TITLE then SafeAddString(SI_MARKET_SUBSCRIPTION_PAGE_BENEFITS_TITLE, "ESO Plus ﺎﻳﺍﺰﻣ", 1) end
    if SI_MARKET_SUBSCRIPTION_PAGE_BUY_SUBSCRIPTION then SafeAddString(SI_MARKET_SUBSCRIPTION_PAGE_BUY_SUBSCRIPTION, "!ﻙﺮﺘﺷﺍ", 1) end
    if SI_MARKET_SUBSCRIPTION_PAGE_FREE_TRIAL then SafeAddString(SI_MARKET_SUBSCRIPTION_PAGE_FREE_TRIAL, "!ﺔﻴﻧﺎﺠﻣ ﺔﺑﺮﺠﺗ", 1) end
    if SI_MARKET_SUBSCRIPTION_PAGE_SUBSCRIPTION_STATUS_ACTIVE then SafeAddString(SI_MARKET_SUBSCRIPTION_PAGE_SUBSCRIPTION_STATUS_ACTIVE, "ﻂﺸﻧ", 1) end
    if SI_MARKET_SUBSCRIPTION_PAGE_SUBSCRIPTION_STATUS_FREE_TRIAL then SafeAddString(SI_MARKET_SUBSCRIPTION_PAGE_SUBSCRIPTION_STATUS_FREE_TRIAL, "|cffffff(<<X:1>>)|r ﺔﻴﻧﺎﺠﻣ ﺔﺑﺮﺠﺗ", 1) end
    if SI_MARKET_SUBSCRIPTION_PAGE_SUBSCRIPTION_STATUS_LABEL_GAMEPAD then SafeAddString(SI_MARKET_SUBSCRIPTION_PAGE_SUBSCRIPTION_STATUS_LABEL_GAMEPAD, "ﻙﺍﺮﺘﺷﺍ", 1) end
    if SI_MARKET_SUBSCRIPTION_PAGE_SUBSCRIPTION_STATUS_LABEL_KEYBOARD then SafeAddString(SI_MARKET_SUBSCRIPTION_PAGE_SUBSCRIPTION_STATUS_LABEL_KEYBOARD, ":ﻙﺍﺮﺘﺷﺍ", 1) end
    if SI_MARKET_SUBSCRIPTION_PAGE_SUBSCRIPTION_STATUS_NOT_ACTIVE then SafeAddString(SI_MARKET_SUBSCRIPTION_PAGE_SUBSCRIPTION_STATUS_NOT_ACTIVE, "ﻂﺸﻧ ﺮﻴﻏ", 1) end
    if SI_MARKET_TILE_CALLOUT_NEW then SafeAddString(SI_MARKET_TILE_CALLOUT_NEW, "ﺪﻳﺪﺟ", 2) end
    if SI_MARKET_TILE_CALLOUT_SALE then SafeAddString(SI_MARKET_TILE_CALLOUT_SALE, "ﻊﻴﺒﻠﻟ", 2) end
    if SI_MARKET_TRAVEL_TO_HOUSE_KEYBIND_LABEL then SafeAddString(SI_MARKET_TRAVEL_TO_HOUSE_KEYBIND_LABEL, "ﻝﺰﻨﻤﻟﺍ ﻰﻟﺇ ﺮﻔﺴﻟﺍ", 1) end
    if SI_MARKET_UPDATING_TEXT then SafeAddString(SI_MARKET_UPDATING_TEXT, ".ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ ﺚﻳﺪﺤﺗ ﺭٍﺎﺟ .ﺭﺎﻈﺘﻧﺍ ﻰﺟﺮﻳُ", 1) end
    if SI_MARKET_VIEW_IN_COLLECTIONS_KEYBIND_LABEL then SafeAddString(SI_MARKET_VIEW_IN_COLLECTIONS_KEYBIND_LABEL, "ﺕﺎﻴﻨﺘﻘﻤﻟﺍ ﻲﻓ ﺽﺮﻋ", 1) end
    if SI_NAMEPLATEDISPLAYCHOICE4 then SafeAddString(SI_NAMEPLATEDISPLAYCHOICE4, "ﻞﻜﻟﺍ", 1) end
    if SI_NEW then SafeAddString(SI_NEW, "ﺪﻳﺪﺟ", 1) end
    if SI_NOTIFICATIONS_EXPIRING_MARKET_CURRENCY_ACCEPT then SafeAddString(SI_NOTIFICATIONS_EXPIRING_MARKET_CURRENCY_ACCEPT, "ﺭﺎﻬﻇﺇ", 1) end
    if SI_NOTIFICATIONS_EXPIRING_MARKET_CURRENCY_DECLINE then SafeAddString(SI_NOTIFICATIONS_EXPIRING_MARKET_CURRENCY_DECLINE, "ﻞﻫﺎﺠﺗ", 1) end
    if SI_NOTIFICATIONS_EXPIRING_MARKET_CURRENCY_MESSAGE then SafeAddString(SI_NOTIFICATIONS_EXPIRING_MARKET_CURRENCY_MESSAGE, ".ﺎﺒًﻳﺮﻗ ﺎﻬﺘﻴﺣﺻ ﻲﻬﺘﻨﺘﺳ ﻥﺎﺠﻴﺗ ﻚﻳﺪﻟ", 1) end
    if SI_NOTIFICATIONS_MARKET_PRODUCT_UNLOCKED_BY_ACHIEVEMENT_MESSAGE then SafeAddString(SI_NOTIFICATIONS_MARKET_PRODUCT_UNLOCKED_BY_ACHIEVEMENT_MESSAGE, "!ﻯﺮﺧﺍ ﻚﺗﺎﻴﺼﺨﺸﻟ ﺀﺍﺮﺸﻠﻟ ﺎﺣًﺎﺘﻣ <<1>> ﺢﺒﺻﺃ", 2) end
    if SI_NOTIFICATIONS_MARKET_PRODUCT_UNLOCKED_BY_COLLECTIBLES_MESSAGE then SafeAddString(SI_NOTIFICATIONS_MARKET_PRODUCT_UNLOCKED_BY_COLLECTIBLES_MESSAGE, "!ﺀﺍﺮﺸﻠﻟ ﺎﺣًﺎﺘﻣ <<1>> ﺢﺒﺻﺃ", 1) end
    if SI_NOTIFICATIONS_MULTIPLE_MARKET_PRODUCTS_UNLOCKED_BY_ACHIEVEMENT_MESSAGE then SafeAddString(SI_NOTIFICATIONS_MULTIPLE_MARKET_PRODUCTS_UNLOCKED_BY_ACHIEVEMENT_MESSAGE, "!ﻯﺮﺧﺍ ﻚﺗﺎﻴﺼﺨﺸﻟ ﺀﺍﺮﺸﻠﻟ ﺔﺣﺎﺘﻣ ﺕﺎﺠﺘﻨﻣ ﺓﺪﻋ ﺖﺤﺒﺻﺃ", 1) end
    if SI_NOTIFICATIONS_MULTIPLE_MARKET_PRODUCTS_UNLOCKED_BY_COLLECTIBLES_MESSAGE then SafeAddString(SI_NOTIFICATIONS_MULTIPLE_MARKET_PRODUCTS_UNLOCKED_BY_COLLECTIBLES_MESSAGE, "!ﺀﺍﺮﺸﻠﻟ ﺔﺣﺎﺘﻣ ﺕﺎﺠﺘﻨﻣ ﺓﺪﻋ ﺖﺤﺒﺻﺃ", 1) end
    if SI_NOTIFICATIONS_OPEN_CROWN_STORE then SafeAddString(SI_NOTIFICATIONS_OPEN_CROWN_STORE, "ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ ﺢﺘﻓ", 1) end
    if SI_OPEN_STORE_TO_BUY_CROWNS_TITLE then SafeAddString(SI_OPEN_STORE_TO_BUY_CROWNS_TITLE, "ﻥﺎﺠﻴﺘﻟﺍ ﺀﺍﺮﺷ", 1) end
    if SI_OUTFITSLOT13 then SafeAddString(SI_OUTFITSLOT13, "ﻱﺯ", 1) end
    if SI_OUTFIT_COLLECTIBLE_SHOW_IN_MARKET then SafeAddString(SI_OUTFIT_COLLECTIBLE_SHOW_IN_MARKET, "ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ ﺢﺘﻓ", 1) end
    if SI_OUTFIT_NEW_FILTER then SafeAddString(SI_OUTFIT_NEW_FILTER, "ﺪﻳﺪﺟ", 1) end
    if SI_OUTFIT_STYLES_BOOK_END_ALL_PREVIEWS_KEYBIND then SafeAddString(SI_OUTFIT_STYLES_BOOK_END_ALL_PREVIEWS_KEYBIND, "ﺕﺎﻨﻳﺎﻌﻤﻟﺍ ﻊﻴﻤﺟ ﺀﺎﻬﻧﺇ", 1) end
    if SI_OUTFIT_STYLES_BOOK_END_PREVIEW_KEYBIND then SafeAddString(SI_OUTFIT_STYLES_BOOK_END_PREVIEW_KEYBIND, "ﺔﻨﻳﺎﻌﻤﻟﺍ ﺀﺎﻬﻧﺇ", 1) end
    if SI_OUTFIT_STYLES_BOOK_PREVIEW_KEYBIND then SafeAddString(SI_OUTFIT_STYLES_BOOK_PREVIEW_KEYBIND, "ﺔﻨﻳﺎﻌﻣ", 1) end
    if SI_PAGE_NAVIGATION_NEXT_PAGE_ACTION then SafeAddString(SI_PAGE_NAVIGATION_NEXT_PAGE_ACTION, "ﻲﻟﺎﺘﻟﺍ", 1) end
    if SI_PAGE_NAVIGATION_PREVIOUS_PAGE_ACTION then SafeAddString(SI_PAGE_NAVIGATION_PREVIOUS_PAGE_ACTION, "ﻖﺑﺎﺴﻟﺍ", 1) end
    if SI_PREVIEW_CLEAR_INVENTORY_PREVIEW then SafeAddString(SI_PREVIEW_CLEAR_INVENTORY_PREVIEW, "ﺔﻨﻳﺎﻌﻤﻟﺍ ﺀﺎﻬﻧﺇ", 1) end
    if SI_PREVIEW_MONSTER_VO_LINE_SAMPLE then SafeAddString(SI_PREVIEW_MONSTER_VO_LINE_SAMPLE, "<<1>> ﺔﻨﻴﻋ ﺭﺎﺴﻣ", 1) end
    if SI_PREVIEW_UNAVAILABLE_ERROR then SafeAddString(SI_PREVIEW_UNAVAILABLE_ERROR, ".ﻥﺍ ﺔﻨﻳﺎﻌﻤﻟﺍ ﻡﺍﺪﺨﺘﺳﺍ ﻚﻨﻜﻤﻳ ", 1) end
    if SI_PROMOTIONAL_EVENT_PERSONAL_CAMPAIGN_CONFIRM_LEAVE_INTRO_DIALOG_BACK_KEYBIND then SafeAddString(SI_PROMOTIONAL_EVENT_PERSONAL_CAMPAIGN_CONFIRM_LEAVE_INTRO_DIALOG_BACK_KEYBIND, "ﻉﻮﺟﺭ", 1) end
    if SI_PROMPT_TITLE_CONFIRM_PURCHASE then SafeAddString(SI_PROMPT_TITLE_CONFIRM_PURCHASE, "ﺀﺍﺮﺷ", 1) end
    if SI_QUEST_JOURNAL_RUMORS_BACK_ACTION then SafeAddString(SI_QUEST_JOURNAL_RUMORS_BACK_ACTION, "ﻉﻮﺟﺭ", 1) end
    if SI_RADIAL_MENU_CANCEL_BUTTON then SafeAddString(SI_RADIAL_MENU_CANCEL_BUTTON, "ﺀﺎﻐﻟﺇ", 1) end
    if SI_REWARD_END_PREVIEW_ACTION then SafeAddString(SI_REWARD_END_PREVIEW_ACTION, "ﺔﻨﻳﺎﻌﻤﻟﺍ ﺀﺎﻬﻧﺇ", 1) end
    if SI_REWARD_PREVIEW_ACTION then SafeAddString(SI_REWARD_PREVIEW_ACTION, "ﺓﺄﻓﺎﻜﻤﻟﺍ ﺔﻨﻳﺎﻌﻣ", 1) end
    if SI_SAVING_EDIT_BOX_CANCEL then SafeAddString(SI_SAVING_EDIT_BOX_CANCEL, "ﺀﺎﻐﻟﺇ", 1) end
    if SI_SCREEN_NARRATION_CROWN_STORE_ITEM_ICON_NARRATION then SafeAddString(SI_SCREEN_NARRATION_CROWN_STORE_ITEM_ICON_NARRATION, "ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ ﻦﻣ ﺮﺼﻨﻋ", 1) end
    if SI_SCREEN_NARRATION_DIRECTIONAL_INPUT_NEXT then SafeAddString(SI_SCREEN_NARRATION_DIRECTIONAL_INPUT_NEXT, "ﻲﻟﺎﺘﻟﺍ", 1) end
    if SI_SCREEN_NARRATION_DIRECTIONAL_INPUT_PREVIOUS then SafeAddString(SI_SCREEN_NARRATION_DIRECTIONAL_INPUT_PREVIOUS, "ﻖﺑﺎﺴﻟﺍ", 1) end
    if SI_SCREEN_NARRATION_EDIT_BOX_SEARCH_NAME then SafeAddString(SI_SCREEN_NARRATION_EDIT_BOX_SEARCH_NAME, "ﺚﺤﺑ", 1) end
    if SI_SCREEN_NARRATION_ITEM_PREVIEW_ACTION_TITLE then SafeAddString(SI_SCREEN_NARRATION_ITEM_PREVIEW_ACTION_TITLE, "ﺔﻨﻳﺎﻌﻤﻟﺍ ﺔﻛﺮﺣ ﺔﻟﺎﺣ", 1) end
    if SI_SCREEN_NARRATION_ITEM_PREVIEW_STATE_NEXT then SafeAddString(SI_SCREEN_NARRATION_ITEM_PREVIEW_STATE_NEXT, "ﺔﻴﻟﺎﺘﻟﺍ ﺔﻟﺎﺤﻟﺍ", 1) end
    if SI_SCREEN_NARRATION_ITEM_PREVIEW_STATE_PREVIOUS then SafeAddString(SI_SCREEN_NARRATION_ITEM_PREVIEW_STATE_PREVIOUS, "ﺔﻘﺑﺎﺴﻟﺍ ﺔﻟﺎﺤﻟﺍ", 1) end
    if SI_SCREEN_NARRATION_ITEM_PREVIEW_STATE_TITLE then SafeAddString(SI_SCREEN_NARRATION_ITEM_PREVIEW_STATE_TITLE, "ﺔﻟﺎﺤﻟﺍ ﺽﺮﻋ", 1) end
    if SI_SCREEN_NARRATION_LOCKED_SET_PIECE_ICON_NARRATION then SafeAddString(SI_SCREEN_NARRATION_LOCKED_SET_PIECE_ICON_NARRATION, "ﻰﻨﺘﻘﻣ ﺮﻴﻏ", 1) end
    if SI_SCREEN_NARRATION_NEW_ICON_NARRATION then SafeAddString(SI_SCREEN_NARRATION_NEW_ICON_NARRATION, "ﺪﻳﺪﺟ", 1) end
    if SI_SCRIBING_BACK_KEYBIND_LABEL then SafeAddString(SI_SCRIBING_BACK_KEYBIND_LABEL, "ﻉﻮﺟﺭ", 1) end
    if SI_SKILLS_PURCHASE_CONFIRM then SafeAddString(SI_SKILLS_PURCHASE_CONFIRM, "ﺀﺍﺮﺷ", 1) end
    if SI_SKILLS_SUBCLASSING_EXIT_PREVIEW_ACTION then SafeAddString(SI_SKILLS_SUBCLASSING_EXIT_PREVIEW_ACTION, "ﺔﻨﻳﺎﻌﻤﻟﺍ ﺀﺎﻬﻧﺇ", 1) end
    if SI_SKILLS_SUBCLASSING_PREVIEW_ACTION then SafeAddString(SI_SKILLS_SUBCLASSING_PREVIEW_ACTION, "ﺔﻨﻳﺎﻌﻣ", 1) end
    if SI_SKILL_RESPEC_CONFIRM_KEYBIND then SafeAddString(SI_SKILL_RESPEC_CONFIRM_KEYBIND, "ﺪﻴﻛﺄﺗ", 2) end
    if SI_SPECIALIZEDITEMTYPE600 then SafeAddString(SI_SPECIALIZEDITEMTYPE600, "ﻱﺯ", 1) end
    if SI_STATS_CONFIRM_ATTRIBUTES_BUTTON then SafeAddString(SI_STATS_CONFIRM_ATTRIBUTES_BUTTON, "ﺪﻴﻛﺄﺗ", 1) end
    if SI_STAT_GAMEPAD_COMMIT_POINTS_CANCEL then SafeAddString(SI_STAT_GAMEPAD_COMMIT_POINTS_CANCEL, "ﺀﺎﻐﻟﺇ", 1) end
    if SI_TAMRIEL_TOMES_CURRENCY_REDEMPTION_CONFIRM_ACTION then SafeAddString(SI_TAMRIEL_TOMES_CURRENCY_REDEMPTION_CONFIRM_ACTION, "ﺪﻴﻛﺄﺗ", 1) end
    if SI_TAMRIEL_TOMES_END_PREVIEW_ACTION then SafeAddString(SI_TAMRIEL_TOMES_END_PREVIEW_ACTION, "ﺔﻨﻳﺎﻌﻤﻟﺍ ﺀﺎﻬﻧﺇ", 1) end
    if SI_TAMRIEL_TOMES_PREVIEW_ACTION then SafeAddString(SI_TAMRIEL_TOMES_PREVIEW_ACTION, "ﺔﻨﻳﺎﻌﻣ", 1) end
    if SI_TIMEOFDAYPREVIEWTYPE0 then SafeAddString(SI_TIMEOFDAYPREVIEWTYPE0, "ﺡﺎﺒﺼﻟﺍ", 1) end
    if SI_TIMEOFDAYPREVIEWTYPE1 then SafeAddString(SI_TIMEOFDAYPREVIEWTYPE1, "ﺓﺮﻴﻬﻈﻟﺍ", 1) end
    if SI_TIMEOFDAYPREVIEWTYPE2 then SafeAddString(SI_TIMEOFDAYPREVIEWTYPE2, "ﺀﺎﺴﻤﻟﺍ", 1) end
    if SI_TOOLTIP_POI_LINKED_CROWN_STORE_COLLECTIBLE_LOCKED then SafeAddString(SI_TOOLTIP_POI_LINKED_CROWN_STORE_COLLECTIBLE_LOCKED, "!ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ ﻦﻣ |cffffff(<<2>>) <<1>>|r ﺀﺍﺮﺸﺑ ﺔﻘﻄﻨﻤﻟﺍ ﻩﺬﻫ ﺢﺘﻓ ﻚﻨﻜﻤﻳ", 1) end
    if SI_TOOLTIP_WAYSHRINE_CLICK_TO_OPEN_CROWN_STORE then SafeAddString(SI_TOOLTIP_WAYSHRINE_CLICK_TO_OPEN_CROWN_STORE, ".ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ ﺢﺘﻔﻟ ﺮﺴﻳﺍ ﺓﺭﺄﻔﻟﺍ ﺭﺰﺑ ﺮﻘﻧﺍ", 1) end
    if SI_TOOLTIP_WAYSHRINE_CLICK_TO_PREVIEW_HOUSE then SafeAddString(SI_TOOLTIP_WAYSHRINE_CLICK_TO_PREVIEW_HOUSE, ".ﻝﺰﻨﻤﻟﺍ ﺔﻨﻳﺎﻌﻤﻟ ﺮﺴﻳﺍ ﺓﺭﺄﻔﻟﺍ ﺭﺰﺑ ﺮﻘﻧﺍ", 1) end
    if SI_TRADING_HOUSE_BROWSE_ITEM_TYPE_ALL then SafeAddString(SI_TRADING_HOUSE_BROWSE_ITEM_TYPE_ALL, "ﻞﻜﻟﺍ", 1) end
    if SI_TRADING_HOUSE_PURCHASE_ITEM_DIALOG_CANCEL then SafeAddString(SI_TRADING_HOUSE_PURCHASE_ITEM_DIALOG_CANCEL, "ﺀﺎﻐﻟﺇ", 1) end
    if SI_TRADING_HOUSE_RESULTS_NEXT_PAGE then SafeAddString(SI_TRADING_HOUSE_RESULTS_NEXT_PAGE, "ﻲﻟﺎﺘﻟﺍ", 1) end
    if SI_TRADING_HOUSE_RESULTS_PREVIOUS_PAGE then SafeAddString(SI_TRADING_HOUSE_RESULTS_PREVIOUS_PAGE, "ﻖﺑﺎﺴﻟﺍ", 1) end
    if SI_TRIAL_PROGRESSION_KEYBIND_EXIT then SafeAddString(SI_TRIAL_PROGRESSION_KEYBIND_EXIT, "ﺝﻭﺮﺧ", 1) end
    if SI_TRIBUTE_CONFINEMENT_VIEWER_BACK_ACTION then SafeAddString(SI_TRIBUTE_CONFINEMENT_VIEWER_BACK_ACTION, "ﻉﻮﺟﺭ", 1) end
    if SI_TRIBUTE_DECK_SELECTION_CONFIRM_ACTION then SafeAddString(SI_TRIBUTE_DECK_SELECTION_CONFIRM_ACTION, "ﺪﻴﻛﺄﺗ", 1) end
    if SI_TRIBUTE_TARGET_VIEWER_CANCEL_ACTION then SafeAddString(SI_TRIBUTE_TARGET_VIEWER_CANCEL_ACTION, "ﺀﺎﻐﻟﺇ", 1) end
    if SI_TRIBUTE_TARGET_VIEWER_CONFIRM_ACTION then SafeAddString(SI_TRIBUTE_TARGET_VIEWER_CONFIRM_ACTION, "ﺪﻴﻛﺄﺗ", 1) end
    if SI_VETERANCY_BACK_ACTION_TEXT then SafeAddString(SI_VETERANCY_BACK_ACTION_TEXT, "ﻉﻮﺟﺭ", 1) end
    if SI_VETERANCY_PREVIEW_ACTION_TEXT then SafeAddString(SI_VETERANCY_PREVIEW_ACTION_TEXT, "ﺔﻨﻳﺎﻌﻣ", 1) end
    if SI_WORLD_MAP_ACTION_GO_TO_CROWN_STORE then SafeAddString(SI_WORLD_MAP_ACTION_GO_TO_CROWN_STORE, "ﻥﺎﺠﻴﺘﻟﺍ ﺮﺠﺘﻣ ﺢﺘﻓ", 1) end
    if SI_WORLD_MAP_ACTION_PREVIEW_HOUSE then SafeAddString(SI_WORLD_MAP_ACTION_PREVIEW_HOUSE, "<<1>> ﺔﻨﻳﺎﻌﻣ", 1) end
end
