-- Questbound_Strings.lua : every UI text the addon shows. W.L("KEY", ...)
-- returns the text, formatted. German and French are in Questbound_Strings_de.lua /
-- _fr.lua (same keys; a missing key falls back to English). The game client's
-- language picks the set. New keys: add them here AND in both translations.

Questbound = Questbound or {}
local W = Questbound

W.STRINGS = {}

W.STRINGS.en = {
    PREFIX = "[Questbound]",
    TITLE = "Questbound",

    -- Launcher button
    NAME_LAUNCHER = "Questbound button",
    LAUNCHER_TT = "Click: show / hide the quest tracker\nDrag: move\nRight-click: options",
    LAUNCHER_EXPAND = "Show the name",
    LAUNCHER_COLLAPSE = "Only the logo",
    LAUNCHER_HIDE_TT = "Hide this button (/qb brings it back)",
    LAUNCHER_MENU_SHOW_TRACKER = "Show the quest tracker",
    LAUNCHER_MENU_HIDE_TRACKER = "Hide the quest tracker",
    LAUNCHER_MENU_COMPACT = "Only the logo",
    LAUNCHER_MENU_WIDE = "Show the name",
    LAUNCHER_MENU_HIDE = "Hide this button",
    LAUNCHER_MENU_SETTINGS = "Settings",
    SET_HDR_LAUNCHER = "Questbound button",
    SET_LAUNCHER = "Show the Questbound button",
    SET_LAUNCHER_COMPACT = "Only the logo",
    SET_LAUNCHER_COMPACT_TT = "The button shows just the logo. The small arrow on the button switches too.",
    SET_LAUNCHER_COMBAT = "Hide the button in combat",

    -- Compact arrow animations
    SET_FX_SPIN = "Animation: spin in",
    SET_FX_SPIN_TT = "On a new objective the arrow spins in and settles on the way to go.",
    SET_FX_GLOW = "Animation: glow when facing it",
    SET_FX_GLOW_TT = "A soft halo pulses behind the arrow while you're heading the right way.",
    SET_FX_ARRIVE = "Animation: arrival",
    SET_FX_ARRIVE_TT = "When you're there the arrow twirls away, a check appears and a green ring ripples out.",
    SET_FX_TURN = "Animation: turn signal",
    SET_FX_TURN_TT = "When the objective is behind you, a light runs along the arrow's gold rim toward the side you should turn to.",
    BIND_TRACKER = "Show / hide quest tracker",
    BIND_NEXT = "Track next quest",
    BIND_PATH = "Turn Nav on / off",
    BIND_TELEPORT = "Teleport near the followed quest",
    BIND_ARROW = "Show / hide arrow",

    -- Tracker tabs and badges
    TAB_CURRENT = "Current",
    TAB_MAIN = "Main %d",
    TAB_HERE = "Here %d",
    TAB_ALL = "All %d",
    TAB_DUNGEONS = "Dungeons %d",
    TAB_DAILY = "Daily %d",
    TRACKER_EMPTY_TAB = "No quests here.",
    TRACKER_EMPTY_CURRENT = "You're not following a quest. Pick one in another tab.",
    TRACKER_EMPTY_MAIN = "No main story quests in your journal.",
    TAB_CURRENT_NAME = "Current (only the quest you follow)",
    TAB_MAIN_NAME = "Main (main story quests)",
    TAB_HERE_NAME = "Here (this zone, nearest first)",
    TAB_ALL_NAME = "All",
    TAB_DUNGEONS_NAME = "Dungeons",
    TAB_DAILY_NAME = "Daily",
    BADGE_TURNIN = "Turn in",
    BADGE_DUNGEON = "Dungeon",
    BADGE_STORY = "Story",
    BADGE_DAILY = "Daily",
    TT_MAP = "Show on the map",
    MENU_MARK = "Put a map marker on it",
    MARK_NONE = "This quest has no spot on this map.",

    -- Arrow comfort
    TT_MOVE = "Drag: move\nMouse wheel: bigger / smaller\nRight-click: options",
    TT_MOVE_LOCKED = "Locked. Right-click: options",
    MENU_LOCK = "Lock position and size",
    MENU_UNLOCK = "Unlock (move and resize)",
    MENU_BIGGER = "Bigger",
    MENU_SMALLER = "Smaller",
    MENU_DESIGN = "Design: %s (click for next)",
    MENU_RESET_POS = "Reset position and size",
    MENU_HIDE_ARROW = "Hide the arrow (/qb brings it back)",
    MENU_HIDE_TEXT = "Hide the text (/qb brings it back)",
    DESIGN_ORNATE = "Ornate",
    DESIGN_DWEMER = "Dwemer gear",
    DESIGN_ROSE = "Compass rose",
    DESIGN_BLADE = "Blade",
    DESIGN_MEDALLION = "Medallion",
    DESIGN_ARROWHEAD = "Arrowhead",
    DESIGN_OUTLINE = "Outline",
    DESIGN_TRIPLE = "Triple chevron",
    DESIGN_DAEDRIC = "Daedric",
    DESIGN_GEM = "Soul gem",
    DESIGN_WISP = "Will-o'-wisp",
    DESIGN_BANNER = "Banner",
    BIND_TEXT = "Show / hide arrow text",
    NAME_TEXT = "Arrow text",
    SET_HDR_TEXT = "Text panel (objective and distance)",
    SET_TEXT = "Show text panel",
    SET_TEXT_SIZE = "Text size",
    SET_TEXT_BG = "Background",
    SET_TEXT_BG_TT = "For the big arrow look only; the compact look has its own dark pill.",
    SET_TEXT_BG_LINES = "Text between gold lines",
    SET_TEXT_BG_DARK = "Dark",
    SET_TEXT_BG_NONE = "None (text only)",
    SET_LOCK_TEXT = "Lock position and size",
    ARROW_PROGRESS = "%d of %d done",

    -- Teleport
    TP_GO = "Travel",
    TP_TO = "Travel to %s?",
    TP_DIST = "About %s from the objective.",
    TP_CLOSER = "You're already closer to it than this wayshrine.",
    TP_ROUGH = "The quest has no exact spot on the map yet, so this is a wayshrine in %s.",
    TP_FREE ="Free (you're at a wayshrine).",
    TP_COST = "Cost: %s",
    TP_GOLD = "%d gold",
    TP_COOLDOWN = "Recall ready in %s",
    TP_NONE = "No known wayshrine near this quest.",
    TP_NONE_ZONE = "You haven't discovered a wayshrine in %s yet, so you can't travel there. Get there once on foot (follow the arrow); after that, travel works.",
    TP_NO_QUEST = "You're not following a quest.",
    TP_MAP_OPEN = "Close the map first.",
    TP_DEAD = "You can't travel while dead.",
    TP_COMBAT = "You can't travel while in combat.",
    TP_PVP = "You can't travel from here (PvP zone).",

    -- Quest tracker
    TRACKER_TITLE = "QUESTBOUND",
    TRACKER_COUNT = "%d/%d",
    ZONE_OTHER = "Other quests",
    FOLLOWING = "FOLLOWING",
    TURN_IN = "turn in",
    TT_TELEPORT = "Teleport to the wayshrine closest to this quest",
    MENU_TELEPORT = "Teleport near this quest",
    OPTIONAL = "Optional",

    -- Group dungeon quests
    DUNGEON_HINT = "Group dungeon: queue for %s",
    TT_QUEUE = "%s is a group dungeon.\nClick to queue for it.",
    MENU_QUEUE = "Queue for the dungeon",
    ARROW_DUNGEON = "Group dungeon: %s",
    QUEUE_CLICK = "Click here to queue",
    TT_QUEUE_CLICK = "Click: queue for the dungeon in the Group Finder",
    QUEUE_TEXT = "This quest only counts inside %s.\n\nQueue for it in the Group Finder (%s, as %s)?",
    QUEUE_GO = "Queue",
    NORMAL = "Normal",
    VETERAN = "Veteran",
    QUEUED = "Queued for %s (%s).",
    QUEUE_ALREADY = "You're already in the Group Finder queue.",
    QUEUE_LEADER = "Only the group leader can queue.",
    QUEUE_FAIL = "Couldn't queue. Open the Group Finder to queue.",
    QUEUE_DLC = "%s needs %s.",

    -- Banner
    BANNER_OBJECTIVE = "Objective complete",
    BANNER_STEP = "Quest updated",
    BANNER_NEXT = "Next: %s",
    TT_MINIMIZE = "Minimize",
    TT_RESTORE = "Show quests",
    TT_SETTINGS = "Settings",
    TT_OPACITY = "Background opacity",
    TT_LOCK = "Position: %s (click to lock)",
    TT_PATH_HIDE = "Nav (Navigator): %s (click to turn off)",
    TT_PATH_SHOW = "Nav (Navigator): %s (click to turn on)",
    TT_UNLOCK = "Position: %s (click to unlock)",
    STATE_UNLOCKED = "unlocked",
    STATE_LOCKED = "locked",
    STATE_OFF = "off",
    STATE_ON = "on",
    MENU_ASSIST = "Follow with the arrow",
    MENU_EXPAND = "Show objectives",
    MENU_COLLAPSE = "Hide objectives",
    MENU_MAP = "Show on map",
    MENU_JOURNAL = "Open in quest journal",
    MENU_SHARE = "Share with group",
    MENU_PIN = "Pin to the top",
    MENU_UNPIN = "Unpin",
    MENU_HIDE = "Hide from the list",
    MENU_UNHIDE = "Show in the list again",
    MENU_ABANDON = "Abandon quest",
    GROUP_PINNED = "Pinned",
    GROUP_HIDDEN = "Hidden quests",
    GROUP_TURNIN = "Ready to turn in",
    REWARDS = "Rewards",
    REWARD_SKILL = "Skill point",
    TT_SEARCH = "Search quests",
    TT_SEARCH_CLOSE = "Close the search",
    SEARCH_HINT = "Search quests or zones...",
    TRACKER_EMPTY_SEARCH = "No quests match.",

    -- Arrow
    ARRIVED = "You're there",
    LEVEL_ABOVE = "· Upstairs",
    LEVEL_BELOW = "· Downstairs",
    FIND_STAIRS_UP = "· Upstairs: find the way up",
    FIND_STAIRS_DOWN = "· Downstairs: find the way down",
    WAYPOINT = "Map marker",
    CALIBRATING = "Walk a few steps to measure the distance",
    DIST_M = "%d m",
    DIST_KM = "%.1f km",
    DIST_FT = "%d ft",
    DIST_MI = "%.1f mi",
    SET_MINIMAP = "Show the way on AUI's minimap",
    SET_MINIMAP_TT = "With the Advanced UI (AUI) addon's minimap: a dotted gold line to your objective and a ring on it, or an arrow on the minimap's edge when it's further away. (Needs AUI with its minimap turned on.)",
    SET_UNITS = "Distance units",
    SET_UNITS_TT = "How distances are shown under the arrow, in the tracker and elsewhere.",
    SET_UNITS_METRIC = "Meters and kilometers",
    SET_UNITS_IMPERIAL = "Feet and miles",
    OTHER_MAP = "Follow the marker to the next area",
    NEXT_AREA_TO = "Next area › %s",
    THROUGH_DOOR_TO = "Through the door › %s",
    ARROW_ELSEWHERE = "In %s",
    TRAVEL_TO_ZONE = "Faster: click to travel to %s",
    TRAVEL_FASTER = "Faster: travel to %s (saves %s)",
    TT_TRAVEL = "Click: travel (shows cost and cooldown first)",
    SET_TRAVEL_HINT = "Suggest faster travel",
    SET_TRAVEL_HINT_TT = "When a wayshrine you know is much closer to the objective than you are, the text says so; click the text to travel. For a quest in another zone it offers to take you there.",
    ARROW_PVP = "In %s (PvP)",
    PVP_JOIN = "Click here to join %s",
    PVP_PICK = "Click here to pick a campaign",
    TT_PVP_CLICK = "Click: join the campaign (the game asks you to confirm)",
    TT_PVP_ROW = "PvP quest: click to join your Cyrodiil campaign\n(or pick one in the Alliance War window)",
    MENU_PVP = "Join a PvP campaign",

    -- Chat / slash command
    HELP = "/qb  show or hide the quest tracker (and bring back anything you hid)\n/qb arrow  show or hide the arrow\n/qb text  show or hide the arrow's text\n/qb nav  turn Nav (arrows on the ground) on or off\n/qb skip  turn Skip dialogue on or off\n/qb story  read the stories Skip dialogue clicked through\n/qb next  follow the next quest\n/qb banner  preview the objective banner\n/qb settings  open the settings\n/qb reset  put everything back in its place",
    SHOWN = "%s shown.",
    HIDDEN = "%s hidden.",
    HIDDEN_HINT = "%s hidden. Type %s to show it again.",
    NAME_TRACKER = "Quest tracker",
    NAME_ARROW = "Arrow",
    NAME_PATH = "Nav",
    RESET_DONE = "Positions reset.",
    NO_LAM = "Settings need LibAddonMenu-2.0 installed.",
    NO_3D = "Your game version can't draw the Nav arrows on the ground.",
    TEX_MISSING = "Some new Questbound images aren't loaded yet. Quit the game completely and start it again (/reloadui isn't enough for new images). Until then Nav uses dots.",

    -- Settings
    SET_INFO = "Quest tracker, direction arrow and Nav arrows on the ground that lead you to your quest objective or to the marker you put on the map.",
    SET_HDR_NAV = "Navigation",
    SET_TARGET = "Follow",
    SET_TARGET_TT = "What the arrow and Nav lead you to.",
    SET_TARGET_AUTO = "Map marker first, else quest",
    SET_TARGET_QUEST = "Followed quest only",
    SET_TARGET_WAYPOINT = "Map marker only",
    SET_HDR_TRACKER = "Quest tracker",
    SET_TRACKER = "Show quest tracker",
    SET_HIDE_GAME = "Hide the game's quest tracker",
    SET_HIDE_GAME_TT = "Questbound's tracker replaces it.",
    SET_HIDE_AUI = "Hide Advanced UI's quest tracker",
    AUI_HIDDEN_NOTE = "Questbound hid Advanced UI's quest tracker, since Questbound shows your quests (AUI's minimap stays). Want it back? Settings > Add-Ons > Questbound > Quest tracker.",
    SET_HIDE_AUI_TT = "Hides the quest tracker under AUI's minimap while Questbound's tracker is shown. AUI's own settings stay as they are: turn this off (or disable Questbound) and its tracker is back. Only available when AUI's quest tracker is on.",
    SET_EXPAND_ALL = "Show objectives of every quest",
    SET_EXPAND_ALL_TT = "Off: only the followed quest (and quests you open) show their objectives.",
    SET_TRACKER_DIST = "Show distances",
    SET_TELEPORT = "Travel, queue and PvP icons next to quests",
    SET_PANEL = "Tracker frame",
    SET_PANEL_ESO = "Gold border",
    SET_PANEL_FLAT = "No border",
    SET_PANEL_TRAIL = "Frameless with trail",
    SET_PANEL_LEDGER = "Ledger (gold frame, card for the followed quest)",
    SET_ARROW_STYLE = "Arrow look",
    SET_ARROW_STYLE_TT = "Compact: a small arrow badge inside the text, on a dark pill.\nBig arrow: a large arrow with the text under it (pick its design below).",
    SET_ARROW_STYLE_COMPACT = "Compact",
    SET_ARROW_STYLE_CLASSIC = "Big arrow",
    MENU_ARROW_STYLE = "Look: %s (click to switch)",
    SET_HDR_LOOK = "General",
    SET_ANIM = "Animations",
    SET_ANIM_TT = "Full: the arrow spins in on a new objective, glows when you face it and signals when to turn around; the Nav arrows flow and draw themselves out; markers bob and pulse.\nSubtle: only the glow, the arrival and the flowing Nav arrows.\nOff: everything stands still.",
    SET_ANIM_FULL = "Full",
    SET_ANIM_SUBTLE = "Subtle",
    SET_ANIM_OFF = "Off",
    SET_COMBAT_FADE = "Fade in combat",
    SET_COMBAT_FADE_TT = "The tracker and the text next to the arrow become see-through while you fight (the tracker comes back when you point at it).",
    SET_TAB = "Tab shown",
    SET_ARROW_DESIGN = "Arrow design",
    SET_NPC_MARKER = "Marker above the objective",
    SET_NPC_MARKER_TT = "An Elder Scrolls quest marker hovers above the person you have to talk to (or your map marker, or the spot to reach, once you're close), with a golden ring of light on the ground.",
    SET_KILL_AREA = "Hunting area for monsters to kill",
    SET_KILL_AREA_TT = "Where a quest wants monsters killed, the area glows faint red on the ground with crossed swords over its middle.",
    SET_KILL_BADGE = "Quest badge on the crosshair",
    SET_KILL_BADGE_TT = "When you aim at a monster one of your quests wants dead, a small red badge with the count (3 / 5) shows next to your crosshair.",
    SET_PILLAR = "Light pillar on far objectives",
    SET_PILLAR_TT = "A soft pillar of light rises from map markers and objectives that are far away, so you can spot them. Close by it fades into the marker.",
    SET_STYLE_SOLID = "Solid chevrons",
    SET_STYLE_CHEVRONS = "Dotted chevrons",
    SET_STYLE_COMET = "Comet",
    SET_THEME = "Accent color",
    SET_THEME_TT = "Titles, highlights, the arrow and the header buttons. Changing it makes your own Custom theme. (Nav has its own color below.)",
    SET_COLORS_INFO = "Pick a ready-made color theme, or change any of the three colors below to make your own. Text colors adjust by themselves, so everything stays readable with any color.",
    SET_COLOR_THEME = "Color theme",
    SET_COLOR_THEME_TT = "The colors of the quest tracker, the Questbound button, the story window and the arrow badge.",
    SET_PANEL_COLOR = "Background color",
    SET_PANEL_COLOR_TT = "The windows' background (its see-through amount is the tracker's own slider). Very light colors are darkened a little, so the game's white icons stay visible.",
    SET_FRAME_COLOR = "Frame and line color",
    SET_FRAME_COLOR_TT = "Window frames, corners and divider lines.",
    SET_COLORS_RESET = "Back to the standard colors",
    THEME_DEFAULT = "Questbound gold (standard)",
    THEME_ALDMERI = "Aldmeri Dominion",
    THEME_DAGGERFALL = "Daggerfall Covenant",
    THEME_EBONHEART = "Ebonheart Pact",
    THEME_SILVER = "Silver",
    THEME_OBSIDIAN = "Obsidian (black and white)",
    THEME_BRONZE = "Bronze",
    THEME_COPPER = "Copper",
    THEME_AMBER = "Amber",
    THEME_EMBER = "Ember",
    THEME_SUNSET = "Sunset",
    THEME_CRIMSON = "Crimson",
    THEME_RUBY = "Ruby",
    THEME_ROSE = "Rose",
    THEME_DAEDRIC = "Daedric magenta",
    THEME_AMETHYST = "Amethyst",
    THEME_VIOLET = "Violet",
    THEME_MIDNIGHT = "Midnight blue",
    THEME_SAPPHIRE = "Sapphire",
    THEME_ICE = "Ice",
    THEME_TEAL = "Teal",
    THEME_PSIJIC = "Psijic",
    THEME_JADE = "Jade",
    THEME_EMERALD = "Emerald",
    THEME_FOREST = "Forest",
    THEME_OLIVE = "Olive",
    THEME_DWEMER = "Dwemer brass",
    THEME_SLATE = "Slate",
    THEME_CUSTOM = "Custom (my own colors)",
    SET_FONT_STYLE = "Font style",
    SET_FONT_STYLE_TT = "Elder Scrolls: carved title letters and book-style quest names, like the game's own menus.",
    SET_STYLE_ESO = "Elder Scrolls",
    SET_STYLE_BOOK = "Book",
    SET_STYLE_PLAIN = "Plain",
    SET_FOLLOW_NEW = "Follow new quests right away",
    SET_FOLLOW_NEW_TT = "When you accept a quest (from someone you talk to, a letter...), the arrow and tracker switch to it. A quest you pick in the tracker stays followed until you accept the next one.",
    SET_BANNER = "Objective banner",
    SET_BANNER_TT = "When the followed quest moves on, show what's done and where to go next in the middle of the screen.",
    SET_BG = "Background opacity",
    SET_BG_TT = "Slide left for a see-through background, right for a darker one (0 = fully see-through, 100 = solid). The text and icons don't change.",
    SET_FONT = "Text size",
    SET_LOCK_TRACKER = "Lock position",
    SET_HDR_ARROW = "Arrow",
    SET_ARROW = "Show arrow",
    SET_ARROW_SIZE = "Size",
    SET_ARROW_NAME = "Show objective name",
    SET_ARROW_DIST = "Show distance",
    SET_ARROW_ANGLE = "Color shows the direction",
    SET_ARROW_ANGLE_TT = "Bright when you face the right way, orange when it's behind you.",
    SET_ARROW_COMBAT = "Hide in combat",
    SET_ARROW_COMBAT_TT = "Hides the arrow and its text while you fight.",
    SET_LOCK_ARROW = "Lock position",
    SET_ARROW_TIP = "With the mouse cursor shown (the '.' key by default): drag the arrow or its text to move it, use the mouse wheel over it to resize, right-click it for options. Hide or show them any time with /qb arrow, /qb text or a keybind.",
    SET_HDR_PATH = "Nav (Navigator: arrows on the ground)",
    SET_HDR_MARKERS = "Markers and minimap",
    SET_PATH = "Turn on Nav",
    SET_PATH_STYLE = "Style",
    SET_STYLE_LINE = "Line",
    SET_STYLE_DOTS = "Dots",
    SET_PATH_LENGTH = "Length (meters)",
    SET_PATH_WIDTH = "Size",
    SET_PATH_ALPHA = "Opacity",
    SET_PATH_FLOW = "Moving flow",
    SET_PATH_FLOW_TT = "Nav arrows slowly flow toward the objective.",
    SET_PATH_DEPTH = "Hide behind walls and hills",
    SET_PATH_DEPTH_TT = "Off: the Nav arrows are always visible. On: they hide behind anything in front of them (they can sink into slopes).",
    SET_PATH_MARKER = "Rings at the objective",
    SET_PATH_MARKER_TT = "Rings ripple on the spot when the objective is in reach of Nav, and green rings when you arrive.",
    SET_PATH_COLOR = "Color",
    SET_PATH_NOTE = "Where you've walked before, the arrows follow the streets (see Streets below); elsewhere they point straight at the objective, at your own height.",
    SET_HDR_ROADS = "Streets (Nav follows where you've walked)",
    SET_ROADS_INFO = "The game tells addons nothing about walls or streets, so Questbound learns them: while you walk it quietly remembers your way, and Nav then follows those streets, around walls and through alleys. Where you haven't walked yet it points straight at the objective. It gets better the more you play.",
    SET_ROADS = "Nav follows learned streets",
    SET_ROADS_TT = "Off: always straight toward the objective.",
    SET_LEARN = "Learn streets while I walk",
    SET_LEARN_TT = "Remembers where you walk (a point every few meters, per zone).",
    SET_FORGET_ROADS = "Forget streets in this zone",
    SET_FORGET_ROADS_TT = "Deletes what Questbound learned about the streets of the zone you're in (for example after walking through a wall glitch), and the doors and floor heights it learned on this map.",
    SET_FORGET_ROADS_WARN = "All learned streets of this zone, and the doors and floor heights of this map, are deleted. This can't be undone.",
    -- Skip dialogue (Questbound_Skip.lua)
    BIND_SKIP = "Skip dialogue on / off",
    TT_SKIP_ON = "Skip dialogue: %s\nQuest conversations click through by themselves.\nHold Shift as you start talking to read one.\nClick to turn off.",
    TT_SKIP_OFF = "Skip dialogue: %s\nClick to let Questbound click through quest conversations for you.",
    SKIP_NOW_ON = "Skip dialogue is on. Hold Shift as you start talking to read a conversation.",
    SKIP_NOW_OFF = "Skip dialogue is off.",
    SKIP_CHOICE = "This one is your choice: pick an answer.",
    SKIP_OTHER_ADDON = "%s is installed too and may answer as well. Turn one of the two off.",
    SET_HDR_SKIP = "Skip dialogue",
    SET_SKIP_INFO = "Clicks through quest conversations for you, and at choices picks the best answer. Red answers (big decisions) are left to you unless you turn them on below. Shops, banks and answers that cost gold are never touched. Also on the button in the quest tracker's header.",
    SKIP_PICKED = "Chose: %s",
    SET_SKIP_REWARD = "Pick the reward that fits my gear",
    SET_SKIP_REWARD_TT = "When a conversation lets you choose your reward (a sword or a staff, light or heavy armor...), Questbound takes the one that matches what you wear: your most-worn armor weight and your weapons. (ESO picks the item itself when you hand a quest in; these conversation picks are the only reward choices.)",
    SET_SKIP_RED = "Skip all choices, including the ones you must make",
    SET_SKIP_RED_TT = "Off (standard): Questbound stops at the red answers, the big decisions of a quest, and you choose. On: it picks those too, so every conversation is skipped. Leave it off if you want to make the important choices yourself.",
    SET_SKIP_HIDE = "Hide the dialogue window while skipping",
    SET_SKIP_HIDE_TT = "The fastest way through: the conversation window stays invisible while Questbound answers, and comes back the moment you're needed (a choice, a shop...).",
    SKIP_READ = "Read: %s",
    SKIP_SAVED = "Saved you about %s of dialogue so far.",
    TIME_H_M = "%d h %d min",
    TIME_M = "%d min",
    TIME_LESS = "less than a minute",
    STORY_TITLE = "Skipped stories",
    STORY_EMPTY = "Nothing here yet. Conversations that Skip dialogue clicks through are kept here, per quest, so you can read the story whenever you like.",
    STORY_OTHER = "Other conversations",
    STORY_SUB = "%d conversations · story %d of %d",
    STORY_SOMEONE = "Someone",
    STORY_OLDER = "Older story",
    STORY_NEWER = "Newer story",
    MENU_STORY = "Read the story (skipped dialogue)",
    SET_SKIP_STORY = "Read skipped stories",
    SET_SKIP_STORY_TT = "Everything NPCs said in the conversations Questbound skipped, and the answers it gave, per quest. Also: right-click a quest in the tracker, or /qb story.",
    SET_SKIP_TYPES = "Which quests to skip",
    SET_SKIP_TYPES_TT = "Turn a kind of quest off to read its conversations yourself.",
    SET_SKIP_TYPES_INFO = "All kinds are skipped by default. Turn one off and its conversations are shown as usual. Conversations Questbound can't link to a quest count as side quests.",
    SKIP_TYPE_MAIN = "Main story and prologues",
    SKIP_TYPE_ZONE = "Zone stories",
    SKIP_TYPE_SIDE = "Side quests",
    SKIP_TYPE_GUILD = "Guild quests",
    SKIP_TYPE_DAILY = "Dailies and repeatable quests",
    SKIP_TYPE_DUNGEON = "Dungeons, trials and pledges",
    SKIP_TYPE_COMPANION = "Companion quests",
    SKIP_TYPE_CRAFTING = "Crafting writs",
    SKIP_TYPE_PVP = "PvP and battlegrounds",
    SKIP_TYPE_EVENT = "Event quests",
    SET_SKIP_READ = "Read quest notes for me",
    SET_SKIP_READ_TT = "When a quest says to read a note, letter or book you carry, Questbound opens it for you (from your quest items or your bag) and closes it again: the step counts at once. Waits until a fight is over.",
    SET_SKIP_BOOKS = "Close quest books and notes at once",
    SET_SKIP_BOOKS_TT = "Opening a book or note already counts (quest step, lore library), so it can close right away. Hold Shift to read one.",
    SET_SKIP = "Skip dialogue",
    SET_SKIP_TT = "Same as the speech bubble button in the quest tracker, the keybind and /qb skip.",
    SET_SKIP_ACCEPT = "Accept quests",
    SET_SKIP_TURNIN = "Hand in finished quests",
    SET_SKIP_CHOICES = "Pick the best answer at choices",
    SET_SKIP_CHOICES_TT = "When a conversation offers several answers, Questbound picks the one with the best outcome: [Persuade] / [Intimidate] first, then answers that move the quest on, sparing over killing; never turning a quest down or paying gold. The answer it chose is written to chat. Off: it stops and you pick.",
    SET_SKIP_SEEN = "Only skip what I've read before",
    SET_SKIP_SEEN_TT = "New conversations are shown as usual; once you've read one, it's skipped next time. Handy for dailies and repeat quests.",
    SET_SKIP_CHAT = "Also write skipped lines to chat",
    SET_SKIP_CHAT_TT = "Off: the chat stays clean; the skipped story is kept per quest (right-click a quest in the tracker: \"Read the story\"). On: the lines and the answers chosen are also written to chat.",
    SET_SKIP_SHIFT = "Hold Shift to read a conversation",
    SET_SKIP_SHIFT_TT = "Hold Shift as you start talking to someone: that conversation isn't skipped.",
    SET_SKIP_CLOSE = "Close the window when done",
    SET_SKIP_CLOSE_TT = "Ends the conversation once there's nothing new left to say.",
    SET_HDR_MISC = "Other",
    SET_RESET_CAL = "Measure maps again",
    SET_RESET_CAL_TT = "Forget the learned map sizes (use if distances look wrong).",
    SET_RESET_POS = "Reset positions",
}

local active = "en"

function W.SetLanguage(choice)
    local lang = choice
    if lang == nil or lang == "auto" or not W.STRINGS[lang] then
        lang = GetCVar and GetCVar("language.2") or "en"
    end
    if not W.STRINGS[lang] then lang = "en" end
    active = lang
end

-- Text for key in the active language (English if missing), formatted with the extra arguments.
function W.L(key, ...)
    local text = W.STRINGS[active][key]
    if text == nil then text = W.STRINGS.en[key] end
    if text == nil then return key end
    if select("#", ...) > 0 then return string.format(text, ...) end
    return text
end

W.SetLanguage("auto")
