-- Назви гліфів, сутностей, зілль та отрут (українською -> англійською) для таблиці цін TTC.
-- Потрібні, бо мовна база містить лише базові назви цих предметів без префіксів сили.
DovahMova.IntegrationStrings.TamrielTradeCentre = {
	glyphPrefixes = {
		["нікчемний"] = "trifling",
		["убогий"] = "inferior",
		["жалюгідний"] = "petty",
		["крихітний"] = "slight",
		["малий"] = "minor",
		["незначний"] = "lesser",
		["помірний"] = "moderate",
		["звичайний"] = "average",
		["могутній"] = "strong",
		["видатний"] = "major",
		["величезний"] = "greater",
		["грандіозний"] = "grand",
		["славетний"] = "splendid",
		["монументальний"] = "monumental",
		["пречудовий"] = "superb",
		["воістину величний"] = "truly superb"
	},
	glyphTypes = {
		--броня (armor glyphs)
		["гліф здоров'я"] = "glyph of health",
		["гліф магіки"] = "glyph of magicka",
		["гліф витривалості"] = "glyph of stamina",
		["гліф призматичного захисту"] = "glyph of prismatic defense",
		--зброя (weapon glyphs)
		["гліф поглинання здоров'я"] = "glyph of absorb health",
		["гліф поглинання магіки"] = "glyph of absorb magicka",
		["гліф поглинання витривалості"] = "glyph of absorb stamina",
		["гліф розбивання"] = "glyph of crushing",
		["гліф зниження здоров'я"] = "glyph of decrease health",
		["гліф полум'я"] = "glyph of flame",
		["гліф спалення"] = "glyph of foulness",
		["гліф морозу"] = "glyph of frost",
		["гліф затвердження"] = "glyph of hardening",
		["гліф отрути"] = "glyph of poison",
		["гліф сокрушаючого удару"] = "glyph of prismatic onslaught",
		["гліф удару блискавки"] = "glyph of shock",
		["гліф слабкості"] = "glyph of weakening",
		["гліф зброярської шкоди"] = "glyph of weapon damage",
		--прикраси (jewelry glyphs)
		["гліф збільшення фізичної шкоди"] = "glyph of increase physical harm",
		["гліф збільшення магічної шкоди"] = "glyph of increase magical harm",
		["гліф відновлення здоров'я"] = "glyph of health recovery",
		["гліф відновлення магіки"] = "glyph of magicka recovery",
		["гліф відновлення витривалості"] = "glyph of stamina recovery",
		["гліф зниження вартості заклять"] = "glyph of reduce spell cost",
		["гліф зниження вартості здібностей"] = "glyph of reduce feat cost",
		["гліф зміцнення"] = "glyph of bracing",
		["гліф добивання"] = "glyph of bashing",
		["гліф зниження фізичного шкоди"] = "glyph of decrease physical harm",
		["гліф зниження магічного шкоди"] = "glyph of decrease spell harm",
		["гліф стійкості до полум'я"] = "glyph of flame resist",
		["гліф стійкості до морозу"] = "glyph of frost resist",
		["гліф стійкості до блискавки"] = "glyph of shock resist",
		["гліф стійкості до отрути"] = "glyph of poison resist",
		["гліф стійкості до хвороби"] = "glyph of disease resist",
		["гліф прискорення дії зілля"] = "glyph of potion speed",
		["гліф посилення дії зілля"] = "glyph of potion boost",
		["гліф призматичного відновлення"] = "glyph of prismatic recovery",
		["гліф зниження вартості навичок"] = "glyph of reduce skill cost"
	},
	essences = {
		["сутність героїзм"] = "essence of heroism",
		["сутність швидкість"] = "essence of speed",
		["сутність розбиття броні"] = "essence of ravage armor",
		["сутність виснаження витривалості"] = "essence of ravage stamina",
		["сутність виявлення"] = "essence of detection",
		["сутність виснаження"] = "essence of enervation",
		["сутність нерішучість"] = "essence of timidity",
		["сутність осквернення"] = "essence of defile",
		["сутність виснаження магіки"] = "essence of ravage magicka",
		["сутність захист від заклинань"] = "essence of spell protection",
		["сутність ослаблення"] = "essence of maim",
		["сутність виснаження здоров'я"] = "essence of ravage health",
		["сутність боягузтво"] = "essence of cowardice",
		["сутність вразливість"] = "essence of vulnerability",
		["сутність броня"] = "essence of armor",
		["сутність критичний удар заклинання"] = "essence of spell critical",
		["сутність пастка"] = "essence of entrapment",
		["сутність поступове відновлення здоров'я"] = "essence of lingering health",
		["сутність поступове спустошення здоров'я"] = "essence of creeping ravage health",
		["сутність виснаження захисту від заклинань"] = "essence of ravage spell protection",
		["сутність захист"] = "essence of protection",
		["сутність невпевненість"] = "essence of uncertainty",
		["сутність здоров'я"] = "essence of health",
		["сутність магіка"] = "essence of magicka",
		["сутність сила зброї"] = "essence of weapon power",
		["сутність сила заклинання"] = "essence of spell power",
		["сутність життєва сила"] = "essence of vitality",
		["сутність гальмування"] = "essence of hindering",
		["сутність нерухомість"] = "essence of immovability",
		["сутність витривалість"] = "essence of stamina",
		["сутність критичний удар зброї"] = "essence of weapon crit",
		["сутність невидимість"] = "essence of invisibility"
	},
	potionTypes = {
		["сплеск"] = "effusion of",
		["витяжка"] = "distillate of",
		["краплина"] = "dram of",
		["еліксир"] = "elixir of",
		["зілля"] = "potion of",
		["ковток"] = "sip of",
		["настоянка"] = "tincture of",
		["панацея"] = "panacea of",
		["відвар"] = "solution of",
		["сироватка"] = "serum of",
		["трунок"] = "philter of"
	},
	potions = {
		["боягузтво"] = "cowardice",
		["броня"] = "armor",
		["виснаження"] = "enervation",
		["виснаження витривалості"] = "ravage stamina",
		["виснаження захисту від заклинань"] = "ravage spell protection",
		["виснаження здоров'я"] = "ravage health",
		["виснаження магіки"] = "ravage magicka",
		["витривалість"] = "stamina",
		["виявлення"] = "detection",
		["вразливість"] = "vulnerability",
		["гальмування"] = "hindering",
		["героїзм"] = "heroism",
		["життєва сила"] = "vitality",
		["захист"] = "protection",
		["захист від заклинань"] = "spell protection",
		["здоров'я"] = "health",
		["критичний удар заклинання"] = "spell critical",
		["критичний удар зброї"] = "weapon crit",
		["магіка"] = "magicka",
		["невидимість"] = "invisibility",
		["нерухомість"] = "immovability",
		["нерішучість"] = "timidity",
		["осквернення"] = "defile",
		["ослаблення"] = "maim",
		["пастка"] = "entrapment",
		["поступове відновлення здоров'я"] = "lingering health",
		["поступове спустошення здоров'я"] = "creeping ravage health",
		["розбиття броні"] = "ravage armor",
		["сила заклинання"] = "spell power",
		["сила зброї"] = "weapon power",
		["швидкість"] = "speed",
	},
	romanNumerals = {
		["i"] = "I",
		["ii"] = "II", 
		["iii"] = "III",
		["iv"] = "IV",
		["v"] = "V",
		["vi"] = "VI",
		["vii"] = "VII",
		["viii"] = "VIII",
		["ix"] = "IX",
		["x"] = "X"
	},
	poisons = {
		-- Basic poison types (alphabetically sorted)
		["отрута: боягузтво"] = "cowardice poison",
		["отрута: втеча"] = "escapist's poison",
		["отрута: висмоктування витривалості"] = "drain stamina poison",
		["отрута: висмоктування жорстокості"] = "brutality-draining poison",
		["отрута: висмоктування здоров'я"] = "drain health poison",
		["отрута: висмоктування захисту"] = "ward-draining poison",
		["отрута: висмоктування лютості"] = "savagery-draining poison",
		["отрута: висмоктування магії"] = "drain magicka poison",
		["отрута: висмоктування пророцтва"] = "prophecy-draining poison",
		["отрута: висмоктування прихованості"] = "stealth-draining poison",
		["отрута: висмоктування рішучості"] = "resolve-draining poison",
		["отрута: висмоктування чарів"] = "sorcery-draining poison",
		["отрута: висмоктування швидкості"] = "speed-draining poison",
		["отрута: каліцтво"] = "maiming poison",
		["отрута: невпевненість"] = "uncertainty poison",
		["отрута: ослаблення"] = "enervating poison",
		["отрута: пастка"] = "entrapping poison",
		["отрута: помітність"] = "conspicuous poison",
		["отрута: руйнування"] = "fracturing poison",
		["отрута: сповільнення"] = "hindering poison",
		["отрута: шкода витривалості"] = "damage stamina poison",
		["отрута: шкода здоров'ю"] = "damage health poison",
		["отрута: шкода магії"] = "damage magicka poison",
		
		-- Cloudy poison variants
		["отрута для здоров'я з туманним ефектом"] = "cloudy damage health poison",
		["хмарна стримуюча отрута"] = "cloudy hindering poison",
		["хмарний поступовий спустошливий ефект здоров'я отрути"] = "cloudy gradual ravage health poison",
		
		-- Special poison types
		["отрута вразливості"] = "vulnerability poison",
		["отрута нерішучості"] = "timidity poison",
		["отрута осквернення"] = "defiling poison",
		["отрута виснаження життєвої сили"] = "vitality-draining poison",
		["отрута поступового виснаження здоров'я"] = "gradual health drain poison",
		["отрута поступового спустошення здоров'я"] = "gradual ravage health poison",
		["отрута, що скасовує захист"] = "protection-reversing poison",
		
		-- Named poison types
		["проривна отрута"] = "breaching poison",
		["травматична отрута"] = "traumatic poison"
	},
}
