local env = dofile("tests/addon.lua")
function DoesUnitExist(tag) return tag == "player" or tag == "reticleover" end
env.setClock(30)
env.setBuffs("reticleover", { { 39077, 30, 37 } })
env.setting("Effekt-ID").setFunction("39077")
env.setting("Einheit").setFunction(nil, nil, { data = "reticleover" })
env.setting("Tracker hinzufuegen").clickHandler()
local window = env.controls.LiveBuffUptimeTracker3
env.setClock(32)
env.events.tick()
assert(window.labels[1].text == "5.0" and window.labels[2].text == "100.0 %")
env.setClock(37)
env.setBuffs("reticleover", { { 134599, 37, 52 } })
env.events.tick()
assert(window.labels[1].text == "15.0")
env.setClock(40)
env.events.tick()
assert(window.labels[1].text == "12.0")
assert(window.labels[2].text == "100.0 %", "Immunity must be excluded from the denominator")
env.setting("Immunitaetszeit aus Uptime ausnehmen").setFunction(false)
assert(window.labels[2].text == "70.0 %", "Original fight uptime must remain available")
env.setting("Immunitaetszeit aus Uptime ausnehmen").setFunction(true)
env.setClock(52)
env.events.tick()
assert(window.labels[1].text == "--", "Expired immunity must disappear")
env.setBuffs("reticleover", { { 39077, 52, 59 } })
env.events.tick()
env.setClock(54)
env.events.tick()
assert(window.labels[2].text == "100.0 %", "Immediate reapplication must retain full eligible uptime")
env.setCombat(false)
env.events[EVENT_PLAYER_COMBAT_STATE](nil, false)
env.setClock(56)
env.events.tick()
assert(window.labels[2].text == "100.0 %", "Eligible uptime must freeze after combat ends")
env.setCombat(true)
env.events[EVENT_PLAYER_COMBAT_STATE](nil, true)
env.setBuffs("reticleover", { { 134599, 56, 71 }, { 39077, 56, 63 } })
env.events.tick()
assert(window.labels[1].text == "7.0", "Active Off Balance takes priority")
env.setBuffs("reticleover", {})
env.events[EVENT_RETICLE_TARGET_CHANGED]()
assert(window.labels[1].text == "--", "Immunity must follow the current target")
print("Off Balance: shared timer, immunity exclusion, reversible setting, fight freeze and target switch passed")
