local env = dofile("tests/libcombat.lua")
env.setClock(47)
env.setBuffs("player", { { 123, 46, 50 } })
env.setting("Effekt-ID").setFunction("123")
env.setting("Tracker hinzufuegen").clickHandler()
local window = env.controls.LiveBuffUptimeTracker2
local function damage(at)
    env.setClock(at)
    env.callbacks[LIBCOMBAT_EVENT_DAMAGE_OUT](nil, at * 1000 + 100000)
    env.events.tick()
end
damage(48)
damage(49)
assert(window.labels[2].text == "100.0 %")

-- No library fade: the known snapshot expiry still bounds the interval.
env.setClock(52)
env.setBuffs("player", {})
env.events.tick()
damage(54)
assert(window.labels[2].text == "33.3 %", "Initial buff must stop at 50, not the next library event")

-- A later application must not bridge the gap after the initial buff expired.
env.setClock(55)
env.setBuffs("player", { { 123, 55, 57 } })
env.callbacks[LIBCOMBAT_EVENT_EFFECTS_IN](nil, 155000, 1, 123, EFFECT_RESULT_GAINED, 0, 1, 0, 2)
env.setClock(57)
env.callbacks[LIBCOMBAT_EVENT_EFFECTS_IN](nil, 157000, 1, 123, EFFECT_RESULT_FADED, 0, 1, 0, 2)
damage(58)
assert(window.labels[2].text == "40.0 %", "Two separate applications must remain separate")
env.setClock(60)
env.callbacks[LIBCOMBAT_EVENT_FIGHTSUMMARY](nil, { starttime = 146000, endtime = 160000, activetime = 14 })
assert(window.labels[2].text == "40.0 %", "Final replay must agree with live clipping")

env.setClock(70)
env.setBuffs("player", {})
env.callbacks[LIBCOMBAT_EVENT_MESSAGES](nil, 170000, LIBCOMBAT_MESSAGE_COMBATSTART)
env.setClock(72)
env.callbacks[LIBCOMBAT_EVENT_EFFECTS_IN](nil, 172000, 1, 123, EFFECT_RESULT_GAINED, 0, 1, 0, 2)
damage(72)
env.setClock(73)
env.callbacks[LIBCOMBAT_EVENT_EFFECTS_IN](nil, 173000, 1, 123, EFFECT_RESULT_FADED, 0, 1, 0, 2)
damage(74)
assert(window.labels[2].text == "50.0 %")
env.setClock(76)
env.callbacks[LIBCOMBAT_EVENT_DAMAGE_OUT](nil, 171000)
env.events.tick()
assert(window.labels[2].text == "33.3 %", "Delayed first damage must correct the start without rewinding the end")
print("Prebuff expiry: missing fade, expired snapshot, reapplication gap and final replay passed")
