-- SnipersFriendState.lua: Pure data initialization (defaults + runtime state)

local SnipersFriendState = {}

---@return SnipersFriendSavedVars
function SnipersFriendState.Defaults()
    return {
        reticle = {
            enabled = true,
            style = "dot_medium",
            size = 32,
            color = { r = 1, g = 1, b = 1, a = 1 },
            hostileColor = { r = 1, g = 0.25, b = 0.25, a = 1 },
            hostileTint = true,
            hitFlash = true,
            offsetY = 0,
        },
        camera = {
            applyOnLoad = true,
            synced = false,
            sensitivityX = 0.85,
            sensitivityY = 0.85,
            sensitivityFirstPersonX = 0.72,
            sensitivityFirstPersonY = 0.72,
            syncFirstPerson = false,
            distance = 2.5,
            distanceSheathed = 2.5,
            distanceSiege = 6.0,
            syncDistances = true,
            lockDistance = false,
            height = 0,
            horizontalOffset = 0,
            fov = 50,
            unlockNativeSliders = true,
            limits = {
                sensitivityMax = 3.00,
                distanceMax = 12.00,
                heightMin = -0.30, -- native bounds; raise in the addon menu if wanted
                heightMax = 0.50,
                offsetMax = 3.00,
                fovMin = 20,
                fovMax = 110,
            },
        },
        groundTarget = {
            enabled = true,
            okColor = { r = 0.35, g = 1, b = 0.35, a = 1 },
            rangeColor = { r = 1, g = 0.2, b = 0.2, a = 1 },
            losColor = { r = 1, g = 0.6, b = 0.1, a = 1 },
            invalidColor = { r = 0.6, g = 0.6, b = 0.6, a = 1 },
            dwellFade = true,
            dwellMs = 400,
            showLabel = true,
            labelOffsetY = 12,
            rangeText = "OUT OF RANGE",
            losText = "NO LINE OF SIGHT",
            invalidText = "INVALID TARGET",
            debugLog = false,
        },
        aimLine = {
            enabled = true,
            depthTest = true,
            lineWidthM = 0.15,
            lineColor = { r = 0.3, g = 0.9, b = 1, a = 0.75 },
            showTicks = true,
            tickIntervalM = 5,
            majorTickEvery = 2,
            tickWidthM = 0.6,
            tickThicknessM = 0.08,
            tickColor = { r = 1, g = 1, b = 1, a = 0.9 },
            showCap = true,
            capSizeM = 0.6,
            capColor = { r = 1, g = 0.3, b = 0.3, a = 0.9 },
            showWithoutGroundAbility = false,
            fallbackRangeM = 28,
            rangeOverrideM = 0,
            orientMode = "euler",
            debugDump = false,
            showGround = true,
            groundSizeM = 1.2,
            groundColor = { r = 0.3, g = 1, b = 0.4, a = 0.8 },
            groundFarColor = { r = 1, g = 0.3, b = 0.3, a = 0.8 },
        },
        debug = false,
    }
end

---@return SnipersFriendState
function SnipersFriendState.Create()
    return {
        savedVars = SnipersFriendState.Defaults(),
        dotControl = nil,
        nativeReticle = nil,
        nativeReticleAlpha = nil,
        hitTimeline = nil,
        hitAnimation = nil,
        hooksInstalled = false,
        isHostile = false,
        lockTimerRegistered = false,
        settingsPanel = nil,
        nativeRanges = {},
        canQueryHostile = false,
        distanceInjected = false,
        gtReady = false,
        gtState = "idle",
        gtLastError = nil,
        gtStateSince = 0,
        gtOverriding = false,
        gtLabel = nil,
        gtAbilities = {},
        gtLastUsedSlot = nil,
        gtLog = {},
        aimLineReady = false,
        aimLineVisible = false,
        aimLineRangeM = nil,
        aimLineTL = nil,
        cameraProbe = nil,
        aimLine = nil,
        aimLineCap = nil,
        aimLineDebug = nil,
        aimTicks = {},
        aimTickCount = 0,
        aimGround = nil,
        aimGroundDistM = nil,
    }
end

SnipersFriend.State = SnipersFriendState
