-- Explicit HUD allowlist. Never enumerate arbitrary UI controls.
local MH = MovableHUD
MH.nativeTargets = {}
MH.nativeOrder = {}
local function Add(key, label, names)
    MH.nativeTargets[key] = { label = label, names = names }
    MH.nativeOrder[#MH.nativeOrder + 1] = key
    MH.targetOrder[#MH.targetOrder + 1] = key
end
Add("golden", "Golden Pursuits / Tamriel Tomes / Endeavors", {"ZO_TimedActivityTracker_TL", "ZO_PromotionalEventTracker_TL"})
Add("achievement", "Achievement Tracker", {"ZO_AchievementTracker_TL"})
Add("activityqueue", "Activity Finder Queue Status", {"ZO_ActivityTracker"})
Add("activityready", "Activity Finder Ready-Check Progress", {"ZO_ReadyCheckTrackerTopLevel"})
Add("activitydialog", "Activity Finder Accept / Decline Dialog", {})
MH.nativeTargets.activitydialog.unavailable = "Dialog movement is unavailable to avoid interfering with ESO's shared installer dialogs. Your saved position is retained. Queue status and ready-check progress can still be moved."
Add("compass", "Compass", {"ZO_CompassFrame"})
Add("actionbar", "Action Bar", {"ZO_ActionBar1"})
Add("health", "Health", {"ZO_PlayerAttributeHealth"})
Add("magicka", "Magicka", {"ZO_PlayerAttributeMagicka"})
Add("stamina", "Stamina", {"ZO_PlayerAttributeStamina"})
Add("mount", "Mount Stamina", {"ZO_PlayerAttributeMountStamina"})
Add("werewolf", "Werewolf Timer", {"ZO_PlayerAttributeWerewolf"})
Add("siegehealth", "Siege Health", {"ZO_PlayerAttributeSiegeHealth"})
Add("target", "Target Health and Name", {"ZO_TargetUnitFramereticleover"})
Add("boss", "Boss Health", {"ZO_BossBarHealth"})
Add("bossleft", "Boss Bar Left Bracket", {"ZO_BossBarBracketLeft"})
Add("bossright", "Boss Bar Right Bracket", {"ZO_BossBarBracketRight"})
Add("performance", "Performance Meters (when available)", {"ZO_PerformanceMeters"})
Add("playerbuffs", "Player Buffs and Debuffs", {"ZO_BuffDebuffTopLevelSelfContainer"})
Add("targetbuffs", "Target Buffs and Debuffs", {"ZO_BuffDebuffTopLevelTargetContainer"})
Add("combattips", "Combat Tips", {"ZO_ActiveCombatTipsTip"})
Add("reticle", "Reticle", {"ZO_ReticleContainerReticle"})
Add("stealth", "Stealth Indicator", {"ZO_ReticleContainerStealthIcon"})
Add("interact", "Interaction Prompt", {"ZO_ReticleContainerInteract"})
Add("noninteract", "Non-interaction Text", {"ZO_ReticleContainerNonInteract"})
Add("synergy", "Synergy Prompt", {"ZO_SynergyTopLevelContainer"})
Add("playerprompt", "Player Interaction / Ready-Check HUD Prompt", {"ZO_PlayerToPlayerAreaPromptContainer"})
Add("resurrect", "Resurrection Progress", {"ZO_PlayerToPlayerResurrectProgress"})
Add("objective", "Objective Capture Meter", {"ZO_ObjectiveCaptureMeter"})
Add("battleground", "Battleground Score and Objectives", {"ZO_BattlegroundHUDFragmentTopLevelBattlegroundScoreHud"})
Add("bgkey", "Battleground Scoreboard Keybind", {"ZO_BattlegroundHUDFragmentTopLevelKeybindButton"})
Add("raidlife", "Trial Lives", {"ZO_HUDRaidLife"})
Add("death", "Death / Respawn Prompts", {"ZO_Death"})
Add("ram", "Battering Ram", {"ZO_RamTopLevel"})
Add("infamy", "Bounty and Infamy", {"ZO_HUDInfamyMeter"})
Add("telvar", "Tel Var Meter", {"ZO_HUDTelvarMeter"})
Add("daedric", "Daedric Energy Meter", {"ZO_HUDDaedricEnergyMeterTopLevel"})
Add("equipment", "Equipment Status", {"ZO_HUDEquipmentStatus"})
Add("loot", "Loot History", {"ZO_LootHistoryControl_Gamepad"})
Add("subtitles", "Subtitles", {"ZO_Subtitles"})
Add("alerts", "Alert Text", {"ZO_AlertTextNotificationGamepad"})
Add("notifications", "Notification Icons", {"ZO_NotificationIcons_Console"})
Add("voice", "Voice Chat HUD", {"ZO_VoiceChatHUDGamepad"})
Add("announcements", "Center-Screen Announcements", {"ZO_CenterScreenAnnounce"})
Add("kickalive", "Instance Kick Warning", {"ZO_InstanceKickWarning_Alive"})
Add("kickdead", "Instance Kick Warning While Dead", {"ZO_InstanceKickWarning_Dead"})
Add("adventure", "Adventure Zone Tracker", {"ZO_AdvZoneHUDTracker"})
Add("adventurescore", "Adventure Zone Score", {"ZO_AdvZoneHUD_TopLevelPlayerScoreContainer"})
Add("dynamic", "Dynamic Events Tracker", {"ZO_DynamicEventsTracker_TL"})
Add("house", "House Information Tracker", {"ZO_HouseInformationTrackerTopLevel"})
Add("archive", "Infinite Archive / Night Market Tracker", {"ZO_EndDunHUDTracker"})
Add("archivescore", "Infinite Archive Score and Lives", {"ZO_EndlessDungeonHUD_TopLevelScoreContainer"})
Add("archivebuffs", "Infinite Archive Buff Tracker", {"ZO_EndDunBuffTracker_Gamepad"})
Add("zonestory", "Zone Story Tracker", {"ZO_ZoneStoryTracker"})
Add("selector", "Event Selection Tracker", {"ZO_GenSelectHUDTracker"})
