-- SetHunter_Strings.lua : every UI text the addon shows. S.L("KEY", ...)
-- returns the text, formatted. Only English for now; add S.STRINGS.de / fr / es
-- with the same keys to translate (missing keys fall back to English).

SetHunter = SetHunter or {}
local S = SetHunter

S.STRINGS = {}

S.STRINGS.en = {
    PREFIX = "[Set Hunter]",
    TITLE = "Set Hunter",
    SUBTITLE = "FARM  ·  COLLECT  ·  COMPLETE",
    LAUNCHER = "Set Hunter",
    LAUNCHER_TT = "Click: open / minimize\nDrag: move\nRight-click: options",
    LAUNCHER_HIDE_TT = "Hide this button (/sethunter brings it back)",
    LAUNCHER_COLLAPSE = "Hide name",
    LAUNCHER_EXPAND = "Show name",
    LAUNCHER_HIDDEN = "Button hidden. Type /sethunter to show it again.",
    MINIMIZE = "Minimize",
    BIND_TOGGLE = "Toggle Set Hunter",

    -- Left side
    SEARCH = "Search sets...",
    MISSING_ONLY = "Missing only",
    MISSING_ONLY_TT = "Hide sets you've already fully collected.",
    ANNOUNCE = "Wishlist alerts",
    ANNOUNCE_TT = "When you enter a zone, dungeon or trial, say in chat which wishlist sets drop there.",

    TREE_SETS = "SETS",
    TREE_ITEMS = "MY ITEMS",
    TREE_XP = "XP FARMING",

    -- Header of the right side
    BADGE_PLAYERS = "%d players",
    BADGE_NORMAL_VET = "Normal + Veteran",
    BADGE_DLC = "DLC",
    BADGE_DLC_MISSING = "DLC not owned",
    BADGE_PLACE = "1 place",
    BADGE_PLACES = "%d places",
    BADGE_SET = "1 set",
    BADGE_SETS = "%d sets",
    BADGE_SPOTS = "%d spots",
    BADGE_MAX_XP = "Up to +290% XP",
    BADGE_PIECE = "1 piece",
    BADGE_PIECES = "%d pieces",
    BADGE_CHAR = "1 character scanned",
    BADGE_CHARS_OF = "Bags of %d of %d characters",
    CHARS_SUM_ALL = "All %d characters are in the list",
    CHARS_SUM_SOME = "%d of %d characters are in the list",
    CHARS_OLDEST = "Oldest: %s, %s",
    CHARS_LOG_IN = "log in once",
    CHARS_PANEL_NOTE = "Your bank and house storage are always included. A character is added the first time you log in on it, and updated every time you do.",
    BADGE_CHARS = "%d characters scanned",
    LINE_HEAD = "Head: %s  —  %s",
    LINE_HEAD_FROM = "%s (Veteran)",
    LINE_SHOULDERS = "Shoulders: %s",
    UNDAUNTED_KEYS = "Undaunted keys",
    MONSTER_INFO_HEAD = "Head: from the dungeon's last boss, Veteran only",
    WISHLIST_INFO = "Everything on your wishlist: whole sets, and sets where you only want certain pieces. Open Wishlist on the left to see them apart.",
    WISHLIST_PROGRESS = "Wishlist complete",
    COLLECTION_HERE = "Collection here",
    PROGRESS_VALUE = "%d of %d sets",
    HOW_DROPS = "How drops work",
    NAV_BACK = "Back",
    NAV_FORWARD = "Forward",
    SELECTED = "Selected:",
    COL_SET = "SET",
    COL_TYPE = "TYPE",
    COL_OWNED = "OWNED",
    COL_COLLECTED = "COLLECTED",
    COL_DROPS = "DROPS IN",
    COL_ITEM = "ITEM",
    COL_TRAIT = "TRAIT",
    COL_WHERE = "WHERE",
    COL_SOURCE = "SOURCE",
    PILL_DUNGEON = "Dungeon",
    PILL_TRIAL = "Trial",
    PILL_ARENA = "Arena",
    PILL_OVERLAND = "Overland",
    PILL_PVP = "PvP",
    PILL_MYTHIC = "Mythic",
    PILL_MONSTER = "Monster",
    PILL_CRAFTED = "Crafted",
    PILL_OTHER = "Special",
    GRP_GOALS = "Your goals",
    GRP_BROWSE = "Browse",
    GRP_PROGRESS = "Progress",
    GRP_PIECES = "Your pieces",
    GRP_SORTED = "Sorted by",
    GRP_CLEANUP = "Clean up",
    GRP_XP_FARM = "Where to farm",
    GRP_XP_GEAR = "Boosts and setup",
    GRP_XP_TRACK = "Your progress",
    CAT_HERE = "Current location",
    CAT_WISHLIST = "Wishlist",
    CAT_ITEMS = "My items",
    CAT_ITEMS_NEW = "Not in collection yet",
    CAT_ITEMS_DECON = "Safe to deconstruct",
    CAT_ITEMS_TRAIT = "By trait",
    CAT_ITEMS_DUPES = "Duplicates",
    CAT_ITEMS_TRADE = "Tradeable",
    CAT_ITEMS_LOW = "Below max level",
    CAT_ITEMS_SLOT = "By slot",
    CAT_ITEMS_QUALITY = "By quality",
    CAT_ITEMS_WEIGHT = "By gear type",
    CAT_ITEMS_SETTYPE = "By set type",
    KIND_CRAFTED = "Crafted",
    ITEMS_DUPES_INFO = "Pieces you have more than once: the same set, slot and trait. Keep the best one (quality, level) and clear out the rest.",
    EMPTY_ITEMS_DUPES = "No duplicates: every piece you own is one of a kind.",
    ITEMS_TRADE_INFO = "Pieces that aren't bound yet: you can sell them in a guild store, trade them or mail them to someone. Binding one adds it to your Set Collection, but then it can't be traded anymore.",
    EMPTY_ITEMS_TRADE = "All your pieces are bound.",
    ITEMS_LOW_INFO = "Pieces below CP 160, the level where gear stops getting stronger. Usually old leveling gear: replace them, or deconstruct them once they're in your Set Collection.",
    EMPTY_ITEMS_LOW = "All your pieces are max level (CP 160).",
    ITEMS_SLOT_INFO = "Your pieces by where they go: head, chest, rings, each weapon type... Pick a slot on the left.",
    ITEMS_QUALITY_INFO = "Your pieces by quality, best first. Pick one on the left; gold (Legendary) pieces took the most materials to upgrade.",
    ITEMS_WEIGHT_INFO = "Your pieces by gear type: Light, Medium or Heavy armor, jewelry and weapons. Pick one on the left.",
    ITEMS_SETTYPE_INFO = "Your pieces by where their set comes from: dungeons, trials, overland zones, crafted, monster, mythic... Pick one on the left.",
    ITEMS_WISH_INFO = "The pieces you own from your wishlist sets. For sets where you picked single pieces, only those pieces show. Traits you're hunting show in green.",
    EMPTY_ITEMS_WISH = "You don't own any pieces from your wishlist sets yet.",
    ITEMS_TRAIT_INFO = "Your pieces in each trait, on all characters, in the bank and in house storage. Pick a trait on the left. Traits you're hunting (Sets > Trait hunt) show in green.",
    CAT_WISH_PLACES = "By place",
    WISH_PLACES_INFO = "Where your wishes drop, the place with the most first, so you can plan where to farm. Use the icon at the end of a place to travel or queue there. A set that drops in several places is listed under each.",
    EMPTY_WISH_PLACES = "Nothing to farm right now.\nClick the star next to a set to add it to your wishlist.",
    WISH_PLACE_ONE = "1 wished set",
    WISH_PLACE_MANY = "%d wished sets",
    WISH_PLACE_TT = "Your open wishes that drop here. Click the icon at the end of the row to travel or queue.",
    BADGE_PLACE = "1 place",
    BADGE_PLACES = "%d places",
    CAT_WISH_DONE = "Completed",
    WISH_DONE_INFO = "You've collected everything you wanted from these sets. Click the %s to take a set off your wishlist.",
    EMPTY_WISH_DONE = "Nothing completed yet.",
    CAT_WISH_WHOLE = "Whole sets",
    WISH_WHOLE_INFO = "Sets you want complete, and where they drop.",
    EMPTY_WISH_WHOLE = "No whole sets on your wishlist.\nClick the star next to a set to add it.",
    PROGRESS_PIECES = "%d of %d pieces",
    CAT_WISH_PIECES = "Wanted pieces",
    WISH_PIECES_INFO = "Sets where you only want certain pieces, with those pieces listed underneath. Right-click a set > Wanted pieces... to change them.",
    WISH_PIECES_PROGRESS = "Pieces collected",
    EMPTY_WISH_PIECES = "You haven't picked any single pieces yet.\nRight-click any set > Wanted pieces... and click the pieces you want (Head, Chest...).",
    CAT_HUNT = "Trait hunt",
    CAT_OVERVIEW = "Collection overview",
    OVERVIEW_INFO = "How far your Set Collection is, per category. Click a category's icon (or double-click the row) to open it.",
    OVERVIEW_PROGRESS = "Sets complete",
    OVERVIEW_PIECES = "%s / %s pieces",
    OVERVIEW_TT = "%d of %d sets complete, %s of %s pieces collected. Click the icon to open it.",
    BADGE_PIECES_OF = "%s / %s pieces collected",
    COL_CATEGORY = "CATEGORY",
    COL_PIECES = "PIECES",
    COL_SETS_DONE = "SETS COMPLETE",
    CAT_ALMOST = "Almost complete",
    ALMOST_INFO = "Sets you're only 1 to 3 pieces away from finishing, closest first. Hover a set to see which pieces you still need.",
    ALMOST_HDR_ONE = "1 piece to go",
    ALMOST_HDR = "%d pieces to go",
    EMPTY_ALMOST = "No sets are 1 to 3 pieces from done right now.",
    CAT_RECENT = "Recently collected",
    RECENT_INFO = "Pieces added to your Set Collection, newest first (the last 100). Set Hunter keeps this list from the moment it was installed.",
    RECENT_TT = "%s  ·  collected in %s",
    EMPTY_RECENT = "Nothing yet. Pieces you add to your Set Collection from now on show up here.",
    CAT_CRAFTED = "Crafted sets",
    CRAFTED_INFO = "Sets you make yourself at a set crafting station, grouped by how many researched traits they need. \"You can craft\" is for this character: traits are researched per character.",
    RULE_CRAFTED = "Go to the set's crafting station (the zone under STATION IN). You can make a piece once this character has researched enough traits for that item type. Research traits at any crafting station, one trait per item type at a time. Crafted sets aren't part of the Set Collection: you can make them again whenever you like.",
    CRAFT_HDR = "%d traits needed",
    CRAFT_ALL = "you can craft every piece",
    CRAFT_SOME = "you can craft %d of %d item types",
    BADGE_CRAFTABLE = "%d fully craftable",
    COL_STATION = "STATION IN",
    TT_CRAFT_NEED = "Crafted set: needs %d researched traits on the item",
    TT_CRAFT_ALL = "This character can craft every piece.",
    TT_CRAFT_MISSING = "Not enough traits yet (this character): %s",
    HUNT_INFO = "Sets you want in specific traits. Under each trait: the pieces you already have in it, on any character or in the bank. Right-click a set > Hunt traits... to change them.",
    EMPTY_HUNT = "You're not hunting any traits yet.\nRight-click any set > Hunt traits... and click the traits you want.",
    HUNT_HAVE = "You have %d",
    HUNT_NONE = "None yet",
    BADGE_HUNT_FOUND = "%d of %d traits found",
    HUNT_TRAIT_TT = "You're hunting %s pieces of %s. Right-click to change the traits.",
    ITEMS_FOR = "My items: %s",
    CAT_DUNGEON = "Dungeons",
    CAT_TRIAL = "Trials",
    CAT_ARENA = "Arenas",
    CAT_OVERLAND = "Overland zones",
    CAT_PVP = "PvP",
    CAT_OTHER = "Other sources",
    CAT_MONSTER = "Monster helms",
    CAT_XP_SPOTS = "Grind spots",
    CAT_XP_BOOSTS = "XP boosts",
    CAT_XP_SETUP = "Leveling setup",
    CAT_XP_SESSION = "This session",
    CAT_XP_DAILY = "Daily bonuses",
    XP_LABEL_LEVEL = "Level %d",
    XP_LABEL_CP = "CP %s",
    XP_TO_NEXT_LEVEL = "%d%% to level %d",
    XP_TO_NEXT_CP = "%d%% to next CP",
    DURATION_HM = "%d h %d min",
    DURATION_M = "%d min",
    DURATION_LT_MIN = "less than a minute",
    SESSION_INFO = "XP you've earned since you logged in on this character. A /reloadui or a short break keeps counting; after 15 minutes away a new session starts.",
    SESSION_RULES = "XP per hour is everything you earned this session divided by the time played. Try a grind spot for 15 minutes and compare the numbers to find your fastest one.",
    SESSION_TIME = "Time played",
    SESSION_XP = "XP earned",
    SESSION_RATE = "XP per hour",
    SESSION_RATE_VALUE = "%s / h",
    SESSION_LEVELS = "Levels gained",
    SESSION_CP = "Champion points gained",
    SESSION_NEXT_LEVEL = "Next level in",
    SESSION_NEXT_CP = "Next champion point in",
    SESSION_ABOUT = "about %s",
    SESSION_NO_XP_YET = "earn some XP first",
    SESSION_BUFF = "XP buff",
    SESSION_BUFF_LEFT = "%s  ·  %s left",
    SESSION_NO_BUFF = "none active",
    SESSION_BUFF_TT = "Experience Scrolls, Ambrosia and event boosts show here while they're active.",
    MENU_XP_RESET = "Start a new session",
    XP_RESET_TT = "Set the time and XP back to zero, for example before you try a new grind spot.",
    DAILY_INFO = "Once a day, the first time you finish one of these gives a big reward, with lots of XP. Straight from the Group Finder.",
    DAILY_RULES = "The daily reward resets once a day for your whole account. Queue for it in the Group Finder (P); the icon at the end of a row takes you there.",
    DAILY_OPEN = "Not done today",
    DAILY_DONE = "Done today",
    DAILY_XP = "+%s XP",
    DAILY_BADGE = "%d still open today",
    DAILY_TT_OPEN = "Today's reward for this is still waiting for you.",
    DAILY_TT_DONE = "You already got today's reward for this. It comes back after the daily reset.",
    DAILY_NONE = "The Group Finder has no daily rewards to show right now.",
    STATUS_BUFF_LEFT = "Active, %s left",
    SEARCH_RESULTS = "Search results",

    COUNT = "%d",

    -- Set types
    TYPE_LIGHT = "Light",
    TYPE_MEDIUM = "Medium",
    TYPE_HEAVY = "Heavy",
    TYPE_MIXED = "All weights",
    TYPE_JEWELRY = "Jewelry",
    TYPE_WEAPON = "Weapons",
    TYPE_MONSTER = "Monster",
    TYPE_MYTHIC = "Mythic",
    TYPE_CRAFTED = "Crafted, %d traits",
    COLLECTED = "%d / %d",
    COMPLETE = "Complete",
    OWNED = "%d owned",
    NOT_COLLECTED = "Uncollected",
    NO_TRAIT = "No trait",
    LEVEL = "Level",

    -- My items
    WHERE_WORN = "%s (worn)",
    WHERE_BACKPACK = "%s (backpack)",
    WHERE_BANK = "Bank",
    WHERE_BANK_PLUS = "Bank (ESO Plus)",
    WHERE_HOUSE = "House storage",
    WHERE_CHEST = "%s · %s",
    HOW_BANK = "Your bank is shared by all your characters: open it at any banker in any city (or with a banker assistant).",
    HOW_BANK_PLUS = "In the extra ESO Plus bank space: open it at any banker in any city while you have ESO Plus.",
    HOW_THIS_CHAR = "On this character.",
    HOW_OTHER_CHAR = "On %s: log in on that character, or have them put it in the bank.",
    HOW_CHEST = "In your house %s, in the storage chest \"%s\".",
    HOW_CHEST_NO_HOUSE = "In the storage chest \"%s\" in one of your houses.",
    TT_UPDATED = "Last checked: %s",
    BANKER_SUMMON = "Summon your bank assistant %s",
    BANKER_SUMMON_ANY = "Summon one of your bank assistants",
    BANKER_CLICK_ONE = "Click to summon",
    BANKER_CLICK_MANY = "Click to choose which one to call.",
    BANKER_MENU = "Summon %s",
    BANKER_COOLDOWN = "%s can be summoned again in %d seconds.",
    BANK_LINK_SUMMON = "Summon %s",
    BANK_LINK_ANY = "Summon a banker",
    BANK_LINK_NEAREST = "Nearest bank",
    BANK_PICK_ONE = "Your bank assistant",
    BANK_PICK_MANY = "Your bank assistants",
    BANK_BTN = "Bank",
    BANK_NONE_TITLE = "You don't have a bank assistant",
    BANK_NONE_DIR = "The nearest bank is to the %s of you.",
    BANK_NONE_HERE = "There's a bank right next to you.",
    BANK_NONE_NODIR = "There's no bank on this map. Go to a city to reach a banker.",
    BANK_NONE_MAP = "Look for %s on your map.",
    DIR_N = "north",
    DIR_NE = "north-east",
    DIR_E = "east",
    DIR_SE = "south-east",
    DIR_S = "south",
    DIR_SW = "south-west",
    DIR_W = "west",
    DIR_NW = "north-west",
    AGO_NOW = "just now",
    AGO_MIN = "%d min ago",
    AGO_HOUR = "%d h ago",
    AGO_DAY = "%d days ago",
    AGO_DAY_ONE = "1 day ago",
    MENU_KEEP_BEST_ONE = "Keep the best, mark the other copy for deconstruction",
    MENU_KEEP_BEST = "Keep the best, mark the other %d for deconstruction",
    KEEP_DONE = "Kept %s (%s). Marked %d other copies for deconstruction in FCO ItemSaver.",
    KEEP_SKIP_PROTECTED = "%d worn or locked copies were left alone.",
    KEEP_SKIP_UNREAD = "%d copies couldn't be marked yet: log in on that character (or open the bank) once.",
    KEEP_SKIP_SHARED = "%d identical copies share one FCO ItemSaver mark with the kept one, so they were left alone. Turn on unique IDs in FCO ItemSaver's settings to mark them apart.",
    SEARCH_COUNT_ONE = "1 result",
    SEARCH_COUNT = "%d results",
    SEARCH_CLEAR = "Clear the search",
    QUALITY_MYTHIC = "Mythic",
    QUALITY_OTHER = "Quality %d",
    -- Set Hunter lines in the game's item tooltips (bag, bank, worn, loot)
    TTL_WISH = "On your wishlist",
    TTL_WISH_PIECE = "A wanted piece on your wishlist",
    TTL_HUNT_TRAIT = "A trait you're hunting",
    TTL_NOT_COLLECTED = "Not in your Set Collection yet",
    TTL_DUPE_ONE = "You own 1 more of this: %s",
    TTL_DUPES = "You own %d more of this: %s",
    TTL_MORE = "+%d more",
    SET_TOOLTIP_LINES = "Set Hunter lines in item tooltips",
    SET_TOOLTIP_LINES_TT = "Adds a few lines to the game's item tooltips (bag, bank, worn gear, crafting, loot): on your wishlist, a trait you hunt, not in your Set Collection yet, and how many more copies you own and where.",
    ITEMS_INFO = "Every set item you own, on all characters, in the bank and in your house storage. Pick a character in the list above to see only theirs.",
    SCOPE_ALL = "All characters",
    SCOPE_BANK = "Bank",
    SCOPE_HOUSE = "House storage",
    SCOPE_NOT_SCANNED = "%s (log in once)",
    SCOPE_HDR_CHARS = "Characters",
    SCOPE_HDR_STORAGE = "Storage",
    SCOPE_NOT_READ = "not read yet",
    SCOPE_SEARCH = "Find a character...",
    SCOPE_TT = "Whose items to show: all characters, one character, the bank or house storage. The number is how many set pieces are there.",
    EMPTY_CHAR_NOT_SCANNED = "Set Hunter hasn't seen %s's bags yet.\nLog in on that character once to add their items.",
    ITEMS_RULES = "Log in on each character once so the addon can see their bags.\nTo include your house chests, visit your house once.\n\n\"1 / 22\" means you have unlocked 1 of the 22 pieces of that set in your Set Collection.\n\"Owned\" means pieces you have right now, in your bags, bank or house.",
    ITEMS_NEW_INFO = "Pieces you own that aren't in your Set Collection yet. Unbound (Bind on Equip) pieces unlock once you bind them: right-click the item in your inventory > Bind.",
    EMPTY_ITEMS = "No set items found yet.\nOpen your bank once, and log in on your other characters.",
    EMPTY_ITEMS_NEW = "Everything you own is already in your Set Collection.",
    ITEMS_DECON_INFO = "Bound pieces that are already in your Set Collection, so you can always get them back by reconstructing (Transmute Crystals). Worn gear and traits you're hunting are left out. Check it isn't gear you still use on another build.",
    EMPTY_ITEMS_DECON = "Nothing to clear out right now.",

    -- Location info panel
    INFO_DUNGEON = "Group dungeon  ·  4 players",
    INFO_TRIAL = "Trial  ·  12 players",
    INFO_ARENA_SOLO = "Solo arena",
    INFO_ARENA_GROUP = "Group arena  ·  4 players",
    INFO_ARENA_SOLODUO = "Solo or duo",
    INFO_ARENA = "Arena",
    INFO_OVERLAND = "Overland zone",
    INFO_PVP = "PvP",
    INFO_OTHER = "Special reward source",
    DLC_REQUIRED = "DLC required",

    RULE_DUNGEON = "Sets drop from every boss and from treasure chests; Veteran bosses drop more. Weapons and jewelry come from bosses.",
    RULE_TRIAL = "Trial sets drop from the bosses (Perfected versions on Veteran). The weekly trial quest adds a reward coffer with extra gear.",
    RULE_ARENA = "Gear drops from the stage bosses and the final reward. Veteran gives the Perfected arena weapons.",
    RULE_OVERLAND = "Drops from enemies, chests, delve and public dungeon bosses, world bosses, dolmens/geysers and zone daily reward boxes.",
    RULE_PVP = "From PvP rewards: Rewards for the Worthy mail, Alliance Point / Tel Var vendors, keeps and Battlegrounds.",
    RULE_OTHER = "Comes from a reward system instead of one place.",

    -- Other sources: what each reward system is and how you get its sets
    SRC_INFO_ANTIQUITIES = "Mythic items, dug up with the Antiquities system. The number next to \"Mythic\" is how many of its fragments you've found; hover a set to see every fragment, the zone its lead is in, and whether you have that lead. Click the \"Mythic\" tag at the end of a row to open your Antiquities journal.",
    SRC_RULE_ANTIQUITIES = "Each mythic is made of several fragments, and every fragment needs its own lead. Leads drop from things in their zone, such as bosses, treasure chests, dolmens, delves and fishing. With a lead: travel to its zone, scry to find the dig site, then excavate it. Harder leads need a higher Scrying and Excavation skill. Once you've found every fragment, the mythic is yours.",
    SRC_INFO_BATTLEGROUNDS = "Sets from Battlegrounds, the team PvP matches you queue for in the Group Finder.",
    SRC_RULE_BATTLEGROUNDS = "Pieces come from Battlegrounds match rewards, and the Battlegrounds merchants sell them for Alliance Points.",
    SRC_INFO_RANDOM = "Sets from the reward for finishing a Random Dungeon from the Group Finder.",
    SRC_RULE_RANDOM = "Queue for a Random Normal or Random Veteran Dungeon in the Group Finder. The reward you get for finishing it can hold these pieces; the first random dungeon each day gives the biggest reward.",
    SRC_INFO_WORTHY = "Sets from Rewards for the Worthy: reward coffers mailed to you for earning Alliance Points in PvP.",
    SRC_RULE_WORTHY = "Earn Alliance Points in Cyrodiil, Imperial City or Battlegrounds. Every time the Rewards for the Worthy bar fills up, a coffer with gear from these sets arrives in your mail.",
    RULE_MONSTER = "Head: guaranteed from the listed boss on Veteran. Shoulders: Undaunted keys at the Pledge Masters, and Undaunted chests. DLC monster sets can also be bought in the Crown Store.",

    MONSTER_LINE = "Monster helm: %s  —  %s (final boss, Veteran)",
    SHOULDER_LINE = "Monster shoulders: Undaunted keys",
    PROGRESS_LINE = "Your collection here: %d of %d sets complete",
    HERE_TITLE = "Here: %s",
    HERE_NONE = "No set drops known for this location.",

    NO_LIB = "Install LibItemSets to see every set and where it drops. Monster helms and the XP guide work without it.",
    EMPTY_WISHLIST = "Your wishlist is empty.\nClick the star next to a set to add it.",
    EMPTY_SEARCH = "Nothing found.",
    EMPTY = "Nothing here.",

    -- Bottom buttons, right-click menu
    BTN_WISH = "Add to wishlist",
    BTN_UNWISH = "Remove from wishlist",
    BTN_LINK = "Link in chat",
    BTN_TRAVEL = "Travel there",
    BTN_QUEUE = "Queue dungeon",
    MENU_GOTO = "Show where it drops",
    MENU_GOTO_AT = "Go to %s",
    -- right-click menu sections
    RM_WISHLIST = "Wishlist",
    RM_FIND = "Find it",
    RM_PIECE = "This piece",
    RM_FCO = "FCO ItemSaver marks",
    RM_SET_SUB = "%d of %d pieces collected",
    MENU_MY_PIECES = "Show my pieces (%d)",
    MENU_QUEUE = "Queue for this dungeon...",
    CANCEL = "Cancel",
    CLOSE = "Close",
    MENU_SUMMARY_ON = "Run summary: on",
    MENU_SUMMARY_OFF = "Run summary: off",

    -- Run summary
    RUN_COMPLETE = "Run complete",
    RUN_ENDED = "Run ended",
    RUN_PIECES = "set pieces",
    RUN_NEW = "new to collection",
    RUN_TODAY = "runs today",
    RUN_SET_LINE = "%s: %d / %d collected",
    RUN_GAINED = "+%d this run",
    RUN_NOT_THIS_TIME = "not this time",
    RUN_COLLECTION_HERE = "Collection here: %d of %d sets complete",
    RUN_NEW_TAG = "NEW",
    RUN_NO_LOOT = "No set pieces this run.",
    RUN_AGAIN = "Queue again",
    RUN_SEE_LOOT = "See loot",
    RUN_HIDE_LOOT = "Hide loot",
    TT_MORE_SHORT = "... and %d more",

    -- Dungeon queue
    NORMAL = "Normal",
    VETERAN = "Veteran",
    ROLE_DPS = "Damage",
    ROLE_HEAL = "Healer",
    ROLE_TANK = "Tank",
    QUEUE_DIFFICULTY = "Difficulty",
    QUEUE_ROLE = "Your role",
    QUEUE_FOR = "Farming: %s  (%s)",
    QUEUE_REQ_LEVEL = "Requires level %d",
    QUEUE_REQ_CP = "Requires CP %d",
    QUEUE_REQ_OK = "—  Requirements met",
    QUEUE_REQ_NO = "—  Requirements not met",
    QUEUE_NO_VET = "This difficulty isn't available for this dungeon.",
    QUEUE_NO_DLC = "DLC not owned: %s. Buy it in the Crown Store or get ESO Plus to play this dungeon.",
    QUEUE_MONSTER_VET = "Monster helms only drop on Veteran.",
    QUEUE_IN_QUEUE = "You're in the queue right now.",
    QUEUE_NOT_LEADER = "You're in a group: only the group leader can queue.",
    BTN_START_QUEUE = "Queue",
    BTN_LEAVE_QUEUE = "Leave queue",
    QUEUED = "Queued for %s (%s) as %s.",
    QUEUE_NONE = "%s (%s) can't be queued from the Activity Finder.",
    QUEUE_ALREADY = "You're already in the queue. Leave it first to queue for another dungeon.",
    QUEUE_FAIL = "Couldn't start the queue. Open the Group Finder (P) to queue manually.",
    MENU_HIDE_BUTTON = "Hide this button",
    MENU_RESET_SIZE = "Reset window size",
    MENU_ANNOUNCE_ON = "Wishlist alerts: on",
    MENU_ANNOUNCE_OFF = "Wishlist alerts: off",
    MENU_SETTINGS = "Settings",

    -- Settings panel
    SET_INFO = "Tip: right-click the Set Hunter button for quick options.",
    SET_HDR_BUTTON = "Button and window",
    SET_BUTTON = "Show the Set Hunter button",
    SET_BUTTON_TT = "The small button at the top left of your screen. You can always open the window with /sethunter or a keybind.",
    SET_COMPACT = "Compact button (only the shield)",
    SET_COMPACT_TT = "Shows just the Set Hunter shield instead of the shield with the name. The small arrow on the button switches it too.",
    SET_COMBAT_HIDE = "Hide the button in combat",
    SET_COMBAT_HIDE_TT = "The Set Hunter button disappears while you fight and comes back afterwards.",
    SET_BAG_BUTTON = "Button in the inventory and bank",
    SET_BAG_BUTTON_TT = "A small Set Hunter shield at the top left of your inventory and bank, that opens Set Hunter on My items.",
    MENU_COMPACT_ON = "Show name",    -- the name is hidden now
    MENU_COMPACT_OFF = "Hide name",
    BAG_BUTTON_TT = "Set Hunter: My items",
    BAG_BUTTON_TT_INFO = "All your set items on every character, the bank and house storage. Click a piece in the list to find it in this bag. Click the shield again to close Set Hunter.",
    SET_RESET_POS = "Reset position",
    SET_RESET_POS_TT = "Put the button and the window back in their starting place.",
    SET_RESET_SIZE = "Reset size",
    SET_RESET_SIZE_TT = "Put the window back to its starting size.",
    SET_BANK_OPEN = "Open next to the bank",
    SET_BANK_OPEN_TT = "When you open your bank, Set Hunter opens on My items. Click a bank piece to jump to it in the bank.",
    SET_HDR_ALERTS = "Alerts",
    SET_DROP = "Alert when a wishlist piece drops",
    SET_DROP_TT = "Shows a message in the middle of your screen when you loot a piece from a set on your wishlist.",
    SET_DROP_SOUND = "Play a sound",
    SET_DROP_NEW = "Only for pieces I haven't collected yet",
    SET_DROP_NEW_TT = "No alert for pieces that are already in your Set Collection.",
    SET_ANNOUNCE = "Tell me in chat what drops where I arrive",
    SET_HDR_LISTS = "Set lists",
    SET_MISSING = "Hide sets I've fully collected",
    SET_HDR_RUNS = "Dungeon runs",
    SET_SUMMARY = "Show the \"Run complete\" window",
    SET_SUMMARY_TT = "After a dungeon: your time, the set pieces you got and how many were new.",
    NO_LAM = "Install LibAddonMenu-2.0 to use the settings panel.",

    -- Wishlist drop alert
    DROP_TITLE = "Wishlist drop!",
    DROP_TITLE_TRAIT = "Hunted trait!",
    DROP_TITLE_PIECE = "Wanted piece!",
    DROP_NEW = "New for your collection",
    DROP_PROGRESS = "%d / %d collected",
    DROP_CHAT = "Wishlist drop: %s",

    -- Travel
    TRAVEL_CONFIRM = "Travel to <<1>>?<<2>>\n\nRecalling costs gold unless you're standing at a wayshrine.",
    NOTE_TRIAL = "Trial: made for a group of 12 players (Normal and Veteran). Find a group in zone chat or your guild before you go.",
    NOTE_GROUP_ARENA = "Group arena: made for a group of 4 players. Find a group before you go.",
    TRAVEL_NONE = "You don't know a wayshrine for %s yet.",
    TRAVEL_COMBAT = "You can't travel while in combat.",
    TC_HDR_SPOTS = "Travel check - XP grind spots:",
    TC_HDR_PLACES = "Travel check - delves, dungeons and other places inside a zone:",
    TC_LINE = "%s › %s (%s)",
    TC_LINE_NONE = "%s › no known wayshrine",
    TC_HOW_ENTRANCE = "its own entrance",
    TC_HOW_ONLY = "the only wayshrine you know there",
    TC_HOW_PLACE = "closest to it",
    TC_HOW_YOU = "closest to you",
    TC_HOW_NEAR = "the wayshrine named for this spot",
    TC_HOW_WORD = "not on your map yet, wayshrine with the same name",
    TC_HOW_FIRST = "place not found on the map, first wayshrine",
    TC_HOW_NOMAP = "map couldn't be read, first wayshrine",
    TC_DONE = "Travel check done: %d place(s) not matched on the map (orange).",

    -- Tooltips
    TT_DROPS = "Drops in: %s",
    TT_HEAD = "Head: %s (Veteran)",
    TT_SHOULDERS = "Shoulders: Undaunted keys",
    TT_MISSING = "Still missing (%d): %s",
    TT_MISSING_ALL = "Still missing: all %d pieces",
    TT_FRAGMENTS = "Fragments: %d / %d found",
    TT_FRAGMENTS_HOW = "Get a fragment's lead, go to its zone, scry and dig it up.",
    FRAG_FOUND = "found",
    FRAG_LEAD = "you have the lead",
    FRAG_NO_LEAD = "no lead yet",
    FRAG_ANY_ZONE = "any zone",
    TT_WANTED_TRAITS = "Hunting traits: %s",
    TT_WANTED_TRAIT = "A trait you're hunting (Sets > Trait hunt)",
    TT_WANTED_PIECES = "Wanted pieces: %s",
    TT_WANTED_PIECE = "A piece on your wishlist",
    MENU_PIECES = "Wanted pieces...",
    MENU_WISH_PIECE = "Add this piece to wishlist",
    MENU_UNWISH_PIECE = "Remove this piece from wishlist",
    MENU_UNWISH_SET = "Remove set from wishlist",
    PIECE_ANY = "Whole set",
    WISH_ADDED = "%s added to your wishlist.",
    WISH_TRAITS_ROW = "Hunting traits",
    WISH_TRAITS_TT = "Drops of %s in these traits get a \"Hunted trait!\" alert; other traits only alert when the piece is new for your collection. Right-click the set > Hunt traits... to change them.",
    PIECE_HAVE = "(have)",
    PIECE_COLLECTED = "Collected",
    PIECE_MISSING = "Not collected yet",
    PIECE_TT = "You wishlisted the %s of %s. Right-click to remove it.",
    MENU_TRAITS = "Hunt traits...",
    TRAIT_ANY = "Clear all",
    DONE = "Done",
    PICK_TRAITS = "Hunt traits: %s",
    PICK_PIECES = "Wanted pieces: %s",
    PICK_TRAITS_NOTE = "Click the traits you're hunting (%s = picked). A drop in one of them gets a \"Hunted trait!\" alert. Your pieces in them show in green, are never marked safe to deconstruct, and are listed under Sets > Trait hunt.",
    PICK_PIECES_NOTE = "Click the pieces you want (%s = picked). A drop of one of them gets a \"Wanted piece!\" alert, and they're listed under the set in your Wishlist.",
    TRAIT_WANTED = "(wanted)",
    TRAITS_ARMOR = "Armor",
    TRAITS_WEAPON = "Weapons",
    TRAITS_JEWELRY = "Jewelry",
    HINT_STAR = "Star: wishlist",
    HINT_DOUBLE_GOTO = "Double-click: where it drops",
    HINT_DOUBLE_ACTION = "Double-click: %s",
    HINT_RIGHT = "Right-click: more",
    TT_OWNED = "You own %d:",
    TT_MORE = "... and %d more (right-click > Show my pieces)",
    TT_WHERE = "Where: %s",
    TT_BOUND = "Bound",
    TT_UNBOUND = "Not bound (tradeable)",
    TT_COLLECTED = "In your Set Collection",
    TT_NOT_COLLECTED = "Not in your Set Collection yet",
    TT_BIND_TO_COLLECT = "Not in your Set Collection yet: bind it (right-click > Bind) to unlock it",
    TT_KILL_ONLY = "Only affects XP from kills.",
    TT_OWNED_CLICK = "Click %s to show your pieces",
    TT_SHOW_IN_BAG = "In your bag: click to show it",
    MENU_SHOW_IN_BAG = "Show in my bag",
    MENU_FCO_LATER = "FCO ItemSaver: log in on %s once first",
    MENU_FCO_LATER_BANK = "FCO ItemSaver: open your bank once first",
    MENU_FCO_LATER_HOUSE = "FCO ItemSaver: visit your house once first",
    TT_FCO_MARKS = "FCO ItemSaver: %s",
    -- only used if FCOIS gives no name for one of its marks
    FCO_ICON_1 = "Lock", FCO_ICON_3 = "Research", FCO_ICON_5 = "Selling", FCO_ICON_9 = "Deconstruction",
    FCO_ICON_10 = "Improvement", FCO_ICON_11 = "Sell at guild store", FCO_ICON_12 = "Intricate",
    FCO_NEED_SCAN = "Set Hunter read %s's bags before FCO ItemSaver was installed. Log in on that character once, then you can mark this piece.",
    FCO_NEED_SCAN_BANK = "Set Hunter read your bank before FCO ItemSaver was installed. Open the bank once, then you can mark this piece.",
    FCO_NEED_SCAN_HOUSE = "Set Hunter read this storage chest before FCO ItemSaver was installed. Visit your house once, then you can mark this piece.",
    BAG_GONE = "That item isn't in your bag anymore.",
    TT_SHOW_IN_BANK = "In your bank: click to show it",
    MENU_SHOW_IN_BANK = "Show in my bank",
    BANK_GONE = "That item isn't in your bank anymore.",
    TT_ACTION_QUEUE = "Click %s to queue for %s",
    TT_ACTION_TRAVEL = "Click %s to travel to %s",
    TT_ACTION_ANTIQ = "Click %s to open your Antiquities journal",
    MENU_ANTIQ = "Open Antiquities",
    ANTIQ_LINK_TT = "Your leads, and where to scry and dig for each fragment, are in the game's Antiquities journal.",
    TT_ACTION_RANDOM = "Click %s to queue for a random dungeon",
    MENU_RANDOM = "Queue random dungeon",
    RANDOM_LINK_TT = "Pick Normal or Veteran and your role, and queue for a random dungeon.",
    TT_ACTION_BG = "Click %s to open Battlegrounds in the Group Finder",
    MENU_BG = "Open Battlegrounds",
    BG_LINK_TT = "Opens the Group Finder on Battlegrounds, where you pick a match type and queue.",
    RANDOM_DUNGEON = "Random Dungeon",
    QUEUE_RANDOM_SUB = "The game picks a dungeon for you.",
    QUEUE_RANDOM_REWARD = "Finish it for the reward; the first one each day gives the most.",

    -- Chat
    ANNOUNCE_MSG = "Wishlist sets that drop here: %s",
    CREDIT = "by %s · v%s",
    HELP = {
        "/sethunter - open or close the window",
        "/sethunter <set name> - search for a set",
        "/sethunter here - show what drops where you are",
        "/sethunter wishlist - show your wishlist",
        "/sethunter items - show every set item you own",
        "/sethunter testrun - preview the run summary window",
        "/sethunter testdrop - preview the wishlist drop alert",
        "/sethunter travelcheck - list which wayshrine each place travels to",
        "/sethunter xp - open the XP farming guide",
        "/sethunter settings - open the settings",
    },

    -- XP guide
    XP_HDR_TOP = "Best spots",
    XP_HDR_BACKUP = "Backup spots",
    XP_TIPS_TITLE = "Tips",
    GROUP_SOLO = "Solo",
    GROUP_ANY = "Solo or group",
    GROUP_DUO = "2+ players",
    BASE_GAME = "Base game",
    SETUP_HDR_GEAR = "Step 1: what to wear",
    SETUP_HDR_SKILLS = "Step 2: skills that hit many enemies",
    SETUP_HDR_SKILLS_MINE = "Step 2: skills for your %s",
    SETUP_HDR_SKILLS_OTHER = "Other classes",
    SETUP_SKILLS_TT = "Put these %s skills on your bar: %s. They hit every enemy around you, so you can kill a whole group at once.",
    SETUP_HDR_CONS = "Step 3: what to bring",
    SETUP_HDR_MUNDUS = "Step 4: which mundus stone",
    YOUR_CLASS = "your class",

    -- XP boosts you own
    STATUS_ACTIVE = "Active",
    STATUS_OFF = "Not active",
    STATUS_GROUPED = "You're grouped",
    STATUS_ENLIGHTENED = "Enlightened: %s XP",
    BADGE_BOOSTS_OWNED = "%d scrolls / Ambrosia owned",
    BOOSTS_INFO = "The bag shows how many you have on all your characters, in the bank and in house storage. Click it to see each one, its quality and who has it.",
    BADGE_ITEM = "1 item",
    BADGE_ITEMS = "%d items",
    BADGE_STORED_ONE = "in 1 place",
    BADGE_STORED = "in %d places",
    COL_AMOUNT = "AMOUNT",
    AMOUNT = "x%d",
    EMPTY_BOOSTS = "You don't have any of these on your characters, in your bank or in your house storage.\nLog in once on each character to include their bags.",
    MENU_MY_BOOSTS = "Show what I have (%d)",
    SETUP_INFO = "How to get your character ready to level fast. The idea: pull a big group of enemies and kill them all at once, with gear and boosts that give extra XP. Hover a row for the full explanation.",
    BADGE_STEPS = "4 steps",
}

-- ---------------------------------------------------------------------------
local active = "en"

function S.SetLanguage(choice)
    local lang = choice
    if lang == nil or lang == "auto" or not S.STRINGS[lang] then
        lang = GetCVar and GetCVar("language.2") or "en"
    end
    if not S.STRINGS[lang] then lang = "en" end
    active = lang
end

-- Text for key in the active language (English if missing), formatted with the extra arguments.
function S.L(key, ...)
    local text = S.STRINGS[active][key]
    if text == nil then text = S.STRINGS.en[key] end
    if text == nil then return key end
    if select("#", ...) > 0 then return string.format(text, ...) end
    return text
end

S.SetLanguage("auto")
